prebid/prebid-server-java

src/main/java/org/prebid/server/validation/RequestValidator.java
src/test/java/org/prebid/server/validation/RequestValidatorTest.java

Pushed commit with the incorrect name mentioning "comma" instead of "point"

Format decimal bidAdjustmentFactor according to US locale using decimal point separator

---

src/main/java/org/prebid/server/auction/PreBidRequestContextFactory.java
src/main/java/org/prebid/server/proto/request/PreBidRequest.java
src/test/java/org/prebid/server/auction/PreBidRequestContextFactoryTest.java

Set timeout to default value for ongoing requests in /auction endpoint when 0 <= incoming timeout > 2000

Set timeout to default value

---

src/main/java/org/prebid/server/json/ZonedDateTimeModule.java
src/test/java/org/prebid/server/cookie/UidsCookieTest.java
src/test/java/org/prebid/server/handler/GetuidsHandlerTest.java
src/test/java/org/prebid/server/json/ZonedDateTimeModuleTest.java

Currently Jackson is configured to parse timestamp with format defined at `org.prebid.server.json.ZonedDateTimeModule#FORMATTER` as `yyyy-MM-dd'T'HH:mm:ss.nnnnnnnnnXXX` (exactly 9 digits in nanoseconds part).
The problem shows up when uids cookie contains timestamps with the number of nanoseconds digits less than 9, for example 2018-03-15T14:04:19.30409244Z i.e. nanoseconds part isn't padded with zeros.

Made ZonedDateTime deserializer tolerant to variable number of nanosecond digits

---

src/main/java/org/prebid/server/currency/CurrencyConversionService.java
src/test/java/org/prebid/server/auction/CurrencyConversionServiceTest.java

As per documented in https://vertx.io/docs/apidocs/io/vertx/core/http/HttpClientRequest.html "Once you are ready to send the request, one of the end() methods should be called" , that was missing
See https://github.com/rubicon-project/prebid-server-java/issues/72

Issue 72 - Currency conversion service doesnt fetch data

---

src/main/java/org/prebid/server/auction/BidResponsePostProcessor.java
src/main/java/org/prebid/server/auction/ExchangeService.java
src/test/java/org/prebid/server/auction/ExchangeServiceTest.java

- Related issue https://github.com/rubicon-project/prebid-server-java/issues/74
- As per discussed in the original PR https://github.com/rubicon-project/prebid-server-java/pull/75 we adapt BidResponsePostProcessor

Being able to extract user's cookie sync status with each bidder

---

src/main/java/org/prebid/server/analytics/model/AmpEvent.java
src/main/java/org/prebid/server/auction/AmpResponsePostProcessor.java
src/main/java/org/prebid/server/handler/openrtb2/AmpHandler.java
src/main/java/org/prebid/server/proto/response/AmpResponse.java
src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
src/main/java/org/prebid/server/spring/config/WebConfiguration.java
src/test/java/org/prebid/server/ApplicationTest.java
src/test/java/org/prebid/server/handler/openrtb2/AmpHandlerTest.java

- related to https://github.com/rubicon-project/prebid-server-java/issues/84
- AmpResponsePostProcessor is executed prior sending the AMP RTC response back to the client, it allows companies that host Prebid Server to add custom key values in the AMP RTC response
- Changed AmpEvent and AmpResponse targeting map from Map<String, String> to Map<String, Object> to conform with RTC response specification https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/rtc-documentation.md#rtc-callout-endpoint-and-response-specification

AmpResponsePostProcessor : ease of adding custom key values in AMP RTC response

---

src/main/java/org/prebid/server/auction/ExchangeService.java
src/main/java/org/prebid/server/bidder/HttpAdapterConnector.java
src/main/java/org/prebid/server/bidder/HttpBidderRequester.java
src/main/java/org/prebid/server/bidder/model/BidderError.java
src/main/java/org/prebid/server/handler/AuctionHandler.java
src/main/java/org/prebid/server/metric/AdapterMetrics.java
src/main/java/org/prebid/server/metric/MetricName.java
src/main/java/org/prebid/server/metric/RequestMetrics.java
src/test/java/org/prebid/server/ApplicationTest.java
src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
src/test/java/org/prebid/server/bidder/HttpAdapterConnectorTest.java
src/test/java/org/prebid/server/bidder/HttpBidderRequesterTest.java
src/test/java/org/prebid/server/handler/AuctionHandlerTest.java
src/test/java/org/prebid/server/metric/MetricsTest.java

Partly addresses #81:
- `adapter.*.requests.(gotbids,nobid,badinput,badserverresponse,timeout,unkown_error)` metrics
- ` account.*.*.requests.(gotbids,nobid)` metrics

More granular bidder bids presence and error metrics

---

pom.xml

We've stumbled upon this bug after compression has been enabled recently: https://github.com/eclipse/vert.x/issues/2184.
Upgrading to a newer vert.x version fixed that issue.

Bumped up vertx version to 3.5.2 to fix the bug with Connection: close request header and enabled compression

---

src/main/resources/application.yaml

Error in log:
```
2018-07-18 08:38:47.684  WARN 2240 --- [vert.x-eventloop-thread-2] o.p.server.bidder.HttpBidderRequester    : Error occurred while sending HTTP request to a bidder
java.lang.IllegalStateException: Response is closed
at io.vertx.core.http.impl.HttpServerResponseImpl.checkValid(HttpServerResponseImpl.java:548)
at io.vertx.core.http.impl.HttpServerResponseImpl.putHeader(HttpServerResponseImpl.java:153)
at io.vertx.core.http.impl.HttpServerResponseImpl.putHeader(HttpServerResponseImpl.java:53)
at org.prebid.server.handler.openrtb2.AmpHandler.handleResult(AmpHandler.java:247)
at org.prebid.server.handler.openrtb2.AmpHandler.lambda$handle$304(AmpHandler.java:131)
at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:165)
at …
```

Fixed unhandled exception on highload

---

pom.xml
src/main/java/org/prebid/server/bidder/HttpAdapterConnector.java
src/main/java/org/prebid/server/bidder/HttpBidderRequester.java
src/main/java/org/prebid/server/handler/AuctionHandler.java
src/main/java/org/prebid/server/handler/openrtb2/AmpHandler.java
src/main/java/org/prebid/server/handler/openrtb2/AuctionHandler.java
src/main/java/org/prebid/server/spring/config/WebConfiguration.java

- Updated Vert.x to 3.5.3 version
- Replced `router.route().handler(TimeoutHandler.create(10000))` with `HttpServerOptions.setIdleTimeout(10)`
- RequestTimeMetric moved from `context.response().endHandler(...)` to `setHandler(responseResult -> handleResult(...))`

Fixed "Response is closed" exception

---

src/main/java/org/prebid/server/handler/AuctionHandler.java
src/main/java/org/prebid/server/handler/openrtb2/AmpHandler.java
src/main/java/org/prebid/server/handler/openrtb2/AuctionHandler.java
src/main/java/org/prebid/server/metric/MetricName.java
src/test/java/org/prebid/server/handler/AuctionHandlerTest.java
src/test/java/org/prebid/server/handler/openrtb2/AmpHandlerTest.java
src/test/java/org/prebid/server/handler/openrtb2/AuctionHandlerTest.java

The metrics `requests.networkerr.{legacy,openrtb2-web,openrtb2-app,amp}` was added on a step when response is considered as valid but something goes wrong on sending it to the client.

Added a metric type for network errors

---

src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtRequestPrebidCacheBids.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtRequestPrebidCacheVastxml.java

Fixed json mapping configuration - add `@JsonProperty` annotation to `returnCreative ` fields.

Fix adding new cache param - returnCreative

---

README.md

The application fails to start up without `gdpr.vendorlist.filesystem-cache-dir` and line 75 implies that `/status` will return 200 OK when it actually defaults to No Content.

add fields needed for the minimal config in the readme

---

src/main/java/org/prebid/server/auction/BidResponsePostProcessor.java
src/main/java/org/prebid/server/auction/ExchangeService.java
src/main/java/org/prebid/server/auction/PreBidRequestContextFactory.java
src/main/java/org/prebid/server/auction/PriceGranularity.java
src/main/java/org/prebid/server/auction/StoredRequestProcessor.java
src/main/java/org/prebid/server/bidder/HttpAdapterRequester.java
src/main/java/org/prebid/server/bidder/HttpBidderRequester.java
src/main/java/org/prebid/server/bidder/adform/AdformBidder.java
src/main/java/org/prebid/server/bidder/adkerneladn/AdkernelAdnBidder.java
src/main/java/org/prebid/server/bidder/adtelligent/AdtelligentBidder.java
src/main/java/org/prebid/server/bidder/appnexus/AppnexusBidder.java
src/main/java/org/prebid/server/bidder/beachfront/BeachfrontBidder.java
src/main/java/org/prebid/server/bidder/brightroll/BrightrollBidder.java
src/main/java/org/prebid/server/bidder/eplanning/EplanningBidder.java
src/main/java/org/prebid/server/bidder/facebook/FacebookBidder.java
src/main/java/org/prebid/server/bidder/rubicon/RubiconAdapter.java
src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
src/main/java/org/prebid/server/bidder/somoaudience/SomoaudienceBidder.java
src/main/java/org/prebid/server/bidder/sovrn/SovrnBidder.java
src/main/java/org/prebid/server/gdpr/GdprService.java
src/main/java/org/prebid/server/handler/openrtb2/AmpHandler.java
src/main/java/org/prebid/server/handler/openrtb2/AuctionHandler.java
src/main/java/org/prebid/server/validation/RequestValidator.java
src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
src/test/java/org/prebid/server/handler/openrtb2/AmpHandlerTest.java
src/test/java/org/prebid/server/handler/openrtb2/AuctionHandlerTest.java

Changes:
- The `BidResponsePostProcessor` interface was changed to accept `RoutingContext` argument:
```
Future<BidResponse> postProcess(RoutingContext context, BidRequest bidRequest, 
UidsCookie uidsCookie, BidResponse bidResponse);
```
- Fixed minor issues.
- Refactored code and JavaDoc.

Add RoutingContext to BidResponsePostProcessor interface

---

docs/config-app.md
docs/differenceBetweenPBSGo-and-Java.md
docs/metrics.md
pom.xml
src/main/java/org/prebid/server/handler/ConnectionHandler.java
src/main/java/org/prebid/server/metric/MetricName.java
src/main/java/org/prebid/server/metric/Metrics.java
src/main/java/org/prebid/server/metric/UpdatableMetrics.java
src/main/java/org/prebid/server/spring/config/MetricsConfiguration.java
src/main/java/org/prebid/server/spring/config/VertxConfiguration.java
src/test/java/org/prebid/server/handler/ConnectionHandlerTest.java
src/test/java/org/prebid/server/metric/MetricsTest.java

CL:
- Added `vertx-dropwizard-metrics` module to support [rich application metrics](https://vertx.io/docs/vertx-dropwizard-metrics/java/#_the_metrics).
- Used single metric registry for built-in Vertx and custom metrics.
- Custom `active_connections` metric implementation replaced with `vertx.http.servers.0.0.0.0:8080.open-netsockets.count`.
- Added `console` metrics backend for debugging purposes.
- Added new `metrics.{graphite,influxdb,console}.enabled` config properties to be more clear and simple control with metrics backends configurations.

Fix active connections metric

---

src/main/java/org/prebid/server/auction/ExchangeService.java
src/test/java/org/prebid/server/ApplicationTest.java
src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
src/test/resources/org/prebid/server/ApplicationTest/cache/update/test-auction-response.json
src/test/resources/org/prebid/server/ApplicationTest/openrtb2/adform/test-auction-adform-response.json
src/test/resources/org/prebid/server/ApplicationTest/openrtb2/adkerneladn/test-auction-adkerneladn-response.json
src/test/resources/org/prebid/server/ApplicationTest/openrtb2/adtelligent/test-auction-adtelligent-response.json
src/test/resources/org/prebid/server/ApplicationTest/openrtb2/beachfront/test-auction-beachfront-response.json
src/test/resources/org/prebid/server/ApplicationTest/openrtb2/brightroll/test-auction-brightroll-response.json
src/test/resources/org/prebid/server/ApplicationTest/openrtb2/conversant/alias/test-auction-conversant-response.json
src/test/resources/org/prebid/server/ApplicationTest/openrtb2/conversant/test-auction-conversant-response.json
src/test/resources/org/prebid/server/ApplicationTest/openrtb2/eplanning/test-auction-eplanning-response.json
src/test/resources/org/prebid/server/ApplicationTest/openrtb2/facebook/test-auction-facebook-response.json
src/test/resources/org/prebid/server/ApplicationTest/openrtb2/ix/test-auction-ix-response.json
src/test/resources/org/prebid/server/ApplicationTest/openrtb2/lifestreet/test-auction-lifestreet-response.json
src/test/resources/org/prebid/server/ApplicationTest/openrtb2/openx/test-auction-openx-response.json
src/test/resources/org/prebid/server/ApplicationTest/openrtb2/pubmatic/test-auction-pubmatic-response.json
src/test/resources/org/prebid/server/ApplicationTest/openrtb2/pulsepoint/test-auction-pulsepoint-response.json
src/test/resources/org/prebid/server/ApplicationTest/openrtb2/rhythmone/test-auction-rhythmone-response.json
src/test/resources/org/prebid/server/ApplicationTest/openrtb2/rubicon_appnexus/test-auction-rubicon-appnexus-response.json
src/test/resources/org/prebid/server/ApplicationTest/openrtb2/somoaudience/test-auction-somoaudience-response.json
src/test/resources/org/prebid/server/ApplicationTest/openrtb2/sovrn/test-auction-sovrn-response.json
src/test/resources/org/prebid/server/ApplicationTest/openrtb2/ttx/test-auction-ttx-response.json

Fixed bidresponse.ext containing empty errors list - now, if there are no errors - they are not added to .json file.

Fix bidresponse.ext containing empty errors list

---

src/main/java/org/prebid/server/bidder/rubicon/RubiconAdapter.java
src/test/java/org/prebid/server/bidder/rubicon/RubiconAdapterTest.java

CL:
- AdUnit will be skipped for invalid mediaType

Rework media type checking in legacy Rubicon adapter

---

src/main/java/org/prebid/server/cookie/UidsCookieService.java
src/test/java/org/prebid/server/cookie/UidsCookieServiceTest.java

This PR changes working with `host-cookie` and `uids`cookies.
For now PBS checked `uids`cookie and if it contains HOST-BIDDER uid then `host-cookie` is ignored.
In new behavior if `host-cookie` exists and `uids` cookie contains HOST-BIDDER uid with different value - the `host-cookie` value will be used.
So, available scenarios:
- `host-cookie` specified, `uids.HOST-BIDDER` exists, `host-cookie` value **is equal** to  `uids.HOST-BIDDER`: no action (HAPPY PATH)
- `host-cookie` specified, `uids.HOST-BIDDER` exists, `host-cookie` value **is NOT equal** to  `uids.HOST-BIDDER`: use `host-cookie` value for `uids.HOST-BIDDER`
- `host-cookie` specified, no `uids.HOST-BIDDER`: use `host-cookie` value for `uids.HOST-BIDDER`
- no `host-cookie`, `uids.HOST-BIDDER` exists: no action (continue use …

Make host-cookie precedence over uids

---

docs/endpoints/cookieSync.md
src/main/java/org/prebid/server/bidder/beachfront/BeachfrontBidder.java
src/main/java/org/prebid/server/cookie/UidsCookieService.java
src/main/java/org/prebid/server/handler/CookieSyncHandler.java
src/main/java/org/prebid/server/spring/config/WebConfiguration.java
src/test/java/org/prebid/server/ApplicationTest.java
src/test/java/org/prebid/server/handler/CookieSyncHandlerTest.java
src/test/java/org/prebid/server/validation/RequestValidatorTest.java
src/test/resources/org/prebid/server/ApplicationTest/test-application.properties

This PR continues the idea of https://github.com/rubicon-project/prebid-server-java/pull/248
It changes `/cookie_sync` behavior for two cases:
- `host-cookie` specified, `uids.HOST-BIDDER` exists, `host-cookie` value **is NOT equal** to  `uids.HOST-BIDDER`: use `host-cookie` value for `uids.HOST-BIDDER`
- `host-cookie` specified, no `uids.HOST-BIDDER`: use `host-cookie` value for `uids.HOST-BIDDER`
In both of cases we have broken `uids.HOST-BIDDER`, but valid `host-cookie` value. So, we should update `uids.HOST-BIDDER` value.
In regular situation we just put pre-configured `usersync-url` in `/cookie_sync` response. But for `HOST-BIDDER` it is not necessary to call `usersync-url`for obtaining new UID because we already have it in `host-cookie`.
So, all we need is to use direct …

Set /setuid as usersync-url for host-bidder in /cookie_sync response

---

src/main/java/org/prebid/server/bidder/appnexus/AppnexusBidder.java
src/test/java/org/prebid/server/bidder/appnexus/AppnexusBidderTest.java

- Fixed NPE occurring in AppNexus bidder when app.ext is missing;
- Added tests to cover all cases and ensure the right flow.

Fix NPE occurring in AppNexus bidder

---

src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
src/main/resources/application.yaml
src/test/resources/org/prebid/server/ApplicationTest/test-application.properties

Moved MaxMind DB file path to configuration property to avoid errors in tests when file is not being downloaded (use existing test DB file instead).

Make MaxMind DB file path being set from configuration

---

src/main/java/org/prebid/server/gdpr/GdprService.java
src/main/java/org/prebid/server/vertx/http/BasicHttpClient.java
src/test/java/org/prebid/server/gdpr/GdprServiceTest.java

CL:
- Added additional checking of VendorID in Consent String.
- Safe BasicHttpClient with `tryComplete` call on success.

Fix NPE in GdprService when Vendor ID is not in Consent

---

docs/differenceBetweenPBSGo-and-Java.md

- Updated PBS Go and Java differences document as for now Java version won't enable the support of bidders passing their extensions in imp[...].ext.prebid.bidder.

Update PBS Go and Java differences doc

---

src/main/java/org/prebid/server/analytics/model/HttpContext.java
src/test/java/org/prebid/server/handler/openrtb2/AuctionHandlerTest.java

Fixes:
```
java.lang.IllegalStateException: Duplicate key
at java.util.stream.Collectors.lambda$throwingMerger$154(Unknown Source)
at java.util.HashMap.merge(Unknown Source)
at java.util.stream.Collectors.lambda$toMap$212(Unknown Source)
at java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.collect(Unknown Source)
at org.prebid.server.analytics.model.HttpContext.headers(HttpContext.java:42)
at …
```

Fix duplicate key error while analytics HttpContext creating

---

src/main/java/org/prebid/server/auction/AmpRequestFactory.java
src/main/java/org/prebid/server/auction/AuctionRequestFactory.java
src/main/java/org/prebid/server/auction/PreBidRequestContextFactory.java
src/main/java/org/prebid/server/auction/TimeoutResolver.java
src/main/java/org/prebid/server/handler/openrtb2/AmpHandler.java
src/main/java/org/prebid/server/handler/openrtb2/AuctionHandler.java
src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
src/main/java/org/prebid/server/spring/config/WebConfiguration.java
src/test/java/org/prebid/server/auction/AmpRequestFactoryTest.java
src/test/java/org/prebid/server/auction/AuctionRequestFactoryTest.java
src/test/java/org/prebid/server/auction/PreBidRequestContextFactoryTest.java
src/test/java/org/prebid/server/auction/TimeoutResolverTest.java
src/test/java/org/prebid/server/handler/openrtb2/AmpHandlerTest.java
src/test/java/org/prebid/server/handler/openrtb2/AuctionHandlerTest.java

All timeout processing functionality delegated to `TimeoutResolver`:
- `long resolve(Long requestTimeout)` - Resolves timeout according to given in request and pre-configured default and max values.
- `long adjustTimeout(long requestTimeout)` - Determines timeout according to given in request and pre-configured adjustment value.

Fix applying of timeout adjustment

---

src/main/java/org/prebid/server/auction/PreBidRequestContextFactory.java
src/main/java/org/prebid/server/cache/CacheService.java
src/main/java/org/prebid/server/events/EventsService.java
src/main/java/org/prebid/server/handler/AuctionHandler.java
src/main/java/org/prebid/server/settings/JdbcApplicationSettings.java
src/main/java/org/prebid/server/settings/mapper/JdbcStoredDataResultMapper.java
src/test/java/org/prebid/server/settings/JdbcApplicationSettingsTest.java
src/test/java/org/prebid/server/settings/mapper/JdbcStoredDataResultMapperTest.java

Mapper used by JDBC Client should not throws exception if empty result obtained.
Otherwise, `CircuitBreakerSecuredJdbcClient` will fire up.

Fix JdbcApplicationSettings result mapper while fetching account by ID

---

src/main/java/org/prebid/server/handler/CookieSyncHandler.java
src/main/java/org/prebid/server/handler/SetuidHandler.java
src/main/java/org/prebid/server/proto/response/UsersyncInfo.java
src/test/java/org/prebid/server/handler/CookieSyncHandlerTest.java

Fixes:
- Host-bidder cookie uid value must be url-encoded in `/setuid` url.
- GDPR macro must be properly handled.

Fix host-bidder usersync-url

---

src/main/java/org/prebid/server/bidder/conversant/ConversantAdapter.java
src/main/java/org/prebid/server/bidder/conversant/ConversantBidder.java
src/main/resources/bidder-config/conversant.yaml
src/main/resources/static/bidder-params/conversant.json
src/test/java/org/prebid/server/bidder/conversant/ConversantAdapterTest.java
src/test/java/org/prebid/server/bidder/conversant/ConversantBidderTest.java

- Added support of app requests for Conversant adapter and bidder;
- Removed `site_id` from required params to ensure a correct logic when app request is received;
- Switch Conversant bidder from extending OpenrtbBidder abstract class back to implementing Bidder interface;
- Corrected existing unit tests and added couple of new ones.

Allow Conversant bidder to support app request

---

docs/config-app.md
src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
src/main/java/org/prebid/server/util/HttpUtil.java
src/test/java/org/prebid/server/util/HttpUtilTest.java

CL:
- The Pulsepoint bidder usersync-url contains doubled percent symbol `%%`. This caused the problem in `HttpUtil.encodeUrl(...)`. The `String.format(...)` method was used there and it interprets `%` as escape symbol (even no `args` given).
So, `encodeUrl` was simplified since the second argument was never used it is removed from its signature.
- Fixed `status-response` config property handling for `HealthChecker`s configuration.
- Removed `events.accounts-enabled` config property from documentation since it is not used anymore.

Fix Pulsepoint usersync-url

---

src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
src/main/java/org/prebid/server/validation/RequestValidator.java
src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java

Rubicon XAPI prefers single media type impression.
This PR leaves either banner or video if both income in prebid request. So, video will be chosen if it has fields:
- Mimes
- Protocols
- Maxduration
- Linearity
- Api
Otherwise, video should be removed.

Fix Rubicon bidder for multi-format impression processing

---

src/main/java/org/prebid/server/auction/AmpRequestFactory.java
src/main/java/org/prebid/server/auction/ExchangeService.java
src/main/java/org/prebid/server/bidder/HttpBidderRequester.java
src/main/java/org/prebid/server/handler/openrtb2/AmpHandler.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtRequestPrebid.java
src/test/java/org/prebid/server/auction/AmpRequestFactoryTest.java
src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
src/test/java/org/prebid/server/bidder/HttpBidderRequesterTest.java
src/test/java/org/prebid/server/handler/openrtb2/AmpHandlerTest.java
src/test/java/org/prebid/server/validation/RequestValidatorTest.java

CL:
- The `request.test` flag is replaced with `request.ext.prebid.debug`
- For backward compatibility on transition period `request.test` left working as well.

Replace request.test flag with request.ext.prebid.debug

---

docs/config-app.md
src/main/java/org/prebid/server/currency/CurrencyConversionService.java
src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
src/main/resources/application.yaml
src/test/java/org/prebid/server/auction/CurrencyConversionServiceTest.java

CL:
- Added `currency-converter.default-timeout-ms` config property.

Add configurable timeout for currency conversion

---

pom.xml

Fixed security alert:
> CVE-2019-12086
> 
> Vulnerable versions: >= 2.0.0, < 2.9.9
> Patched version: 2.9.9
> 
> A Polymorphic Typing issue was discovered in FasterXML jackson-databind 2.x before 2.9.9. When Default Typing is enabled (either globally or for a specific property) for an externally exposed JSON endpoint, the service has the mysql-connector-java jar (8.0.14 or earlier) in the classpath, and an attacker can host a crafted MySQL server reachable by the victim, an attacker can send a crafted JSON message that allows them to read arbitrary local files on the server. This occurs because of missing com.mysql.cj.jdbc.admin.MiniAdmin validation.

Upgrade com.fasterxml.jackson libraries to 2.9.9 version

---

src/test/java/org/prebid/server/auction/CpmRangeTest.java
src/test/java/org/prebid/server/bidder/UsersyncerTest.java
src/test/java/org/prebid/server/bidder/adtelligent/AdtelligentBidderTest.java
src/test/java/org/prebid/server/bidder/beachfront/BeachfrontBidderTest.java
src/test/java/org/prebid/server/bidder/brightroll/BrightrollBidderTest.java
src/test/java/org/prebid/server/bidder/consumable/ConsumableBidderTest.java
src/test/java/org/prebid/server/bidder/conversant/ConversantBidderTest.java
src/test/java/org/prebid/server/bidder/eplanning/EplanningBidderTest.java
src/test/java/org/prebid/server/bidder/gamoshi/GamoshiBidderTest.java
src/test/java/org/prebid/server/bidder/gumgum/GumgumBidderTest.java
src/test/java/org/prebid/server/bidder/ix/IxBidderTest.java
src/test/java/org/prebid/server/bidder/lifestreet/LifestreetBidderTest.java
src/test/java/org/prebid/server/bidder/pubmatic/PubmaticAdapterTest.java
src/test/java/org/prebid/server/bidder/pulsepoint/PulsepointBidderTest.java
src/test/java/org/prebid/server/bidder/somoaudience/SomoaudienceBidderTest.java
src/test/java/org/prebid/server/bidder/ttx/TtxBidderTest.java
src/test/java/org/prebid/server/bidder/yieldmo/YieldmoBidderTest.java
src/test/java/org/prebid/server/cache/CacheServiceTest.java
src/test/java/org/prebid/server/geolocation/CircuitBreakerSecuredGeoLocationServiceTest.java
src/test/java/org/prebid/server/handler/NotificationEventHandlerTest.java
src/test/java/org/prebid/server/it/AdformTest.java
src/test/java/org/prebid/server/it/ApplicationTest.java
src/test/java/org/prebid/server/it/IntegrationTest.java
src/test/java/org/prebid/server/settings/FileApplicationSettingsTest.java
src/test/java/org/prebid/server/settings/HttpApplicationSettingsTest.java
src/test/java/org/prebid/server/settings/service/JdbcPeriodicRefreshServiceTest.java
src/test/java/org/prebid/server/vertx/CircuitBreakerTest.java
src/test/java/org/prebid/server/vertx/http/CircuitBreakerSecuredHttpClientTest.java

CL:
- Added delay while calling `/currency-rates` admin endpoint in `currencyRatesHandlerShouldRespondWithLastUpdateDate` test.
- The `Adform` application test moved to the separate class.
- Tunned waiting time in `CircuitBreaker` related tests.
- Applied code formatting to all tests.

Fix currency rates handler test in application test

---

src/main/java/org/prebid/server/auction/AmpRequestFactory.java
src/main/java/org/prebid/server/auction/AuctionRequestFactory.java
src/main/java/org/prebid/server/bidder/rubicon/RubiconSize.java
src/test/java/org/prebid/server/auction/AmpRequestFactoryTest.java
src/test/java/org/prebid/server/auction/AuctionRequestFactoryTest.java

CL:
- Fixed http request query string `debug` param processing for AMP.
- Fixed setting of `ext.prebid.debug` when dealing with `ExtRequestPrebid` through builder.

Fix ext.prebid.debug processing in Auction/Amp request factory

---

src/main/java/org/prebid/server/auction/ExchangeService.java
src/main/java/org/prebid/server/gdpr/GdprService.java
src/main/java/org/prebid/server/settings/FileApplicationSettings.java
src/main/java/org/prebid/server/settings/JdbcApplicationSettings.java
src/main/java/org/prebid/server/settings/model/Account.java
src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
src/test/java/org/prebid/server/cache/CacheServiceTest.java
src/test/java/org/prebid/server/events/EventsServiceTest.java
src/test/java/org/prebid/server/gdpr/GdprServiceTest.java
src/test/java/org/prebid/server/handler/AuctionHandlerTest.java
src/test/java/org/prebid/server/settings/CachingApplicationSettingsTest.java
src/test/java/org/prebid/server/settings/CompositeApplicationSettingsTest.java
src/test/java/org/prebid/server/settings/FileApplicationSettingsTest.java
src/test/java/org/prebid/server/settings/JdbcApplicationSettingsTest.java
src/test/resources/org/prebid/server/it/test-app-settings.yaml

(!) Breaking changes: `Account` is extended with `enforceGdpr` flag.
So, SQL scheme for `jdbc` application settings should be updated.
The `file` and `http` application settings can be used safely.

Add support for per-account enforce-GDPR flag

---

docs/endpoints/info/bidders/bidderName.md
src/main/java/org/prebid/server/handler/info/BidderDetailsHandler.java
src/main/java/org/prebid/server/proto/response/BidderInfo.java
src/test/java/org/prebid/server/handler/info/BidderDetailsHandlerTest.java
src/test/resources/org/prebid/server/it/info-bidders/test-info-bidder-details-response.json

CL:
- Fixed `/info/bidders/<BIDDER_NAME>` to respond with bidder details for active only bidder.
- Fixed `/info/bidders/<BIDDER_ALIAS>` to respond with bidder details for active only bidder by alias.
- Added `/info/bidders/all` to respond with bidder details for all active bidders.

Modify bidder info endpoint to be able to get all bidder details

---

src/main/java/org/prebid/server/bidder/beachfront/BeachfrontBidder.java
src/test/java/org/prebid/server/bidder/beachfront/BeachfrontBidderTest.java

Beachfront is now sending an empty array and 200 as their "no results" response.
Add headers from Device.* method
Add tests

Beachfront empty array and 200 as "no results" response

---

src/main/java/org/prebid/server/auction/AuctionRequestFactory.java
src/main/java/org/prebid/server/validation/RequestValidator.java
src/test/java/org/prebid/server/auction/AuctionRequestFactoryTest.java
src/test/java/org/prebid/server/validation/RequestValidatorTest.java
src/test/resources/org/prebid/server/it/openrtb2/rubicon_appnexus/test-auction-rubicon-appnexus-request.json

Example OpebRTB request:
```
{
...
"user": {
"ext": {
"digitrust": {
"id": "id",
"keyv": 1
}
}
}
...
}
```
will result in exchange request:
```
{
...
"user": {
"ext": {
"digitrust": {
"id": "id",
"keyv": 1,
"pref": 0
}
}
}
...
}
```

Set default request.user.ext.digitrust.perf value to 0 if not defined

---

src/main/java/org/prebid/server/auction/ExchangeService.java
src/main/java/org/prebid/server/auction/model/RequestContext.java
src/main/java/org/prebid/server/handler/openrtb2/AmpHandler.java
src/main/java/org/prebid/server/handler/openrtb2/AuctionHandler.java
src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
src/test/java/org/prebid/server/handler/openrtb2/AmpHandlerTest.java
src/test/java/org/prebid/server/handler/openrtb2/AuctionHandlerTest.java

Changed main method of ExchangeService from
```
public Future<BidResponse> holdAuction(BidRequest bidRequest, UidsCookie uidsCookie, 
Timeout timeout, MetricsContext metricsContext, RoutingContext context) {...}
```
to
```
public Future<BidResponse> holdAuction(RequestContext context) {...}
```
The `RequestContext` object repsents the context of `BidRequest` and contains all needed data to perform auction.

Add request context to ExchangeService

---

src/main/java/org/prebid/server/auction/ExchangeService.java
src/main/java/org/prebid/server/auction/PrivacyEnforcementService.java
src/test/java/org/prebid/server/auction/PrivacyEnforcementServiceTest.java

No reason to return empty User object if all fields were masked. Fixed to respond with null if so.

Fix PrivacyEnforcementService to return null User if empty

---

src/main/java/org/prebid/server/auction/ExchangeService.java
src/main/java/org/prebid/server/auction/PrivacyEnforcementService.java
src/main/java/org/prebid/server/gdpr/GdprService.java
src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
src/test/java/org/prebid/server/auction/PrivacyEnforcementServiceTest.java
src/test/java/org/prebid/server/gdpr/GdprServiceTest.java

- Changed GdprService to use `Boolean isGdprEnforced` value from AuctionContext's Account, instead of calling `ApplicationSettings.getAccountById` and retrieving `isGdprEnforced` from it;
- Corrected unit tests to reflect the changes.

Make GdprService use Account from AuctionContext

---

docs/endpoints/setuid.md
src/main/java/org/prebid/server/handler/SetuidHandler.java
src/test/java/org/prebid/server/handler/SetuidHandlerTest.java

When we receive /setuid...&format=img, we response with pixel file.

Add handling of format parameter in /setuid

---

src/main/java/org/prebid/server/bidder/rubicon/RubiconAdapter.java
src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java

Fix rubicon empty user.target when inventory and visitor is empty

Omit request.user.ext.rp.target if empty in Rubicon bidder

---

docs/bidders/appnexus.md
docs/differenceBetweenPBSGo-and-Java.md
docs/pbs-java-and-go-features-review.md

Updated `docs/bidders/appnexus.md`, `docs/differenceBetweenPBSGo-and-Java.md` and `docs/pbs-java-and-go-features-review.md ` documents.

Update appnexus and PBS java/go difference docs

---

src/test/java/org/prebid/server/execution/RemoteFileSyncerTest.java

Add system independent file path creation

fix RemoteFileSyncTest to work on Windows

---

docs/config-app.md
src/main/java/org/prebid/server/spring/config/WebConfiguration.java
src/main/resources/application.yaml

Vert.x set default size for all headers to 8kB which can be too small for Prebid Server since `uids` can be large.
Added `http.max-headers-size` config property to fix the error:
```
2019-08-22 00:00:00.465  WARN 28553 --- [vert.x-eventloop-thread-4] o.p.server.handler.ExceptionHandler      : Error while establishing HTTP connection
io.netty.handler.codec.TooLongFrameException: HTTP header is larger than 8192 bytes.
at io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.newException(HttpObjectDecoder.java:837)
at io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.process(HttpObjectDecoder.java:829)
at io.netty.buffer.AbstractByteBuf.forEachByteAsc0(AbstractByteBuf.java:1298)
at io.netty.buffer.AbstractByteBuf.forEachByte(AbstractByteBuf.java:1278)
at …
```

Increase HTTP headers size

---

src/main/java/org/prebid/server/handler/BidderParamHandler.java
src/main/java/org/prebid/server/handler/CookieSyncHandler.java
src/main/java/org/prebid/server/handler/GetuidsHandler.java
src/main/java/org/prebid/server/handler/NoCacheHandler.java
src/main/java/org/prebid/server/handler/SetuidHandler.java
src/main/java/org/prebid/server/handler/StatusHandler.java
src/main/java/org/prebid/server/handler/VersionHandler.java
src/main/java/org/prebid/server/handler/openrtb2/AmpHandler.java
src/main/java/org/prebid/server/handler/openrtb2/AuctionHandler.java
src/test/java/org/prebid/server/handler/NoCacheHandlerTest.java
src/test/java/org/prebid/server/handler/SetuidHandlerTest.java
src/test/java/org/prebid/server/handler/openrtb2/AmpHandlerTest.java
src/test/java/org/prebid/server/handler/openrtb2/AuctionHandlerTest.java

This PR fixes error, like:
```
2019-08-22 00:00:03.028 ERROR 28553 --- [vert.x-eventloop-thread-8] io.vertx.core.impl.ContextImpl           : Unhandled exception
java.lang.IllegalStateException: Response is closed
at io.vertx.core.http.impl.HttpServerResponseImpl.checkValid(HttpServerResponseImpl.java:564)
at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:324)
at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:313)
at io.vertx.ext.web.impl.RoutingContextImplBase.unhandledFailure(RoutingContextImplBase.java:166)
at io.vertx.ext.web.impl.RoutingContextImpl.checkHandleNoMatch(RoutingContextImpl.java:143)
at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:135)
at …
```

Improve handling "Response is closed" error

---

src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/rubicon/ExtImpRubicon.java

- Changed ImpExtRubicon inventory and visitor fields type from `JsonNode` to `ObjectNode` as specified in `rubicon.json` bidder parameters description.
- Modified Rubicon Bidder request processing to reflect the changes.

Change ImpExtRubicon inventory and visitor fields type

---

src/main/java/org/prebid/server/geolocation/CircuitBreakerSecuredGeoLocationService.java
src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
src/main/java/org/prebid/server/spring/config/SettingsConfiguration.java
src/main/java/org/prebid/server/vertx/CircuitBreaker.java
src/main/java/org/prebid/server/vertx/http/CircuitBreakerSecuredHttpClient.java
src/main/java/org/prebid/server/vertx/jdbc/CircuitBreakerSecuredJdbcClient.java
src/test/java/org/prebid/server/geolocation/CircuitBreakerSecuredGeoLocationServiceTest.java
src/test/java/org/prebid/server/vertx/CircuitBreakerTest.java
src/test/java/org/prebid/server/vertx/http/CircuitBreakerSecuredHttpClientTest.java
src/test/java/org/prebid/server/vertx/jdbc/CircuitBreakerSecuredJdbcClientTest.java

This PR fixes error:
```
2019-08-22 07:26:53.942  WARN 6420 --- [vertx-blocked-thread-checker] io.vertx.core.impl.BlockedThreadChecker  : Thread Thread[vert.x-eventloop-thread-4,5,main] has been blocked for 572566 ms, time limit i
s 2000 ms                                                                                                                                                                                                    
io.vertx.core.VertxException: Thread blocked                                                                                                                                                                 
at io.vertx.circuitbreaker.impl.CircuitBreakerImpl.state(CircuitBreakerImpl.java:185) …
```

Fix CircuitBreaker Thread blocked error

---

src/main/java/org/prebid/server/analytics/model/NotificationEvent.java
src/main/java/org/prebid/server/handler/NotificationEventHandler.java
src/main/java/org/prebid/server/spring/config/WebConfiguration.java
src/test/java/org/prebid/server/handler/NotificationEventHandlerTest.java
src/test/java/org/prebid/server/it/ApplicationTest.java

Implementation for /event?t=(win|imp)&b=BIDID&a=ACCOUNT[&f=i&x=0]
ApplicationSettings for retrieving info about EventEnable for account.
We never send second response.
For emptyAccount we send 401, not 400.
Be aware that I use 14062 id from configuration for integration test.

Event of Win/Imp type handling

---

src/main/java/org/prebid/server/analytics/model/NotificationEvent.java
src/main/java/org/prebid/server/events/EventsService.java
src/main/java/org/prebid/server/handler/NotificationEventHandler.java
src/main/java/org/prebid/server/handler/SettingsCacheNotificationHandler.java
src/main/java/org/prebid/server/proto/openrtb/ext/response/Events.java
src/test/java/org/prebid/server/events/EventsServiceTest.java
src/test/java/org/prebid/server/handler/NotificationEventHandlerTest.java
src/test/java/org/prebid/server/it/ApplicationTest.java
src/test/resources/org/prebid/server/it/openrtb2/rubicon_appnexus/test-auction-rubicon-appnexus-response.json

CL:
- Use `Accout` object instead of `accout id` string in NotificationEvent
- Fixed type `t` parameter values: `win/imp` instead of `w/i`
- NotificationEventHandler returns HTTP 500 in case of error while account fetching

Refactor of NotificationEventHandler

---

docs/differenceBetweenPBSGo-and-Java.md
docs/endpoints/info/bidders.md

As it was decided with @bretg, the `/info/bidders` and `/info/bidders/{bidderName}` endpoints would keep a different behaviour from PBS-Go - Java won't display disabled bidders and will return 404 when trying to get an info for one which is not in active list.
Therefore, I've updated `bidders.md` and difference docs to emphasize these distinctions.

Update bidders and difference docs on bidder info

---

src/main/java/org/prebid/server/auction/ExchangeService.java
src/main/java/org/prebid/server/cache/CacheService.java
src/main/java/org/prebid/server/handler/NotificationEventHandler.java
src/main/java/org/prebid/server/handler/VtrackHandler.java
src/main/java/org/prebid/server/spring/config/WebConfiguration.java
src/test/java/org/prebid/server/cache/CacheServiceTest.java
src/test/java/org/prebid/server/handler/VtrackHandlerTest.java

PBS should validate the arguments supplied with /vtrack: if ACCOUNT, BIDID, or BIDDER aren't supplied, it should reject the /vtrack request with 400. This should get caught when the page is being tested.
If the ACCOUNT doesn't exist and PBS is enforcing accounts, that should also result in a 400.
PBS will process /vtrack similar to the server-side VAST response, inserting impression tracking when:
- account ID allows events
- the bidder allows VAST modification
See for details https://github.com/prebid/prebid-server/issues/1015

Change /vtrack endpoint for updated requirements

---

src/main/java/org/prebid/server/handler/VtrackHandler.java
src/test/java/org/prebid/server/handler/VtrackHandlerTest.java

Fixed error:
```
2019-09-23 09:35:18.946 ERROR 30452 --- [vert.x-eventloop-thread-3] io.vertx.core.impl.ContextImpl           : Unhandled exception
java.lang.NullPointerException: null
at org.prebid.server.handler.VtrackHandler.handleAccountResult(VtrackHandler.java:123)
at org.prebid.server.handler.VtrackHandler.lambda$handle$1(VtrackHandler.java:70)
at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125)
at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86)
at io.vertx.core.Future.lambda$recover$4(Future.java:385)
at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125)
at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86)
at io.vertx.core.Future.lambda$recover$4(Future.java:385)
at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125)
at …
```

Fix NPE in /vtrack handler if account.events_enabled is NULL

---

src/main/java/org/prebid/server/auction/AuctionRequestFactory.java
src/test/java/org/prebid/server/auction/AuctionRequestFactoryTest.java

Fixes NPE when `imp` has no `ext` object:
```
2019-09-25 08:48:15.903 ERROR 20589 --- [vert.x-eventloop-thread-0] o.p.s.handler.openrtb2.AuctionHandler    : Critical error while running the auction                                        
java.lang.NullPointerException: null                                                                                                                                                                         
at org.prebid.server.auction.AuctionRequestFactory.lambda$aliasesOrNull$5(AuctionRequestFactory.java:474)                                                                                            
at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) …
```

Fix aliases processing from imp.ext if it is missing

---

docs/config-app.md
src/main/java/org/prebid/server/auction/AuctionRequestFactory.java
src/main/java/org/prebid/server/exception/UnauthorizedAccountException.java
src/main/java/org/prebid/server/handler/openrtb2/AmpHandler.java
src/main/java/org/prebid/server/handler/openrtb2/AuctionHandler.java
src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
src/main/resources/application.yaml
src/test/java/org/prebid/server/auction/AuctionRequestFactoryTest.java
src/test/java/org/prebid/server/handler/openrtb2/AmpHandlerTest.java
src/test/java/org/prebid/server/handler/openrtb2/AuctionHandlerTest.java

```
settings:
enforce-valid-account: true // defaults to false
```
if option is true, PBS will reject any request (/openrtb2/auction or /amp) that don't carry an account ID with an HTTP 401.

Add configuration property to process only predefined accounts id.

---

pom.xml
src/main/java/org/prebid/server/vertx/CircuitBreaker.java

This PR fixes logging in `Circuit Breaker`:
```
2019-10-03 01:35:50.063  WARN 22561 --- [ntloop-thread-4] org.prebid.server.vertx.CircuitBreaker   : Resetting circuit breaker state failed
java.util.concurrent.TimeoutException: Timeout period of 756ms has been exceeded
at org.prebid.server.vertx.http.BasicHttpClient.handleTimeout(BasicHttpClient.java:66)
at org.prebid.server.vertx.http.BasicHttpClient.lambda$request$0(BasicHttpClient.java:42)
at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:907)
at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:866)
at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
at …
```

Fix circuit breaker logging when ensuring state is failed

---

pom.xml
src/main/java/org/prebid/server/auction/AuctionRequestFactory.java
src/test/java/org/prebid/server/auction/AuctionRequestFactoryTest.java

This PR fixes #484 and changes of **includebidderkeys** determining:
- if `ext.prebid.targeting.includebidderkeys` **is defined** (true/false) -> then use it and take precedence over `ext.prebid.cache.winningonly` flag: if true - then `ext.prebid.cache.winningonly` is ignored, if false - then `ext.prebid.cache.winningonly` is used as usual.
- if `ext.prebid.targeting.includebidderkeys` **is not defined** - then set it to **false** only in case if `ext.prebid.cache.winningonly == true`, otherwise - **true**.

Fix supporting of ext.prebid.cache.winningonly flag

---

src/main/java/org/prebid/server/bidder/HttpBidderRequester.java
src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
src/test/java/org/prebid/server/bidder/HttpBidderRequesterTest.java
src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java

- Updated `HttpBidderRequester` to not filter out http responses with 204 No Content status;
- Updated `RubiconBidder#makeBids` method to check the response status first - if it is 204, meaning that there are no errors, but no bids either - return empty response;
- Updated existing unit test in `HttpBidderRequesterTest` and added a new one in `RubiconBidderTest` to reflect the changes.

Update rubicon bidder to accept and handle a 204 No Content response

---

src/main/java/org/prebid/server/auction/AuctionRequestFactory.java
src/test/java/org/prebid/server/auction/AuctionRequestFactoryTest.java

Fixed leaking host cookie to all bidders. 
After looking into our code I've found that we do have the same issue as GO had, which is the result of host cookie value being set to `user.id`. Also, this change is a simple necessity to keep PBS-Java up with GO in terms of protocol and processing standards.

Fix leaking host cookie to all bidders

---

src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java

For Rubicon bidder, pass `imp[].ext.context.data.adslot` to ` imp[].ext.rp.target.dfp_ad_unit_code` without leading slash (if any).

Pass Prebid adSlot to Rubicon bidder XAPI

---

src/main/java/org/prebid/server/auction/AmpRequestFactory.java
src/test/java/org/prebid/server/auction/AmpRequestFactoryTest.java
src/test/java/org/prebid/server/it/ApplicationTest.java
src/test/resources/org/prebid/server/it/amp/test-appnexus-bid-request.json

- Added `account` query param support for `/openrtb2/amp` endpoint;
- Added new and updated existing unit and application tests.

Add Account query param support for AMP endpoint

---

src/main/java/org/prebid/server/auction/BidResponseCreator.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtMediaTypePriceGranularity.java
src/main/java/org/prebid/server/validation/RequestValidator.java
src/test/java/org/prebid/server/validation/RequestValidatorTest.java

Fixed missing media type price granularity node being displayed as a NullNode i.e. a field would have `null` value, despite json mapper set to ignore `null` fields.

Fix displaying missing Json Node as Null Node

---

docs/metrics.md
src/main/java/org/prebid/server/gdpr/GdprService.java
src/main/java/org/prebid/server/metric/MetricName.java
src/main/java/org/prebid/server/metric/Metrics.java
src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
src/test/java/org/prebid/server/gdpr/GdprServiceTest.java
src/test/java/org/prebid/server/metric/MetricsTest.java

- Added new Geo Location metrics that count overall amount of requests as well as amount of successful and failed responses from Geo Location Service;
- Added unit tests for new metrics and updated existing tests where new metrics were added to reflect and ensure the correct behavior;
- Updated `metrics.md` document for new metrics and added description for existing but not mentioned `geolocation_circuitbreaker_*` metrics.

Add Geo Location metrics

---

src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
src/test/java/org/prebid/server/bidder/appnexus/AppnexusBidderTest.java
src/test/java/org/prebid/server/bidder/facebook/FacebookBidderTest.java
src/test/java/org/prebid/server/bidder/openx/OpenxBidderTest.java
src/test/java/org/prebid/server/bidder/sovrn/SovrnBidderTest.java

`mapper.valueToTree(ext)` now producing `NullNode` when null is received
in 2.9.10 method returns `null`. (NullNode is not extends ObjectNode)
Also `was expecting ('true', 'false' or 'null')` ->
`was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')`
in error message.

Fix tests for jackson 2.10

---

src/main/java/org/prebid/server/bidder/HttpBidderRequester.java
src/test/java/org/prebid/server/bidder/HttpBidderRequesterTest.java

This PR fixes #461 when PBS response has non-critical error like:
```
Failed to decode: No content to map due to end-of-input\n 
at [Source: (String)\"\"; line: 1, column: 0]
```

Fix HttpBidderRequester to pass empty json body for 204 response status

---

src/main/resources/bidder-config/yieldmo.yaml

Updated Yieldmo bidder endpoint protocol to `https`.

Update endpoint protocol for Yieldmo bidder

---

src/main/java/org/prebid/server/spring/config/bidder/model/BidderConfigurationProperties.java

Added `extra-info` optional param for .yaml bidder configuration. Tried adding it as a JsonNode with no success as Spring refused to apply the registered converter bean, therefore left the property as a plain string.

Add extra info param for bidder configuration

---

src/main/java/org/prebid/server/auction/AuctionRequestFactory.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtPublisher.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtPublisherPrebid.java
src/test/java/org/prebid/server/auction/AuctionRequestFactoryTest.java

Moved `publisher.ext.parentAccount` property to `publisher.ext.prebid` and updated unit tests to back up the changes.

Move publisher.ext.parentAccount property to publisher.ext.prebid

---

src/main/java/org/prebid/server/execution/RemoteFileProcessor.java
src/main/java/org/prebid/server/execution/RemoteFileSyncer.java
src/main/java/org/prebid/server/geolocation/MaxMindGeoLocationService.java
src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
src/test/java/org/prebid/server/execution/RemoteFileSyncerTest.java
src/test/java/org/prebid/server/geolocation/MaxMindGeoLocationServiceTest.java

When existing file is corrupted. (Service return failedFuture)
We remove that file and download again.
Works only first time, if later file is still corrupted, there will be error log only.
Add special interface `RemoteFileProcessor` for services which depends on remote files.

Handle corrupted starter file for RemoteFileSyncer 

---

.github/workflows/pullrequest.yml
README.md

Add some badges to README.md.
I decided to not include build on `push` to master. Bc we always use PRs for all features. Also, you can include 11 to `strategy.matrix.java` to verify version compatibility.
Be aware, that Java CI will be triggered by all `pull_request` event types (after each commit)
Later I want to add separate workflow to build Docker image on `release` event.

Add Github Actions

---

src/main/resources/static/bidder-params/rubicon.json
src/test/resources/org/prebid/server/it/openrtb2/rubicon_appnexus/test-auction-rubicon-appnexus-request.json
src/test/resources/org/prebid/server/it/openrtb2/rubicon_appnexus/test-auction-rubicon-appnexus-response.json

Modified JSON schema for Rubicon bidder params to accept multiple format for `playerWidth` and `playerHeight`:
```
"imp": [
{
"ext": {
"rubicon": {
"video": {
"playerWidth": 624,
"playerHeight": 351
}
}
}
```
and
```
"imp": [
{
"ext": {
"rubicon": {
"video": {
"playerWidth": "624",
"playerHeight": "351"
}
}
}
```
This PR fixes https://github.com/rubicon-project/prebid-server-java/pull/565

Change Rubicon player width/height params to accept integer or string

---

src/main/java/org/prebid/server/proto/response/UsersyncInfo.java
src/main/resources/bidder-config/grid.yaml
src/test/java/org/prebid/server/proto/response/UsersyncInfoTest.java

- Updated Grid usersync url and redirect url;
- Added redirect url query parameters handling since in GO they just pass `redirectUrl` as a string, which already contains encoded value (and, like in this case, also query params), while we encode the whole string later (instead a certain part should be encoded).

Update Grid usersync url

---

src/main/java/org/prebid/server/auction/AmpRequestFactory.java
src/main/java/org/prebid/server/auction/AuctionRequestFactory.java
src/main/java/org/prebid/server/auction/StoredRequestProcessor.java
src/main/java/org/prebid/server/exception/InvalidRequestException.java
src/main/java/org/prebid/server/handler/openrtb2/AmpHandler.java
src/main/java/org/prebid/server/handler/openrtb2/AuctionHandler.java
src/test/java/org/prebid/server/auction/AuctionRequestFactoryTest.java
src/test/java/org/prebid/server/handler/openrtb2/AmpHandlerTest.java
src/test/java/org/prebid/server/handler/openrtb2/AuctionHandlerTest.java

This PR adds Referring URL to logs if:
- Incoming bid request cannot be parsed
- AMP request not found by tag_id or other stored request processing error

Add referrer logging for invalid request

---

src/main/resources/bidder-config/eplanning.yaml
src/main/resources/static/bidder-params/eplanning.json
src/test/java/org/prebid/server/bidder/eplanning/EplanningBidderTest.java
src/test/java/org/prebid/server/it/EplanningTest.java

Before:
http://eplanning.com/
After:
https://eplanning.com/

Replaсe http calls from E-Planning bidder to https to keep up with Go version

---

docs/config-app.md
src/main/java/org/prebid/server/spring/config/MetricsConfiguration.java

Sometimes influxDb tags can come in handy to split data by region, hostname etc.
I find there is no tagging in current prebid-server-java.
As dropwizard-metrics-influxdb already has tags support, I suggest this simple implementation.

Add Influxdb tags configuration

---

src/main/java/org/prebid/server/auction/ExchangeService.java

This PR fixes First Party Data applying for `imp[].ext.context.data`.
Especially, mapping `imp[].ext.context.data.adslot` to `imp[].ext.rp.target.dfp_ad_unit_code`.
Before, to apply FPD we had to specify bidders explicitly: 
```
"ext": {
"prebid": {
"data": {
"bidders": [ "rubicon" ]
}
}
```
Take into account, this is just a hotfix. After https://github.com/prebid/prebid-server/issues/879 reworked - changes may be removed.

Hotfix imp[].ext.context.data.adslot issue

---

src/main/java/org/prebid/server/analytics/model/NotificationEvent.java
src/main/java/org/prebid/server/auction/BidResponseCreator.java
src/main/java/org/prebid/server/auction/ExchangeService.java
src/main/java/org/prebid/server/cache/CacheService.java
src/main/java/org/prebid/server/cache/model/CacheContext.java
src/main/java/org/prebid/server/cache/proto/request/PutObject.java
src/main/java/org/prebid/server/events/EventRequest.java
src/main/java/org/prebid/server/events/EventUtil.java
src/main/java/org/prebid/server/events/EventsService.java
src/main/java/org/prebid/server/handler/NotificationEventHandler.java
src/main/java/org/prebid/server/handler/VtrackHandler.java
src/test/java/org/prebid/server/auction/BidResponseCreatorTest.java
src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
src/test/java/org/prebid/server/cache/CacheServiceTest.java
src/test/java/org/prebid/server/events/EventUtilTest.java
src/test/java/org/prebid/server/handler/NotificationEventHandlerTest.java
src/test/java/org/prebid/server/handler/VtrackHandlerTest.java
src/test/java/org/prebid/server/it/ApplicationTest.java
src/test/resources/org/prebid/server/it/vtrack/test-cache-request.json
src/test/resources/org/prebid/server/it/vtrack/test-vtrack-request.json

See parent PR https://github.com/rubicon-project/prebid-server-java/pull/635

Add timestamp and biddercode to event URL - refactored

---

docs/config-app.md
src/main/java/org/prebid/server/handler/AccountCacheInvalidationHandler.java
src/main/java/org/prebid/server/settings/CachingApplicationSettings.java
src/main/java/org/prebid/server/spring/config/WebConfiguration.java
src/main/resources/application.yaml
src/test/java/org/prebid/server/handler/AccountCacheInvalidationHandlerTest.java

`/cache/invalidate?account={accountId}`
config:
`settings.in-memory-cache.account-invalidation-enabled` = true

 Add protected endpoint to invalidate account from cache

---

src/main/java/org/prebid/server/privacy/gdpr/Tcf2Service.java
src/main/java/org/prebid/server/privacy/gdpr/tcfstrategies/purpose/PurposeStrategy.java
src/test/java/org/prebid/server/privacy/gdpr/Tcf2ServiceTest.java

When GVL call failed we downgrade type to basic.
I tried several variants for simplification of `permissionsForInternal`
* You can't create straight forward workflow (
```
.map (p)
.otherwise/recover (downgraded p)
.map` bc in this case you'll be handling exception that can be occurred in map (p).
```
* `setHandle` also bad option, bc it will rethrow failed future.
* Finally, I discovered that compose have overloaded method that can handle both use cases.
Also replaceв lambda with precreation of VendorPermission. (But now we create more objects)

Add downgrading to basic when GVL list failed

---

pom.xml

Upgrade TCF library from `2.0.0-alpha.0` to `2.0.7`.
The old version gives incorrect results, for example the consent `COzw4jqOzw4mAA0BOGUS` was found as valid.

Upgrade iabtcf to 2.0.7 version

---

src/main/java/org/prebid/server/auction/AmpRequestFactory.java
src/main/java/org/prebid/server/auction/AuctionRequestFactory.java
src/main/java/org/prebid/server/identity/IdGenerator.java
src/main/java/org/prebid/server/identity/IdGeneratorType.java
src/main/java/org/prebid/server/identity/NoneIdGenerator.java
src/main/java/org/prebid/server/identity/UUIDIdGenerator.java
src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
src/main/resources/application.yaml
src/test/java/org/prebid/server/auction/AuctionRequestFactoryTest.java
src/test/java/org/prebid/server/identity/NoneIdGeneratorTest.java
src/test/java/org/prebid/server/identity/UUIDIdGeneratorTest.java
src/test/resources/org/prebid/server/it/test-application.properties

Implements first part of https://github.com/prebid/prebid-server/issues/1337
```
All request types should have a source.tid. If the incoming request doesn't have one, 
Prebid Server should generate a random UUID.
```

Generate source.tid if it wasn't defined in request

---

src/main/java/org/prebid/server/privacy/PrivacyExtractor.java
src/main/java/org/prebid/server/validation/RequestValidator.java
src/test/java/org/prebid/server/bidder/HttpAdapterConnectorTest.java
src/test/java/org/prebid/server/privacy/PrivacyExtractorTest.java
src/test/java/org/prebid/server/validation/RequestValidatorTest.java

This PR follows https://github.com/prebid/prebid-server/issues/1129 for **CCPA Phase 2 changes** and fixes: 
```
If a CCPA signal is invalid, process the bid request as normal 
and send a warning back to the publisher in a bid response indicating 
the CCPA was invalid and ignored.
```
But leaves unchanged bid response until #758 will be done.

Make invalid CCPA string doesn't break the auction

---

src/main/java/org/prebid/server/auction/ExchangeService.java
src/test/java/org/prebid/server/auction/ExchangeServiceTest.java

PBS rejects bidder-specific schains when a given bidder is defined more than once.

Reject duplicated schains

---

src/main/java/org/prebid/server/handler/openrtb2/AmpHandler.java
src/main/java/org/prebid/server/handler/openrtb2/AuctionHandler.java
src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
src/test/java/org/prebid/server/handler/openrtb2/AmpHandlerTest.java
src/test/java/org/prebid/server/handler/openrtb2/AuctionHandlerTest.java

The issue - currently we cannot see the logs for invalid requests.
This PR fixed it.
PS. This PR should be revised after https://github.com/rubicon-project/prebid-server-java/pull/618 is merged.

Add conditionalLogger instead of adminManager in Auction & Amp handlers

---

src/main/java/org/prebid/server/auction/ExchangeService.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtRequestPrebid.java
src/test/java/org/prebid/server/auction/ExchangeServiceTest.java

This PR discards using of `bidrequest.ext.prebid.bidderconfig` field processing entirely from #573.
PS. we'll back to it after revising requirements.

Revert First Party Data bidderconfig

---

.github/release-drafter-config.yml
.github/workflows/release-drafter.yml

After this workflow is configured it starts reacting on specific commits to `master` branch pushed by `maven-release-plugin` and having message `Prebid Server prepare release <tag>`.
The workflow leverages Release Drafter action to publish a release with release notes (consisting of PRs contained in this release).
Caveat: the workflow kicks-off when commit is pushed i.e. before tag is pushed by `maven-release-plugin`. That should not be an issue since bootstrapping workflow and its actions takes time and delay between pushing commit and tag is really short.

Create Github Actions workflow for publishing new releases

---

docs/metrics.md
src/main/java/org/prebid/server/metric/Metrics.java
src/main/java/org/prebid/server/metric/TcfMetrics.java
src/main/java/org/prebid/server/privacy/gdpr/TcfDefinerService.java
src/main/java/org/prebid/server/privacy/gdpr/model/TCStringEmpty.java
src/main/java/org/prebid/server/privacy/gdpr/vendorlist/VendorListService.java
src/test/java/org/prebid/server/metric/MetricsTest.java
src/test/java/org/prebid/server/privacy/gdpr/TcfDefinerServiceTest.java
src/test/java/org/prebid/server/privacy/gdpr/vendorlist/VendorListServiceV1Test.java
src/test/java/org/prebid/server/privacy/gdpr/vendorlist/VendorListServiceV2Test.java

This PR changes the metrics:
- rename `privacy.tcf.(v1,v2).vendorlist.{VERSION}.(missing|ok|err)` to `privacy.tcf.(v1,v2).vendorlist.(missing|ok|err)` - no reason for granularity by each vendor list since we can check this info in logs.
- add new `privacy.tcf.missing` metric.

Revise TCF VendorList metrics

---

docs/config-app.md

adding generate-bid-id options

---

src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
src/main/java/org/prebid/server/bidder/rubicon/proto/RubiconUserExt.java
src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java

Rubicon Adapter should translate the "liveramp.com" *id* from the "user.ext.eids" array to "user.ext.liveramp_idl" as follows:
```
{
"user": {
"ext": {
"eids": [{
"source": 'liveramp.com',
"uids": [{
"id": "the-id"
}]
}]
}
}
}
```
 to XAPI:
```
{
"user": {
"ext": {
"liveramp_idl": "the-id"
}
}
}
```

Add Liveramp IDL to Rubicon user.ext

---

src/main/java/org/prebid/server/auction/FpdResolver.java
src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtImpContext.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtImpContextDataAdserver.java
src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java

The fix-PR is related to resolving `adslot` in Rubicon bidder.
FYI, the path is this:
- first (temporary) look for `imp[].ext.context.data.adslot`
- then if `imp[].ext.context.data.adserver.name="gam"` then look for `imp[].ext.context.data.adserver.adslot`
- finally look for `imp[].ext.context.data.pbadslot`

Move imp[].ext.context.adserver to  imp[].ext.context.data.adserver

---

src/main/java/org/prebid/server/bidder/consumable/ConsumableBidder.java
src/main/java/org/prebid/server/bidder/consumable/model/ConsumableDecision.java
src/test/java/org/prebid/server/bidder/consumable/ConsumableBidderTest.java

This PR corresponds to Prebid/prebid-server#1459.
Corrects the width and height specified in the bid response.
After this change, Prebid Server uses the width and height specified in the **bid response** from Consumable.
Previously, Prebid Server would reuse the width and height specified in the **bid request**. That older behaviour was ported from an older version of the prebid.js adapter but is no longer valid.
I am submitting this PR on behalf of Consumable, cc @naffis.

consumable: Correct width and height reported in response.

---

src/main/java/org/prebid/server/bidder/adhese/AdheseBidder.java
src/test/java/org/prebid/server/bidder/adhese/AdheseBidderTest.java
src/test/java/org/prebid/server/it/AdheseTest.java

Next to the referer and the consent string we also want to send the Device IFA (if present) to our Adhese endpoint - if present.

Optionally read IFA value and add it the the request url (Adhese)

---

.github/workflows/release-drafter.yml

This PR fixes `update_release_draft` GitHub actions job failed with error:
```
---
Run target_tag=${COMMIT_MSG#"Prebid Server prepare release "}
target_tag=${COMMIT_MSG#"Prebid Server prepare release "}
echo "::set-env name=TARGET_TAG::$target_tag"
shell: /bin/bash -e {0}
env:
COMMIT_MSG: Prebid Server prepare release 1.50.0
---
Error: Unable to process command '::set-env name=TARGET_TAG::1.50.0' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command
execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. 
```
For more information see: 
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Fix github actions release publishing with set env in new way

---

src/main/java/org/prebid/server/bidder/conversant/ConversantBidder.java
src/test/java/org/prebid/server/bidder/conversant/ConversantBidderTest.java

Fix Conversant bidder to change banner or video if present

---

src/main/java/org/prebid/server/auction/AuctionRequestFactory.java
src/main/java/org/prebid/server/auction/BidResponseCreator.java
src/test/java/org/prebid/server/auction/AuctionRequestFactoryTest.java
src/test/resources/org/prebid/server/it/openrtb2/video/test-video-appnexus-bid-request-1.json
src/test/resources/org/prebid/server/it/openrtb2/video/test-video-appnexus-bid-request-2.json

This PR fixes passing targeting fields to bidders as of #913

Fix passing ext.prebid.targeting.* fields

---

src/main/java/org/prebid/server/auction/AmpRequestFactory.java
src/test/java/org/prebid/server/auction/AmpRequestFactoryTest.java

Fix passing ext.prebid.targeting.* fields for AMP

---

docs/developers/stored-requests.md

minor change in example to follow same convention

follow same convention for stored request example like stored impression

---

src/main/java/org/prebid/server/auction/FpdResolver.java
src/test/java/org/prebid/server/auction/FpdResolverTest.java

This PR fixes passing of `user.ext.data`, `site.ext.data` and `app.ext.data` when creating individual bidder's requests.
Before we modified shared `ext.data` if there is no FPD `ext.data` object.
Now we return new copy of `ext.data` for each bidder.
Thanks @schernysh for solution.

Fix FPD user.ext.data passing to bidders

---

src/main/java/org/prebid/server/bidder/yieldlab/YieldlabBidder.java

If the same targeting parameter is set for multiple ad units the prebid server will crash with 500 as the merging fails.
Fix inspired by [this SO answer](https://stackoverflow.com/questions/32312876/ignore-duplicates-when-producing-map-using-streams)

Fix Duplicate key exception for yieldlab targeting

---

src/test/java/org/prebid/server/bidder/yieldlab/YieldlabBidderTest.java

Add regression tests for #1131

Add test for yieldlab targeting fix

---

src/main/java/org/prebid/server/auction/OrtbTypesResolver.java
src/main/java/org/prebid/server/json/JsonMerger.java
src/test/java/org/prebid/server/auction/OrtbTypesResolverTest.java

if we have two keys:
- `user.data.key = value1`
- `user.data.ext.key = value2`
then in result we should have user.data.ext.key = value1 (overriding ext.ATTR)

Fix (user,site,app).data to be merged to (user,site,app).ext.data

---

src/main/java/org/prebid/server/auction/FpdResolver.java
src/test/java/org/prebid/server/auction/FpdResolverTest.java

This PR fixes NPE:
```
2021-02-15 05:35:44.236 ERROR 7753 --- [vert.x-eventloop-thread-2] o.p.server.handler.openrtb2.AmpHandler   : Critical error while running the auction                                                       
java.lang.NullPointerException: null                                                                                                                                                                         
at java.util.AbstractCollection.addAll(Unknown Source)                                                                                                                                               
at org.prebid.server.auction.FpdResolver.mergeBidders(FpdResolver.java:303) …
```

Fix NPE in FPD when targeting.bidders is not defined

---

src/main/java/org/prebid/server/auction/BidResponseCreator.java
src/test/java/org/prebid/server/auction/BidResponseCreatorTest.java

This PR is temporal solution.
It will be replaced by new requirement https://github.com/prebid/prebid-server/issues/1676
which is already implemented in https://github.com/prebid/prebid-server-java/pull/1126

Pass bid.ext.skadn to PBS response instead of bid.ext.bidder.skadn

---

src/main/java/org/prebid/server/privacy/gdpr/tcfstrategies/purpose/typestrategies/FullEnforcePurposeStrategy.java
src/test/java/org/prebid/server/privacy/gdpr/tcfstrategies/purpose/typestrategies/FullEnforcePurposeStrategyTest.java

https://github.com/prebid/prebid-server/issues/1748

Updated TCF restriction processing

---

src/main/java/org/prebid/server/auction/requestfactory/AmpRequestFactory.java
src/main/java/org/prebid/server/auction/requestfactory/AuctionRequestFactory.java
src/main/java/org/prebid/server/auction/requestfactory/Ortb2RequestFactory.java
src/main/java/org/prebid/server/auction/requestfactory/VideoRequestFactory.java
src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
src/test/java/org/prebid/server/auction/requestfactory/AmpRequestFactoryTest.java
src/test/java/org/prebid/server/auction/requestfactory/AuctionRequestFactoryTest.java
src/test/java/org/prebid/server/auction/requestfactory/Ortb2RequestFactoryTest.java
src/test/java/org/prebid/server/auction/requestfactory/VideoRequestFactoryTest.java

For now, it is not the best code that I've written, but we still need to discuss AMP accountId processing, and this is the simplest solution.
Later we will extract accountId parsing into separate module and extend logic into Video and Amp, so we can remove boolean parameter.

Add lookup of account from stored requests

---

src/main/java/org/prebid/server/auction/requestfactory/Ortb2RequestFactory.java
src/test/java/org/prebid/server/auction/requestfactory/Ortb2RequestFactoryTest.java

Fix Ortb2RequestFactory to throw error if StoredRequestProcessor fails

---

src/main/java/org/prebid/server/bidder/smaato/SmaatoBidder.java
src/test/java/org/prebid/server/bidder/smaato/SmaatoBidderTest.java
src/test/resources/org/prebid/server/it/openrtb2/smaato/test-smaato-bid-request.json

`go` repo PR: https://github.com/prebid/prebid-server/pull/1767

Add App support for Smaato

---

src/main/java/org/prebid/server/bidder/tappx/TappxBidder.java
src/test/java/org/prebid/server/bidder/tappx/TappxBidderTest.java
src/test/java/org/prebid/server/it/TappxTest.java

`go` repo PR: https://github.com/prebid/prebid-server/pull/1777

Tappx changes - Backward compatible change of version

---

src/main/java/org/prebid/server/bidder/openx/OpenxBidder.java
src/test/java/org/prebid/server/bidder/openx/OpenxBidderTest.java

- Fixes bug that set bidfloor to null when customFloor not given (so almost always)
- Implements behavior in https://github.com/prebid/Prebid.js/blob/master/modules/openxBidAdapter.js#L495
- Ref https://github.com/prebid/prebid-server/issues/1787
- Same change as https://github.com/prebid/prebid-server/pull/1795 for PBS-Go

Openx: use bidfloor if set - prebid.js adapter behavior 

---

src/main/java/org/prebid/server/bidder/UsersyncInfoAssembler.java
src/main/java/org/prebid/server/bidder/UsersyncUtil.java
src/main/java/org/prebid/server/handler/CookieSyncHandler.java
src/main/java/org/prebid/server/handler/SetuidHandler.java
src/main/resources/bidder-config/smartyads.yaml
src/test/java/org/prebid/server/bidder/UsersyncUtilTest.java
src/test/java/org/prebid/server/handler/CookieSyncHandlerTest.java
src/test/java/org/prebid/server/it/ApplicationTest.java

Relates to https://github.com/prebid/prebid-server/issues/1554
```
/cookie_sync needs to tell /setuid which kind of response to make.
- For iframe syncs, it should add f=b into the /setuid URL.
- For image syncs, it should add f=i into the /setuid URL.
```

Usersync URL supports format parameter

---

src/main/java/org/prebid/server/bidder/openx/OpenxBidder.java
src/test/java/org/prebid/server/bidder/openx/OpenxBidderTest.java

https://github.com/prebid/prebid-server/pull/1795

Openx: use bidfloor if set - prebid.js adapter behavior

---

src/main/java/org/prebid/server/bidder/appnexus/AppnexusBidder.java
src/test/java/org/prebid/server/bidder/appnexus/AppnexusBidderTest.java

https://github.com/prebid/prebid-server/pull/1814

AppNexus: reform bid floor handling

---

src/main/java/org/prebid/server/auction/BidResponseCreator.java
src/main/java/org/prebid/server/auction/requestfactory/Ortb2RequestFactory.java
src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
src/test/java/org/prebid/server/auction/requestfactory/Ortb2RequestFactoryTest.java

Fixes #1256 
Probably we need to consider to refactor `PrivacyContext` with adding both `ipV4` and `ipV6`. 
Or we can modify `TcfContext` model by changing `ipAddress` of `org.prebid.server.auction.model.IpAddress` type.

Fix IPv6 processing according to privacy ip masking

---

src/main/java/org/prebid/server/analytics/AnalyticsReporter.java
src/main/java/org/prebid/server/analytics/AnalyticsReporterDelegator.java
src/main/java/org/prebid/server/analytics/LogAnalyticsReporter.java
src/main/java/org/prebid/server/metric/AnalyticsCodeMetrics.java
src/main/java/org/prebid/server/metric/AnalyticsReporterMetrics.java
src/main/java/org/prebid/server/metric/EventTypeMetrics.java
src/main/java/org/prebid/server/metric/MetricName.java
src/main/java/org/prebid/server/metric/Metrics.java
src/main/java/org/prebid/server/spring/config/AnalyticsConfiguration.java
src/test/java/org/prebid/server/analytics/AnalyticsReporterDelegatorTest.java
src/test/java/org/prebid/server/metric/MetricsTest.java

Implements https://github.com/prebid/prebid-server/issues/1731

Implement analytics by code metrics

---

src/main/java/org/prebid/server/hooks/execution/HookStageExecutor.java
src/main/java/org/prebid/server/hooks/execution/model/StageExecutionPlan.java
src/main/java/org/prebid/server/spring/config/HooksConfiguration.java
src/test/java/org/prebid/server/hooks/execution/HookStageExecutorTest.java
src/test/resources/org/prebid/server/it/test-application-hooks.properties

One is always executed, another could be overridden by account configuration.

Split host-level execution plan into two parts

---

src/main/java/org/prebid/server/analytics/AnalyticsReporterDelegator.java
src/main/java/org/prebid/server/bidder/beachfront/BeachfrontBidder.java
src/main/java/org/prebid/server/handler/CookieSyncHandler.java
src/main/java/org/prebid/server/handler/SetuidHandler.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtRequestPrebid.java
src/test/java/org/prebid/server/analytics/AnalyticsReporterDelegatorTest.java

Fixes wrong input request like:
```
at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: 
com.iab.openrtb.request.BidRequest["ext"]->
org.prebid.server.proto.openrtb.ext.request.ExtRequest["prebid"]->
org.prebid.server.proto.openrtb.ext.request.ExtRequestPrebid["analytics"]), 
[ntloop-thread-4] o.p.s.handler.openrtb2.AuctionHandler    : Invalid request format: Error decoding bidRequest: 
Cannot deserialize instance of `com.fasterxml.jackson.databind.node.ObjectNode` out of START_ARRAY token
```

Fix ext.prebid.analytics flag to be tolerant for invalid input

---

src/main/java/org/prebid/server/spring/config/WebConfiguration.java

Implements https://github.com/prebid/prebid-server/issues/1812

Turn on decompression support in Vert.x HTTP server (gzip and deflate as of Netty 4.1.31)

---

src/main/java/org/prebid/server/bidder/conversant/ConversantBidder.java
src/test/java/org/prebid/server/bidder/conversant/ConversantBidderTest.java

Ported from https://github.com/prebid/prebid-server/pull/1840/

Conversant: fix bid floor

---

src/main/java/org/prebid/server/bidder/ix/IxBidder.java
src/main/resources/bidder-config/ix.yaml
src/test/java/org/prebid/server/bidder/ix/IxBidderTest.java

https://github.com/prebid/prebid-server/pull/1799
https://github.com/prebid/prebid-server/pull/1794
https://github.com/prebid/prebid-server/pull/1837/

IX: Set bidVideo when category and duration is available

---

src/main/java/org/prebid/server/analytics/AnalyticsReporterDelegator.java
src/test/java/org/prebid/server/analytics/AnalyticsReporterDelegatorTest.java

Fixes NPE:
```
2021-06-08 02:59:02.352 ERROR 13870 --- [vert.x-eventloop-thread-2] io.vertx.core.impl.ContextImpl : Unhandled exception
java.lang.NullPointerException: null
at org.prebid.server.analytics.AnalyticsReporterDelegator.logUnknownAdapters(AnalyticsReporterDelegator.java:114)
at org.prebid.server.analytics.AnalyticsReporterDelegator.checkUnknownAdaptersForAuctionEvent(AnalyticsReporterDelegator.java:109)
at org.prebid.server.analytics.AnalyticsReporterDelegator.delegateEvent(AnalyticsReporterDelegator.java:87)
at org.prebid.server.analytics.AnalyticsReporterDelegator.lambda$processEvent$1(AnalyticsReporterDelegator.java:78)
at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:80)
```

Update AnalyticsReporterDelegator to tolerate with missing BidRequest

---

src/main/java/org/prebid/server/auction/requestfactory/AmpRequestFactory.java
src/main/java/org/prebid/server/auction/requestfactory/AuctionRequestFactory.java
src/main/java/org/prebid/server/auction/requestfactory/Ortb2RequestFactory.java
src/main/java/org/prebid/server/auction/requestfactory/VideoRequestFactory.java
src/test/java/org/prebid/server/auction/requestfactory/AmpRequestFactoryTest.java
src/test/java/org/prebid/server/auction/requestfactory/AuctionRequestFactoryTest.java
src/test/java/org/prebid/server/auction/requestfactory/Ortb2RequestFactoryTest.java
src/test/java/org/prebid/server/auction/requestfactory/VideoRequestFactoryTest.java

Fix account fetching from stored requests for auctions

---

src/main/java/org/prebid/server/auction/model/AuctionContext.java
src/test/java/org/prebid/server/analytics/pubstack/PubstackEventHandlerTest.java

Fixes error:
```
java.lang.IllegalArgumentException: No serializer found for class org.prebid.server.execution.Timeout and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: org.prebid.server.analytics.model.AuctionEvent["auction_context"]->org.prebid.server.auction.model.AuctionContext["timeout"])
at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:2969)
at org.prebid.server.analytics.pubstack.PubstackEventHandler.buffer(PubstackEventHandler.java:104)
at org.prebid.server.analytics.pubstack.PubstackEventHandler.handle(PubstackEventHandler.java:84)
at org.prebid.server.analytics.pubstack.PubstackAnalyticsReporter.processEvent(PubstackAnalyticsReporter.java:100)
at …
```

Fix AuctionContext model to be suitable for JSON encoding

---

src/main/resources/bidder-config/triplelift.yaml

The recent PR [here](https://github.com/prebid/prebid-server-java/pull/1418) was a change intended specifically for Magnite (which is complete and healthy). All other Prebid Server Java hosts must continue using id=20, at least until we can figure out how to more efficiently organize our PBS partners. In the meantime however, I would like this merged as soon as possible so that no other partner begins using this new id specific to Magnite's integration with us.
cc @bretg @rpanchyk 
Putting PR in draft for now in case anything needs to be discussed that I may not be considering.

Revert Triplelift Endpoint [open source id]

---

extra/bundle/pom.xml

`PBS-Bundle` submodule used Spring Boot 2.1.1 as a parent which has older jackson dependency.
Build logs (`mvn clean compile -f extra/pom.xml -X`):
```
[DEBUG] com.fasterxml.jackson.core:jackson-core:jar:2.9.7:compile (version managed from 2.10.0)
[DEBUG] com.fasterxml.jackson.core:jackson-databind:jar:2.9.7:compile (version managed from 2.10.0)
[DEBUG] com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile (version managed from 2.10.0)
[DEBUG] com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.7:compile (version managed from 2.10.0)
[DEBUG] com.fasterxml.jackson.module:jackson-module-afterburner:jar:2.9.7:compile (version managed from 2.10.0)
```
PBS requires newer version - `2.10.0`.
Built with old Jackson produces error:
```
2021-09-06 17:20:19.014 ERROR 28327 …
```

Fix Jackson dependency in bundle submodule

---

extra/bundle/pom.xml
pom.xml

Follow up #1459
Fix for:
```
2021-09-14 18:25:12.584 ERROR 4417 --- [ntloop-thread-1] o.p.s.handler.openrtb2.AuctionHandler    : 
Critical error while running the auction
java.lang.NoSuchMethodError: org.apache.http.client.utils.URIBuilder.getPathSegments()Ljava/util/List;
at org.prebid.server.bidder.tappx.TappxBidder.buildUrl(TappxBidder.java:115)
at org.prebid.server.bidder.tappx.TappxBidder.resolveUrl(TappxBidder.java:105)
at org.prebid.server.bidder.tappx.TappxBidder.makeHttpRequests(TappxBidder.java:60)
```

Fix httpclient dependency

---

extra/bundle/pom.xml

Rid off warning:
```
'build.plugins.plugin.version' for org.springframework.boot:spring-boot-maven-plugin is missing. 
@ line 75, column 21
It is highly recommended to fix these problems because they threaten the stability of your build.
For this reason, future Maven versions might no longer support building such malformed projects.
```

Add version to spring-boot-maven-plugin in bundle POM

---

src/test/java/org/prebid/server/hooks/execution/HookStageExecutorTest.java

Slow environment may fail on small time window check.

Increase execution time checking in HookStageExecutorTest

---

docs/config-app.md
src/main/java/org/prebid/server/proto/response/BidderInfo.java
src/main/java/org/prebid/server/spring/config/bidder/model/BidderConfigurationProperties.java
src/main/java/org/prebid/server/spring/config/bidder/model/DefaultBidderConfigurationProperties.java
src/main/java/org/prebid/server/spring/config/bidder/util/BidderInfoCreator.java
src/main/resources/application.yaml
src/test/java/org/prebid/server/auction/PrivacyEnforcementServiceTest.java
src/test/java/org/prebid/server/bidder/BidderCatalogTest.java
src/test/java/org/prebid/server/handler/CookieSyncHandlerTest.java
src/test/java/org/prebid/server/handler/info/BidderDetailsHandlerTest.java
src/test/java/org/prebid/server/validation/BidderParamValidatorTest.java

This property was used in TCF 1.1 which is already not supported by PBS.

Remove bidder pbs-enforces-gdpr property

---

src/main/java/org/prebid/server/auction/BidResponseCreator.java
src/main/java/org/prebid/server/auction/DebugResolver.java
src/main/java/org/prebid/server/auction/ExchangeService.java
src/main/java/org/prebid/server/auction/model/DebugContext.java
src/main/java/org/prebid/server/auction/requestfactory/VideoRequestFactory.java
src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
src/main/resources/bidder-config/appnexus.yaml
src/main/resources/bidder-config/ttx.yaml
src/test/java/org/prebid/server/auction/BidResponseCreatorTest.java
src/test/java/org/prebid/server/auction/DebugResolverTest.java
src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
src/test/java/org/prebid/server/auction/requestfactory/AmpRequestFactoryTest.java
src/test/java/org/prebid/server/auction/requestfactory/AuctionRequestFactoryTest.java
src/test/java/org/prebid/server/auction/requestfactory/VideoRequestFactoryTest.java
src/test/java/org/prebid/server/handler/openrtb2/AmpHandlerTest.java
src/test/resources/org/prebid/server/it/deals/simulation/test-auction-response-1.json
src/test/resources/org/prebid/server/it/deals/simulation/test-auction-response-2.json
src/test/resources/org/prebid/server/it/test-app-settings.yaml

Turn off debug by Publisher, by bidder - proposal

---

src/main/java/org/prebid/server/bidder/algorix/AlgorixBidder.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/algorix/ExtImpAlgorix.java
src/main/resources/bidder-config/algorix.yaml
src/main/resources/static/bidder-params/algorix.json
src/test/java/org/prebid/server/bidder/algorix/AlgorixBidderTest.java
src/test/resources/org/prebid/server/it/openrtb2/algorix/test-algorix-bid-request.json
src/test/resources/org/prebid/server/it/openrtb2/algorix/test-auction-algorix-request.json

Add Server Region Support:
* add region in ext.bidder: APAC for request to SG EP, USE for request to US EP, other for request to Global EP
The same with PBS-Go: https://github.com/prebid/prebid-server/pull/2096

Algorix: add Server Region Support

---

src/main/resources/bidder-config/amx.yaml

The AMX adapter config is set to have "vendor-id: 0" -- this updates the ID to 737, to match TCF/IAB Europe and "prebid-server" (https://github.com/prebid/prebid-server/blob/master/static/bidder-info/amx.yaml)

AMX Bid Adapter Config: Set AMX vendor ID to 737

---

src/main/java/org/prebid/server/deals/targeting/interpret/Intersects.java
src/main/java/org/prebid/server/deals/targeting/interpret/IntersectsStrings.java
src/test/java/org/prebid/server/deals/targeting/interpret/IntersectsIntegersTest.java
src/test/java/org/prebid/server/deals/targeting/interpret/IntersectsSizesTest.java
src/test/java/org/prebid/server/deals/targeting/interpret/IntersectsStringsTest.java

This PR fixes `NullPointerException`:
```
ERROR [ntloop-thread-4] o.p.s.handler.openrtb2.AuctionHandler : Critical error while running the auction
java.lang.NullPointerException: null
at org.prebid.server.deals.targeting.interpret.IntersectsStrings.toLowerCase(IntersectsStrings.java:23)
at org.prebid.server.deals.targeting.interpret.IntersectsStrings.lookupActualValues(IntersectsStrings.java:19)
at org.prebid.server.deals.targeting.interpret.Intersects.matches(Intersects.java:25)
at org.prebid.server.deals.targeting.interpret.And.matches(And.java:21)
at org.prebid.server.deals.TargetingService.matchesTargeting(TargetingService.java:70)
```
It was occurred when FPD is not defined in request:
```
"site": {
"publisher": {
"id": "ACCOUNT"
}
```
Until adding site FPD:
```
"site": { …
```

Fix PG intersects expression to avoid NPE

---

src/test/groovy/org/prebid/server/functional/model/mock/services/currencyconversion/CurrencyConversionRatesResponse.groovy
src/test/groovy/org/prebid/server/functional/pg/AlertSpec.groovy
src/test/groovy/org/prebid/server/functional/pg/CurrencySpec.groovy
src/test/groovy/org/prebid/server/functional/pg/PlansSpec.groovy
src/test/groovy/org/prebid/server/functional/pg/RegisterSpec.groovy
src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/CurrencyConversion.groovy

Add tests for PG alert, currency, plans, register services
Not only those PG tests, but all (also from other PRs) have passed
[WARNING] Tests run: 246, Failures: 0, Errors: 0, Skipped: 10
[INFO] prebid-server ...................................... SUCCESS [06:02 min]

Add PG tests for alert, currency, plans, register services

---

src/test/groovy/org/prebid/server/functional/pg/PgAuctionSpec.groovy
src/test/groovy/org/prebid/server/functional/pg/TokenSpec.groovy

Add tests for PG auction, tokens
Not only those PG tests, but all (also from other PRs) have passed
[WARNING] Tests run: 246, Failures: 0, Errors: 0, Skipped: 10
[INFO] prebid-server ...................................... SUCCESS [06:02 min]

Add PG tests to cover auction and tokens

---

src/test/groovy/org/prebid/server/functional/pg/PgBidResponseSpec.groovy
src/test/groovy/org/prebid/server/functional/pg/PgBidderRequestSpec.groovy
src/test/groovy/org/prebid/server/functional/pg/UserDetailsSpec.groovy

Add tests for PG bid response, bidder request, user details
Not only those PG tests, but all (also from other PRs) have passed
[WARNING] Tests run: 246, Failures: 0, Errors: 0, Skipped: 10
[INFO] prebid-server ...................................... SUCCESS [06:02 min]

Add PG bidder request, bid response, user details specs

---

src/test/groovy/org/prebid/server/functional/model/ChannelType.groovy
src/test/groovy/org/prebid/server/functional/model/config/AccountCcpaConfig.groovy
src/test/groovy/org/prebid/server/functional/model/config/AccountGdprConfig.groovy
src/test/groovy/org/prebid/server/functional/model/request/amp/AmpRequest.groovy
src/test/groovy/org/prebid/server/functional/model/request/auction/App.groovy
src/test/groovy/org/prebid/server/functional/model/request/auction/BidRequest.groovy
src/test/groovy/org/prebid/server/functional/model/request/auction/Channel.groovy
src/test/groovy/org/prebid/server/functional/model/request/auction/DistributionChannel.groovy
src/test/groovy/org/prebid/server/functional/model/request/auction/UserExt.groovy
src/test/groovy/org/prebid/server/functional/testcontainers/PbsServiceFactory.groovy
src/test/groovy/org/prebid/server/functional/testcontainers/container/PrebidServerContainer.groovy
src/test/groovy/org/prebid/server/functional/tests/BaseSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/pg/TargetingSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/CcpaAmpSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/CcpaAuctionSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/CoppaSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAmpSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/PrivacyBaseSpec.groovy
src/test/groovy/org/prebid/server/functional/util/privacy/TcfConsent.groovy

Rename integration to channel in account config tests

---

src/main/java/org/prebid/server/bidder/telaria/TelariaBidder.java
src/test/java/org/prebid/server/bidder/telaria/TelariaBidderTest.java

https://github.com/prebid/prebid-server/pull/2171

Telaria: add pod support

---

src/main/java/org/prebid/server/bidder/adyoulike/AdyoulikeBidder.java
src/main/java/org/prebid/server/spring/config/bidder/AdyoulikeConfiguration.java
src/main/java/org/prebid/server/util/BidderUtil.java
src/test/java/org/prebid/server/bidder/adyoulike/AdyoulikeBidderTest.java
src/test/resources/org/prebid/server/it/openrtb2/adyoulike/test-auction-adyoulike-response.json

https://github.com/prebid/prebid-server/pull/2194

Adyoulike: add currency conversion

---

src/test/groovy/org/prebid/server/functional/tests/pg/ReportSpec.groovy

Add test to cover PBS doesn't resend a report when del stats responses with 409

Tests: Resend a report when del stats respond with 409

---

.github/workflows/pr-functional-tests.yml
.github/workflows/pr-java-ci.yml

Adding Temurin as a Java distribution as this is now a mandatory field. Temurin is an old AdoptOpenJDK and is a part of the Eclipse foundation.

Workflow: Add Java distribution name to the workflow

---

src/test/groovy/org/prebid/server/functional/tests/pg/AlertSpec.groovy
src/test/groovy/org/prebid/server/functional/util/PBSUtils.groovy

Test failure in 'AlertSpec.PBS should send alert request when the threshold is reached' is not reproduced on a local machine. Testing it here to find out the reason and fix it.
EDIT: it looks like that is some bug with Awaitility when it doesn't execute Groovy closures, decided to replace awaitility waiter with a plain while loop and sleep().

Fix failing PG alert spec test

---

src/test/resources/org/prebid/server/functional/db_schema.sql

Fix for:
> java.sql.SQLException: An attempt by a client to checkout a Connection has timed out
when PBS containers for functional tests execution are failing to start which occurs when executing functional tests on slow devices.
The default MySQL wait timeout is 28s and is increased to 60s in that PR.

Fix JDBC connection timeout error

---

src/main/resources/bidder-config/connectad.yaml

Found that connect ad's sync is an iframe, not a redirect.

Connectad: change usersync type

---

src/main/resources/bidder-config/richaudience.yaml
src/main/resources/bidder-config/smartrtb.yaml

It was pointed out to us that we were missing an equal sign in the /setuid call

Bidders: Fix missing equals in sync `redirect-url`

---

src/test/groovy/org/prebid/server/functional/testcontainers/container/PrebidServerContainer.groovy
src/test/groovy/org/prebid/server/functional/tests/pg/AlertSpec.groovy

In this PR trying to resolve the next exceptions
- org.testcontainers.containers.ContainerLaunchException: Container startup failed
- AlertSpec.PBS should send alert request when the threshold is reached Multiple Failures (4 failures)
org.spockframework.runtime.ConditionFailedWithExceptionError: Condition failed with Exception:
PBSUtils.waitUntil { alert.requestCount == initialRequestCount + 2 }

Fix integration flaky tests

---

src/main/resources/bidder-config/mobilefuse.yaml

We will want gzip for Go as well. Thanks!

Enable endpoint-compression for mobilefuse adapter

---

src/main/resources/bidder-config/onetag.yaml

We would like to add the same compression config in PBS-Go.

OneTag: enable endpoint-compression

---

Dockerfile

Unfortunately official OpenJDK image is now deprecated as per https://hub.docker.com/_/openjdk

Dependencies: Update base docker jdk image

---

src/main/java/org/prebid/server/bidder/ix/IxBidder.java
src/test/java/org/prebid/server/bidder/ix/IxBidderTest.java

This is a port of https://github.com/prebid/prebid-server/pull/2315

IX: Add multi-format ad unit support

---

src/main/resources/static/bidder-params/visx.json
src/test/java/org/prebid/server/validation/BidderParamValidatorTest.java

Updating UID to support both integer and string.
- Updated schema to support string and integer types
- Added regex to schema for UID format validation
- Added schema validation tests for VISX

Add string support to UID

---

src/main/java/org/prebid/server/auction/OrtbTypesResolver.java

Fixed `ClassCastException` while reading `TextNode` fields in `OrtbTypesResolver`.

Fix `ССE` in `OrtbTypesResolver`

---

src/test/groovy/org/prebid/server/functional/tests/privacy/GppAuctionSpec.groovy

Error message: 
`PBS should emit warning when gppSid contains 2, gpp is TCF2-EU and regs.gpp and user.consent are different`  
Time elapsed: 0.501 s  <<< ERROR! java.lang.IllegalStateException: Expecting exactly 1 bidder call. Got 0

Test: Fix `GGP` flaky functional tests

---

src/test/groovy/org/prebid/server/functional/testcontainers/Dependencies.groovy
src/test/groovy/org/prebid/server/functional/testcontainers/PbsServiceFactory.groovy
src/test/groovy/org/prebid/server/functional/testcontainers/container/NetworkServiceContainer.groovy
src/test/groovy/org/prebid/server/functional/testcontainers/container/PrebidServerContainer.groovy
src/test/groovy/org/prebid/server/functional/tests/AuctionSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/BaseSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/BidValidationSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/CacheSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/MetricsSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/pg/ReportSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAmpSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/PrivacyBaseSpec.groovy
src/test/resources/org/prebid/server/functional/mysql_config_override.cnf

This PR fixes the issue of connections being exhausted during test runs. There is actually 2 issues which this PR tries to solve:
- mySQL container being out of connections due to not closing them after PBS shuts down, which leads to a quite fast exhaustion during runs with high container count;
- MockServer dying mid-run most probably due to bloating with logs

Tests: fix connection exhaustion issue

---

src/main/java/org/prebid/server/spring/config/VertxConfiguration.java
src/main/java/org/prebid/server/spring/config/metrics/MetricsConfiguration.java
src/main/resources/metrics-config/metrics.yaml

Removed 'metricRegistry' presence check, forced usage of JVM-related metrics set, enabled JMX for Vertx metrics config.

Core: Telemetry jmx support

---

pom.xml

Please refer https://github.com/grpc/grpc-java/issues/7690 for context.

Workaround for absent Apple ARM proto compiler

---

src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAmpSpec.groovy

> **Error**:  Failures: 
**Error**:    GdprAmpSpec.PBS amp with proper consent.tcfPolicyVersion parameter should process request and cache correct vendorList file:329 Condition not satisfied:

Test: Fix gdpr flaky test

---

src/main/java/org/prebid/server/bidder/orbidder/OrbidderBidder.java
src/main/resources/bidder-config/orbidder.yaml
src/test/resources/org/prebid/server/it/openrtb2/orbidder/test-auction-orbidder-response.json
src/test/resources/org/prebid/server/it/openrtb2/orbidder/test-orbidder-bid-response.json

This PR implements / fixes the "Port PR from PBS-Go: ORBIDDER: enable capability site with media type banner and native" Issue (https://github.com/prebid/prebid-server-java/issues/2515).
We (my team and myself) as developer normally only adjust our GoLang adapter code, but we need as soon as possible the Java Version updated as well. Hopefully it is fine that i did this PR.
Have a nice day
Arne

ORBIDDER: BidType detection, web-sites new types

---

src/main/java/org/prebid/server/bidder/ix/IxBidder.java
src/main/java/org/prebid/server/bidder/ix/model/request/IxDiag.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/ix/ExtImpIx.java
src/main/java/org/prebid/server/spring/config/bidder/IxConfiguration.java
src/main/resources/static/bidder-params/ix.json
src/test/java/org/prebid/server/bidder/ix/IxBidderTest.java
src/test/java/org/prebid/server/it/IxTest.java
src/test/resources/org/prebid/server/it/openrtb2/ix/test-ix-bid-request.json

Updates from https://github.com/prebid/prebid-server-java/issues/2484

Ix: Bidder updates

---

src/main/resources/static/bidder-params/rise.json

#2599 changed the name of the mandatory field for Rise, but JSON schema still requires old `publisher_id` field.

Rise: Fix JSON schema (publisher_id not required)

---

src/main/java/org/prebid/server/bidder/rtbhouse/RtbhouseBidder.java
src/main/resources/bidder-config/rtbhouse.yaml
src/test/java/org/prebid/server/bidder/rtbhouse/RtbhouseBidderTest.java

[x] Feature
Native ads are now available to be processed and accessed by RTB House adapter.
Please reach us at [inventory_support@rtbhouse.com](mailto:inventory_support@rtbhouse.com) with [piotr.jaworski@rtbhouse.com](mailto:piotr.jaworski@rtbhouse.com) and cc [leandro.otani@rtbhouse.com](mailto:leandro.otani@rtbhouse.com).

RTBHouse: native ads support

---

src/main/java/org/prebid/server/spring/config/bidder/util/BidderDepsAssembler.java
src/main/resources/bidder-config/yahooAds.yaml

In order to create alias without specific config (e.g. config is the same as for origin), just use such syntax:
```
adapters:
adapterName:
...
...
aliases:
aliasName: ~
```

Fixed NPE for bidder aliases empty config (syntax example added)

---

src/main/resources/bidder-config/smaato.yaml

Related to: [Port PR from PBS-Go: Smaato: Update userSync url to add GDPR macros](https://github.com/prebid/prebid-server-java/issues/2582)

Smaato: update user sync URL to add GDPR macros

---

src/main/java/org/prebid/server/auction/BidResponseCreator.java
src/main/java/org/prebid/server/validation/RequestValidator.java
src/test/groovy/org/prebid/server/functional/model/request/auction/Targeting.groovy
src/test/groovy/org/prebid/server/functional/tests/TargetingSpec.groovy
src/test/java/org/prebid/server/auction/BidResponseCreatorTest.java
src/test/java/org/prebid/server/validation/RequestValidatorTest.java

Simplified targeting validation, added additional check before targeting keywords resolving.
Related to: https://github.com/prebid/prebid-server/issues/2030

Optional "bidresponse.ext.prebid.targeting" response block

---

src/main/resources/bidder-config/rubicon.yaml

The Magnite exchange can receive gzip compressed requests

Rubicon adapter: adding gzip support

---

src/main/resources/bidder-config/rise.yaml

Spoke with Erez @ Rise who expressed a willingness to change their adapter config to allow modifying VAST.
Heads up @misha93m who authored the PBS-Go version of this file.

Rise adapter allowing modified VAST

---

src/main/java/org/prebid/server/cookie/UidsCookieService.java
src/main/java/org/prebid/server/cookie/proto/Uids.java
src/test/java/org/prebid/server/cookie/UidsCookieServiceTest.java
src/test/java/org/prebid/server/it/ApplicationTest.java
src/test/java/org/prebid/server/it/DealsTest.java
src/test/java/org/prebid/server/it/PrematureReturnTest.java

https://github.com/prebid/prebid-server-java/issues/2375
Port from [PBS-Go project](https://github.com/prebid/prebid-server/pull/2768): Remove Legacy UIDs From Cookie

Remove Legacy UIDs From Cookie

---

src/test/groovy/org/prebid/server/functional/tests/MultibidSpec.groovy

This PR aim to resolve this one flaky test
```
Error:  Tests run: 10, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.455 s <<< FAILURE! - in MultibidSpec
Error:  PBS should prefer bidRequest over account level config [requestTargeting: org.prebid.server.functional.model.request.auction.Targeting{includeWinners:true, includeBidderKeys:false, preferDeals:true, alwaysIncludeDeals:false, includeFormat:false}, accountTargeting: org.prebid.server.functional.model.request.auction.Targeting{includeWinners:true, includeBidderKeys:false, preferDeals:true, alwaysIncludeDeals:false, includeFormat:false}, #2]  Time elapsed: 0.67 s  <<< FAILURE!
org.spockframework.runtime.ConditionNotSatisfiedError: 
Condition not satisfied:
bidderRequest.ext.prebid.targeting != accountTargeting
|             | …
```

Tests: Add fix for `multibidspec` flaky tests

---

src/main/resources/bidder-config/yahooAds.yaml

This pull request updates the maintainer email address to [prebid-tech-team@yahooinc.com](mailto:prebid-tech-team@yahooinc.com).
Details:
Maintainer Email Address: [prebid-tech-team@yahooinc.com](mailto:prebid-tech-team@yahooinc.com)

YahooAds: Update maintainer email address

---

.github/workflows/docker-image-publish.yml
README.md

Docker images build and publish for bare and bundled PBJ versions.
Action is triggered by new tag that usually corresponds to the new release.

GitHub action: Docker image build and publish

---

.github/workflows/release-asset-publish.yml
README.md

GitHub action, that triggered by new release tag. Composes two ready-to-go .jar files (with and without PBS modules) and attaches them to release as assets for download.

GitHub action: release assets build and publish

---

src/main/java/org/prebid/server/bidder/nextmillennium/NextMillenniumBidder.java
src/main/java/org/prebid/server/spring/config/bidder/NextMillenniumConfiguration.java
src/main/resources/bidder-config/nextmillennium.yaml
src/test/java/org/prebid/server/bidder/nextmillennium/NextMillenniumBidderTest.java
src/test/resources/org/prebid/server/it/openrtb2/nextmillennium/test-nextmillennium-bid-request.json
src/test/resources/org/prebid/server/it/test-application.properties

As well update yaml file corresponding to this [PR](https://github.com/prebid/prebid-server/pull/2583)

NextMillennium: Add `extraInfo` support and update `yaml`

---

src/main/java/org/prebid/server/bidder/aidem/AidemBidder.java
src/main/resources/bidder-config/aidem.yaml
src/test/java/org/prebid/server/bidder/aidem/AidemBidderTest.java

Changes from https://github.com/prebid/prebid-server/pull/3403

Aidem: Url resolution updates

---

extra/modules/confiant-ad-quality/src/main/java/org/prebid/server/hooks/modules/com/confiant/adquality/core/RedisParser.java
extra/modules/confiant-ad-quality/src/main/java/org/prebid/server/hooks/modules/com/confiant/adquality/v1/ConfiantAdQualityBidResponsesScanHook.java
extra/modules/confiant-ad-quality/src/test/java/org/prebid/server/hooks/modules/com/confiant/adquality/util/AdQualityModuleTestUtils.java
extra/modules/confiant-ad-quality/src/test/java/org/prebid/server/hooks/modules/com/confiant/adquality/v1/ConfiantAdQualityBidResponsesScanHookTest.java

Currently Hook for Auctions receives information from all bidders. Some of them can contain empty bids.
Confiant module should not scan them because it has a wrong data format and makes no sense actually.
@AntoxaAntoxic would appreciate for a review. Not 100% sure about your flow how I can ping any required reviewer.
fyi @bretg

Confiant AdQuality: Skip scanning for bidders with empty bids

---

docs/metrics.md

The "`/cookie_sync` endpoint metrics`" section of the [Metrics documentation](https://github.com/prebid/prebid-server-java/blob/master/docs/metrics.md#cookie_sync-endpoint-metrics) seems to be out of date.
It lists `cookie_sync.<bidder-name>.gen` and `cookie_sync.<bidder-name>.matches` as available metrics, but neither seems to be available anymore, and it looks like they were removed:
- https://github.com/prebid/prebid-server-java/issues/2114
- https://github.com/prebid/prebid-server-java/pull/2065
- In particular, https://github.com/prebid/prebid-server-java/pull/2065/files#diff-fcd88b249295823c1877f78f5e06d5c8119384d522032b15eecca80b7bb24d55L80-L81
Issue: https://github.com/prebid/prebid-server-java/issues/3017

Remove documentation references to metrics that are no longer available

---

src/main/resources/bidder-config/yieldlab.yaml

The trailing slash needs to be removed because we end up with [two consecutive slashes in the final URL](https://github.com/prebid/prebid-server-java/blob/master/src/main/java/org/prebid/server/bidder/yieldlab/YieldlabBidder.java#L139) otherwise. This could easily lead to issues.

Yieldlab: Fix the default endpoint

---

src/main/java/org/prebid/server/bidder/bizzclick/BizzclickBidder.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/bizzclick/ExtImpBizzclick.java
src/main/resources/bidder-config/bizzclick.yaml
src/test/java/org/prebid/server/bidder/bizzclick/BizzclickBidderTest.java
src/test/java/org/prebid/server/it/BizzclickTest.java
src/test/resources/org/prebid/server/it/openrtb2/bizzclick/test-auction-bizzclick-request.json
src/test/resources/org/prebid/server/it/test-application.properties

Bizzclick: host parameter update

---

src/main/java/org/prebid/server/bidder/yieldlab/YieldlabBidder.java
src/main/java/org/prebid/server/bidder/yieldlab/model/YieldlabDigitalServicesActResponse.java
src/main/java/org/prebid/server/bidder/yieldlab/model/YieldlabResponse.java
src/test/java/org/prebid/server/bidder/yieldlab/YieldlabBidderTest.java

This ports this [Go PR](https://github.com/prebid/prebid-server/pull/3473)
A review and approval from a member of the Yieldlab team are required. (@brushmate, @rey1128, @nkloeber)

Yieldlab: Add Digital Service Act (DSA) support

---

src/main/java/org/prebid/server/currency/CurrencyConversionService.java
src/test/groovy/org/prebid/server/functional/model/Currency.groovy
src/test/groovy/org/prebid/server/functional/tests/CurrencySpec.groovy
src/test/java/org/prebid/server/auction/CurrencyConversionServiceTest.java

https://github.com/prebid/prebid-server/issues/3566
This PR also changes how currency precision works by making sure that PBS doesn't discard end up with a rate with less than 3 decimal places.

Feature: Cross-currency conversion capability

---

extra/bundle/pom.xml
extra/modules/confiant-ad-quality/pom.xml
extra/modules/pom.xml
extra/pom.xml
pom.xml
src/test/groovy/org/prebid/server/functional/testcontainers/container/NetworkServiceContainer.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitUfpdActivitiesSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/prometheus/PrometheusSpec.groovy
src/test/java/org/prebid/server/bidder/adtelligent/AdtelligentBidderTest.java

This PR introduces the beginning of a new approach for managing dependencies. To ensure that all common dependencies will remain of the identical versions across all modules, dependency versions will be now declared using the Dependency Management section in the topmost parent pom.xml.
Modules retain the right to add new dependencies if those dependencies are not creating conflicts. If the dependency is already present in the project, modules should declare their dependency without version tag so that version is synchronized with the project.

Core: Reorganize Maven dependencies

---

src/main/resources/application.yaml

Got advice from legal about adding Switzerland to the TCF-EU behavior list.

application.yaml: add switzerland to the default eea-countries

---

src/main/java/org/prebid/server/bidder/rtbhouse/RtbhouseBidder.java
src/main/resources/bidder-config/rtbhouse.yaml
src/test/java/org/prebid/server/bidder/rtbhouse/RtbhouseBidderTest.java

[x] Feature
Video ads are now available to be processed and accessed by RTB House adapter.
Please reach us at [inventory_support@rtbhouse.com](mailto:inventory_support@rtbhouse.com) with [piotr.jaworski@rtbhouse.com](mailto:piotr.jaworski@rtbhouse.com) and cc [leandro.otani@rtbhouse.com](mailto:leandro.otani@rtbhouse.com).

RTB House: video ads support

---

src/main/java/org/prebid/server/bidder/yieldmo/YieldmoBidder.java
src/main/java/org/prebid/server/spring/config/bidder/YieldmoConfiguration.java
src/test/java/org/prebid/server/bidder/yieldmo/YieldmoBidderTest.java

This branch adds currency conversion for bid floors to the yieldmo adapter. I wasn't able to find any documentation around this feature, so this is largely based off of the implementations found in other adapters.

Yieldmo Adapter: add currency conversion for bid floors

---

docs/config-app.md
src/main/java/org/prebid/server/spring/config/metrics/MetricsConfiguration.java

- [ x ] new feature
This PR activates Logback reporters for metrics. 
PBS-Java currently supports Influx, Graphite, Prometheus, and Console for metrics (see https://docs.prebid.org/prebid-server/hosting/pbs-hosting.html). This PR extends that list by adding support for Logback so that metrics can be configured with the same patterns and configuration files used for configuring runtime logs.
These Logback capabilities already exist in PBS-Java, they just aren't enabled. No new dependencies or business logic have been added.
- [ x ] Are your changes following [our code style guidelines](https://github.com/prebid/prebid-server-java/blob/master/docs/developers/code-style.md)?
- [ n/a ] Are there any breaking changes in your code?
- [ n/a ] Does your test coverage exceed 90%?
- [ n/a ] Are …

Add Logback support for metrics

---

src/main/resources/bidder-config/cpmstar.yaml

- Updated vendor-id for TCF/GVL in bidder-config
- CPMStar now is on the GVL
- Tested on production already 
- Config changes only, no code changes
- Config changes only, no code changes

CPMStar: Updated vendor-id for TCF/GVL

---

src/main/java/org/prebid/server/bidder/readpeak/ReadPeakBidder.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/readpeak/ExtImpReadPeak.java
src/main/java/org/prebid/server/spring/config/bidder/ReadPeakConfiguration.java
src/main/resources/bidder-config/readpeak.yaml
src/main/resources/static/bidder-params/readpeak.json
src/test/java/org/prebid/server/bidder/readpeak/ReadPeakBidderTest.java
src/test/java/org/prebid/server/it/ReadPeakTest.java
src/test/resources/org/prebid/server/it/openrtb2/readpeak/test-auction-readpeak-request.json
src/test/resources/org/prebid/server/it/openrtb2/readpeak/test-auction-readpeak-response.json
src/test/resources/org/prebid/server/it/openrtb2/readpeak/test-readpeak-bid-request.json
src/test/resources/org/prebid/server/it/openrtb2/readpeak/test-readpeak-bid-response.json
src/test/resources/org/prebid/server/it/test-application.properties

https://github.com/prebid/prebid-server-java/issues/3142

New adapter readpeak (#3142)

---

src/main/java/org/prebid/server/bidder/ix/IxBidder.java
src/test/java/org/prebid/server/bidder/ix/IxBidderTest.java

Ix: Update bidder

---

src/main/java/org/prebid/server/analytics/reporter/greenbids/GreenbidsAnalyticsReporter.java
src/main/java/org/prebid/server/analytics/reporter/greenbids/model/CommonMessage.java
src/main/java/org/prebid/server/analytics/reporter/greenbids/model/GreenbidsAdUnit.java
src/main/java/org/prebid/server/analytics/reporter/greenbids/model/GreenbidsAnalyticsProperties.java
src/main/java/org/prebid/server/analytics/reporter/greenbids/model/GreenbidsBid.java
src/main/java/org/prebid/server/analytics/reporter/greenbids/model/GreenbidsBids.java
src/main/java/org/prebid/server/spring/config/AnalyticsConfiguration.java
src/test/java/org/prebid/server/analytics/reporter/greenbids/GreenbidsAnalyticsReporterTest.java

We want to add the following info into analytics payload
- CPM from Bid, currency from BidResponse for each bidder
- bidder specific params from the BidRequest extension imp[].ext.prebid.bidder
- also we want to add to the HTTP header
- the custom flag header into HTTP POST call to distinguish between PBJS and PBS traffic on Greenbids Analytics Server side
- UserAgent header
Have added `givenPrebidNode` with the bidder params and `UserAgent` string into `BidRequest.Device` into `GreenbidsAnalyticsReporterTest` so we can test the new payload.

Add CPM, bidder params, UserAgent, PBS flag in GreenbidsAnalyticsReporter

---

src/main/java/org/prebid/server/bidder/adelement/AdelementBidder.java
src/main/java/org/prebid/server/bidder/bigoad/BigoadBidder.java
src/main/java/org/prebid/server/bidder/concert/ConcertBidder.java
src/main/java/org/prebid/server/bidder/consumable/ConsumableBidder.java
src/main/java/org/prebid/server/bidder/improvedigital/ImprovedigitalBidder.java
src/main/java/org/prebid/server/bidder/ix/IxBidder.java
src/main/java/org/prebid/server/bidder/mediago/MediaGoBidder.java
src/main/java/org/prebid/server/bidder/orbidder/OrbidderBidder.java
src/main/java/org/prebid/server/bidder/smrtconnect/SmrtconnectBidder.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/bigoad/ExtImpBigoad.java
src/main/java/org/prebid/server/spring/config/bidder/BigoadConfiguration.java
src/main/resources/bidder-config/bigoad.yaml
src/main/resources/static/bidder-params/bigoad.json
src/test/java/org/prebid/server/bidder/bigoad/BigoadBidderTest.java
src/test/java/org/prebid/server/it/BigoadTest.java
src/test/resources/org/prebid/server/it/openrtb2/bigoad/test-auction-bigoad-request.json
src/test/resources/org/prebid/server/it/openrtb2/bigoad/test-auction-bigoad-response.json
src/test/resources/org/prebid/server/it/openrtb2/bigoad/test-bigoad-bid-request.json
src/test/resources/org/prebid/server/it/openrtb2/bigoad/test-bigoad-bid-response.json
src/test/resources/org/prebid/server/it/test-application.properties

Bigoad: Add bidder

---

src/main/java/org/prebid/server/privacy/gdpr/TcfDefinerService.java
src/main/java/org/prebid/server/privacy/gdpr/vendorlist/VersionedVendorListService.java
src/test/groovy/org/prebid/server/functional/model/mock/services/vendorlist/GvlSpecificationVersion.groovy
src/test/groovy/org/prebid/server/functional/model/mock/services/vendorlist/VendorListResponse.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAmpSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
src/test/groovy/org/prebid/server/functional/util/privacy/TcfConsent.groovy
src/test/java/org/prebid/server/privacy/gdpr/TcfDefinerServiceTest.java
src/test/java/org/prebid/server/privacy/gdpr/vendorlist/VersionedVendorListServiceTest.java

Add support for TCF Policy Version 5.

---

extra/bundle/pom.xml
extra/modules/confiant-ad-quality/pom.xml
extra/modules/fiftyone-devicedetection/pom.xml
extra/modules/ortb2-blocking/pom.xml
extra/modules/pb-richmedia-filter/pom.xml
extra/modules/pom.xml
extra/pom.xml
pom.xml

Move JaCoCo to parent pom.xml so that code coverage data is generated for modules too.
JaCoCo coverage reports were not generated, and only base PBS coverage data was collected. This PR fixes that.
No impact on production code, so no need for testing.

Housekeeping: JaCoCo config cleanup

---

src/main/java/org/prebid/server/auction/requestfactory/Ortb2ImplicitParametersResolver.java
src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
src/test/groovy/org/prebid/server/functional/model/bidder/Generic.groovy
src/test/groovy/org/prebid/server/functional/model/bidderspecific/BidderImp.groovy
src/test/groovy/org/prebid/server/functional/model/request/auction/AnyUnsupportedBidder.groovy
src/test/groovy/org/prebid/server/functional/model/request/auction/Foo.groovy
src/test/groovy/org/prebid/server/functional/model/request/auction/ImpExt.groovy
src/test/groovy/org/prebid/server/functional/model/request/auction/ImpExtContext.groovy
src/test/groovy/org/prebid/server/functional/model/request/auction/ImpExtContextData.groovy
src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
src/test/java/org/prebid/server/auction/requestfactory/Ortb2ImplicitParametersResolverTest.java

Redefine logic regarding `imp.ext.<bidder>`

---

src/main/java/org/prebid/server/bidder/gumgum/GumgumBidder.java
src/test/java/org/prebid/server/bidder/gumgum/GumgumBidderTest.java

What's the context for the changes? 
Currently, Prebid Server conducts validations for certain video parameters before passing inventory requests to the GG ad server. This preliminary validation prevents the GG ad server from receiving complete inventory data, limiting our ability to apply comprehensive validations and record inventory details.
Since this is about removing validations should bot present any risk

Gumgum remove video validations

---

src/main/java/org/prebid/server/bidder/openx/OpenxBidder.java
src/test/java/org/prebid/server/bidder/openx/OpenxBidderTest.java

Populate BidderBid.videoInfo object for generation of `hb_pb_cat_dur` targeting
Closes #3353 for 
PBS-Go counterpart PR: https://github.com/prebid/prebid-server/pull/3834

OpenX: populate BidderBid.videoInfo for targeting

---

src/test/java/org/prebid/server/it/PriceFloorsTest.java

Price Floors Test Fix

---

src/main/java/org/prebid/server/auction/mediatypeprocessor/MultiFormatMediaTypeProcessor.java
src/test/groovy/org/prebid/server/functional/model/request/auction/BidderControls.groovy
src/test/groovy/org/prebid/server/functional/tests/FilterMultiFormatSpec.groovy
src/test/java/org/prebid/server/auction/mediatypeprocessor/MultiFormatMediaTypeProcessorTest.java

Case Insensitive Check for Bidder Controls

---

src/main/java/org/prebid/server/auction/ImpAdjuster.java
src/test/groovy/org/prebid/server/functional/tests/ImpRequestSpec.groovy
src/test/java/org/prebid/server/auction/ImpAdjusterTest.java

Remove all imp.ext.prebid.imp

---

.github/workflows/docker-image-publish.yml

We have a disabled github actions workflow to build and publish docker image of prebid server to github container registry. This workflow is disabled because its broken. This pr will fix it.

Github actions: fix github container registry workflow

---

extra/pom.xml

- [ x ] tech debt (test coverage, refactorings, etc.)
upgrade to latest version of Wiremock
bumping to latest dependency
CI build passes.

wiremock 3.9.1

---

src/main/java/org/prebid/server/auction/ExchangeService.java
src/test/groovy/org/prebid/server/functional/tests/ImpRequestSpec.groovy
src/test/java/org/prebid/server/auction/ExchangeServiceTest.java

Fix merging imp.ext.prebid.imp into imp

---

src/main/java/org/prebid/server/bidder/taboola/TaboolaBidder.java
src/test/java/org/prebid/server/bidder/taboola/TaboolaBidderTest.java

Taboola Bidder: App Support

---

src/main/java/org/prebid/server/bidder/adtarget/AdtargetBidder.java
src/main/java/org/prebid/server/bidder/adtarget/proto/AdtargetImpExt.java
src/main/java/org/prebid/server/bidder/adtarget/proto/ExtImpAdtargetBidRequest.java
src/main/java/org/prebid/server/bidder/adtelligent/AdtelligentBidder.java
src/main/java/org/prebid/server/bidder/adtelligent/proto/AdtelligentImpExt.java
src/main/java/org/prebid/server/bidder/adtelligent/proto/ExtImpAdtelligentBidRequest.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/adtarget/ExtImpAdtarget.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/adtelligent/ExtImpAdtelligent.java
src/main/resources/static/bidder-params/adtelligent.json
src/test/java/org/prebid/server/bidder/adtarget/AdtargetBidderTest.java
src/test/java/org/prebid/server/bidder/adtelligent/AdtelligentBidderTest.java
src/test/java/org/prebid/server/validation/BidderParamValidatorTest.java

Adtarget and Adtelligent Bidders: Change Aid Type

---

src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
src/main/java/org/prebid/server/spring/config/bidder/RubiconConfiguration.java
src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java

Rubicon: Remove `use-video-size-id-logic` processing

---

src/main/java/org/prebid/server/bidder/rtbhouse/RtbhouseBidder.java
src/test/java/org/prebid/server/bidder/rtbhouse/RtbhouseBidderTest.java
src/test/resources/org/prebid/server/it/openrtb2/rtbhouse/test-auction-rtbhouse-response.json
src/test/resources/org/prebid/server/it/openrtb2/rtbhouse/test-rtbhouse-bid-response.json

The adapter is now able to resolve `${AUCTION_PRICE}` macro in win notify URLs.
Win notify URLs contain the macro. It has to be resolved with the default bidder's currency.
PBS-Go counterpart PR: https://github.com/prebid/prebid-server/pull/3901
Tests passed. Expected behavior tested locally.
Please reach us at [inventory_support@rtbhouse.com](mailto:inventory_support@rtbhouse.com) with [piotr.jaworski@rtbhouse.com](mailto:piotr.jaworski@rtbhouse.com) and cc [leandro.otani@rtbhouse.com](mailto:leandro.otani@rtbhouse.com).

RTB House: resolve oRTB `AUCTION_PRICE` macro

---

README.md
src/main/docker/run.sh

Our documentation about running PBS as a Docker image was incomplete. This PR fixes this by providing examples and a description of minimal configuration.

Housekeeping: Dockerfile documentation clarifications

---

src/test/groovy/org/prebid/server/functional/testcontainers/Dependencies.groovy

Functional test fix startup `localstack` container

---

src/main/java/org/prebid/server/analytics/reporter/agma/AgmaAnalyticsReporter.java
src/main/java/org/prebid/server/analytics/reporter/agma/EventBuffer.java
src/main/java/org/prebid/server/analytics/reporter/agma/model/AgmaAccountAnalyticsProperties.java
src/main/java/org/prebid/server/analytics/reporter/agma/model/AgmaAnalyticsProperties.java
src/main/java/org/prebid/server/analytics/reporter/agma/model/AgmaEvent.java
src/main/java/org/prebid/server/spring/config/AnalyticsConfiguration.java
src/main/resources/application.yaml
src/test/java/org/prebid/server/analytics/reporter/agma/AgmaAnalyticsReporterTest.java
src/test/java/org/prebid/server/analytics/reporter/agma/EventBufferTest.java

Agma Analytics Adapter

---

src/main/java/org/prebid/server/bidder/connectad/ConnectAdBidder.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/connectad/ExtImpConnectAd.java
src/main/resources/bidder-config/lemmadigital.yaml
src/main/resources/bidder-config/playdigo.yaml
src/main/resources/bidder-config/qt.yaml
src/main/resources/bidder-config/smartx.yaml
src/test/java/org/prebid/server/bidder/connectad/ConnectAdBidderTest.java
src/test/resources/org/prebid/server/it/openrtb2/connectad/test-auction-connectad-request.json
src/test/resources/org/prebid/server/it/openrtb2/connectad/test-connectad-bid-request.json
src/test/resources/org/prebid/server/it/openrtb2/smartx/test-smartx-bid-request.json

Minor Bidders Updates

---

src/main/java/org/prebid/server/auction/BidResponseCreator.java
src/main/java/org/prebid/server/auction/StoredResponseProcessor.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtStoredAuctionResponse.java
src/main/java/org/prebid/server/validation/ImpValidator.java
src/test/groovy/org/prebid/server/functional/model/request/auction/StoredAuctionResponse.groovy
src/test/groovy/org/prebid/server/functional/tests/StoredResponseSpec.groovy
src/test/java/org/prebid/server/auction/SkippedAuctionServiceTest.java
src/test/java/org/prebid/server/auction/StoredResponseProcessorTest.java
src/test/java/org/prebid/server/validation/ImpValidatorTest.java

Add storedAuctionResponse on imp level.

---

src/main/java/com/iab/openrtb/request/Eid.java
src/main/java/com/iab/openrtb/request/Uid.java
src/main/java/org/prebid/server/auction/requestfactory/AmpRequestFactory.java
src/main/java/org/prebid/server/auction/requestfactory/AuctionRequestFactory.java
src/main/java/org/prebid/server/auction/requestfactory/Ortb2RequestFactory.java
src/main/java/org/prebid/server/auction/requestfactory/VideoRequestFactory.java
src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
src/main/java/org/prebid/server/validation/RequestValidator.java
src/test/groovy/org/prebid/server/functional/model/request/auction/Eid.groovy
src/test/groovy/org/prebid/server/functional/tests/EidsSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/OrtbConverterSpec.groovy
src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
src/test/java/org/prebid/server/auction/privacy/enforcement/TcfEnforcementTest.java
src/test/java/org/prebid/server/auction/privacy/enforcement/mask/UserFpdTcfMaskTest.java
src/test/java/org/prebid/server/auction/requestfactory/AmpRequestFactoryTest.java
src/test/java/org/prebid/server/auction/requestfactory/AuctionRequestFactoryTest.java
src/test/java/org/prebid/server/auction/requestfactory/Ortb2RequestFactoryTest.java
src/test/java/org/prebid/server/auction/requestfactory/VideoRequestFactoryTest.java
src/test/java/org/prebid/server/auction/versionconverter/down/BidRequestOrtb26To25ConverterTest.java
src/test/java/org/prebid/server/auction/versionconverter/up/BidRequestOrtb25To26ConverterTest.java
src/test/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidderTest.java
src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java
src/test/java/org/prebid/server/bidder/siverpush/SilverPushBidderTest.java
src/test/java/org/prebid/server/validation/RequestValidatorTest.java

https://github.com/prebid/prebid-server/issues/3859

Core: Remove Empty EIDs + add new ortb fields

---

src/main/resources/bidder-config/yieldmo.yaml
src/test/resources/org/prebid/server/it/openrtb2/yieldmo/test-yieldmo-bid-request.json

Indicating ortb 2.6 support for yieldmo in the yaml file, and updating the test request json to move the gdpr field out of the regs.ext object, per the ortb 2.6 protocol.

add ortb-version to yieldmo.yaml

---

src/main/java/org/prebid/server/bidder/sonobi/SonobiBidder.java
src/main/java/org/prebid/server/spring/config/bidder/SonobiConfiguration.java
src/main/resources/bidder-config/sonobi.yaml
src/test/java/org/prebid/server/bidder/sonobi/SonobiBidderTest.java
src/test/resources/org/prebid/server/it/openrtb2/sonobi/test-auction-sonobi-response.json

Sonobi Bidder: Native and Currency Conversion Support

---

src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/VendorList.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAmpSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/PrivacyBaseSpec.groovy
src/test/groovy/org/prebid/server/functional/util/privacy/VendorListConsent.groovy

Test: Update tcf policy version

---

src/main/java/org/prebid/server/privacy/gdpr/TcfDefinerService.java
src/main/java/org/prebid/server/privacy/gdpr/vendorlist/VersionedVendorListService.java
src/main/java/org/prebid/server/spring/config/PrivacyServiceConfiguration.java
src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/VendorList.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAmpSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/PrivacyBaseSpec.groovy
src/test/groovy/org/prebid/server/functional/util/privacy/VendorListConsent.groovy
src/test/java/org/prebid/server/privacy/gdpr/TcfDefinerServiceTest.java
src/test/java/org/prebid/server/privacy/gdpr/vendorlist/VersionedVendorListServiceTest.java

Update TCF policy version validation

---

src/main/java/org/prebid/server/bidder/yieldlab/YieldlabBidder.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/yieldlab/ExtImpYieldlab.java
src/main/resources/static/bidder-params/yieldlab.json
src/test/java/org/prebid/server/bidder/yieldlab/YieldlabBidderTest.java

Port https://github.com/prebid/prebid-server/pull/2364

Yieldlab Bidder: Support for Ad Unit Sizes

---

extra/modules/pb-response-correction/src/main/java/org/prebid/server/hooks/modules/pb/response/correction/core/correction/appvideohtml/AppVideoHtmlCorrection.java
extra/modules/pb-response-correction/src/test/java/org/prebid/server/hooks/modules/pb/response/correction/core/correction/appvideohtml/AppVideoHtmlCorrectionTest.java
src/test/groovy/org/prebid/server/functional/tests/module/responsecorrenction/ResponseCorrectionSpec.groovy

Response correction module does not match VAST markup correctly.

Response correction: Fix VAST matching

---

docs/developers/functional-tests.md
pom.xml
src/test/groovy/org/prebid/server/functional/testcontainers/PbsServiceFactory.groovy

Increase default number for `tests.max-container-count`

---

src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/PrebidCache.groovy
src/test/groovy/org/prebid/server/functional/tests/CacheSpec.groovy

Add functional tests for cache-api-key attribute

---

src/test/groovy/org/prebid/server/functional/model/config/AccountAuctionConfig.groovy
src/test/groovy/org/prebid/server/functional/model/config/PriceGranularityType.groovy
src/test/groovy/org/prebid/server/functional/model/request/auction/PriceGranularity.groovy
src/test/groovy/org/prebid/server/functional/model/request/auction/Range.groovy
src/test/groovy/org/prebid/server/functional/tests/TargetingSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
src/test/groovy/org/prebid/server/functional/util/PBSUtils.groovy

Add functional tests for account PriceGranularity config

---

src/main/java/org/prebid/server/bidder/displayio/DisplayioBidder.java
src/test/java/org/prebid/server/bidder/displayio/DisplayioBidderTest.java

Displayio Bidder: Bidfloor Validation Update

---

src/test/groovy/org/prebid/server/functional/model/request/auction/BidRequest.groovy
src/test/groovy/org/prebid/server/functional/model/request/auction/DebugCondition.groovy
src/test/groovy/org/prebid/server/functional/model/request/auction/Prebid.groovy
src/test/groovy/org/prebid/server/functional/tests/BidValidationSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/DebugSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/SeatNonBidSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsBaseSpec.groovy

Add tests for Zero Non Deal Bids Warning Only in Debug

---

src/main/java/org/prebid/server/analytics/reporter/agma/AgmaAnalyticsReporter.java
src/main/java/org/prebid/server/spring/config/AnalyticsConfiguration.java
src/test/java/org/prebid/server/analytics/reporter/agma/AgmaAnalyticsReporterTest.java

Thanks @AntoxaAntoxic for the port of our adapter! During testing we found 2 minor bugs in the implementation-
- 9da4ca89af35efcf07b1e670563425da7b1dc3d4: prevents triggering a POST request when the buffer is empty. [original](https://github.com/prebid/prebid-server/blob/master/analytics/agma/agma_module.go#L128-L131)
- 2271af3b6490ca1613cdbdd04d4cd32054e32730: respect the sitesApp config and allow empty strings as publisherId, when the sitesApp is set. This also allows a publisher to set multiple codes for multiple sites/apps for the same `publisherId`. [original test](https://github.com/prebid/prebid-server/blob/master/analytics/agma/agma_module_test.go#L293-L305)
Thanks again for the port!

agma: bugfixes

---

src/main/java/org/prebid/server/auction/PriceGranularity.java
src/main/java/org/prebid/server/auction/requestfactory/AmpRequestFactory.java
src/main/java/org/prebid/server/auction/requestfactory/Ortb2ImplicitParametersResolver.java
src/test/groovy/org/prebid/server/functional/model/config/AccountAuctionConfig.groovy
src/test/groovy/org/prebid/server/functional/model/config/PriceGranularityType.groovy
src/test/groovy/org/prebid/server/functional/model/request/auction/PriceGranularity.groovy
src/test/groovy/org/prebid/server/functional/model/request/auction/Range.groovy
src/test/groovy/org/prebid/server/functional/tests/TargetingSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
src/test/groovy/org/prebid/server/functional/util/PBSUtils.groovy
src/test/java/org/prebid/server/auction/PriceGranularityTest.java
src/test/java/org/prebid/server/auction/requestfactory/AmpRequestFactoryTest.java
src/test/java/org/prebid/server/auction/requestfactory/Ortb2ImplicitParametersResolverTest.java

https://github.com/prebid/prebid-server-java/issues/2075

Price Granularity Defaults Fix

---

src/main/java/org/prebid/server/auction/ExchangeService.java
src/test/groovy/org/prebid/server/functional/model/request/auction/BidRequest.groovy
src/test/groovy/org/prebid/server/functional/model/request/auction/DebugCondition.groovy
src/test/groovy/org/prebid/server/functional/model/request/auction/Prebid.groovy
src/test/groovy/org/prebid/server/functional/tests/BidValidationSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/DebugSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/SeatNonBidSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsBaseSpec.groovy
src/test/java/org/prebid/server/auction/ExchangeServiceTest.java

Add Zero Non Deal Bids Warning Only in Debug

---

extra/modules/ortb2-blocking/src/main/java/org/prebid/server/hooks/modules/ortb2/blocking/core/AccountConfigReader.java
extra/modules/ortb2-blocking/src/main/java/org/prebid/server/hooks/modules/ortb2/blocking/core/RequestUpdater.java
extra/modules/ortb2-blocking/src/test/java/org/prebid/server/hooks/modules/ortb2/blocking/core/AccountConfigReaderTest.java
extra/modules/ortb2-blocking/src/test/java/org/prebid/server/hooks/modules/ortb2/blocking/core/RequestUpdaterTest.java
src/test/groovy/org/prebid/server/functional/tests/module/ortb2blocking/Ortb2BlockingSpec.groovy

https://github.com/prebid/prebid-server/issues/4006
https://github.com/prebid/prebid-server-java/pull/3523

Bugfix: Make OpenRTB battr logic more strict

---

src/main/resources/bidder-config/unruly.yaml

https://github.com/prebid/prebid-server/pull/4028
GZIP breaks Unruly bidder

Unruly: Remove GZIP compression as this breaks the bidder

---

src/main/java/org/prebid/server/bidder/gotthamads/GothamAdsBidder.java
src/test/java/org/prebid/server/bidder/gothamads/GothamAdsBidderTest.java

Update Gothamads account passing

---

.github/pull_request_template.md

PR template had some inconsistencies.
Extended the PR template with some things that are frequently done. Plus fixed typos.
It's a documentation.

Housekeeping: Update pull_request_template.md

---

src/test/groovy/org/prebid/server/functional/tests/BidExpResponseSpec.groovy

Test: default bids cache ttl

---

src/main/resources/bidder-config/sharethrough.yaml
src/test/resources/org/prebid/server/it/openrtb2/sharethrough/test-sharethrough-bid-request.json

Updating the bid adapter's configuration file (`sharethrough.yaml`).
Making these changes so that publishers and other partners are aware that Sharethrough's exchange supports oRTB 2.6-compliant bid requests.

Sharethrough: declare support for oRTB 2.6

---

src/main/java/org/prebid/server/auction/requestfactory/AmpRequestFactory.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtUser.java
src/test/java/org/prebid/server/auction/requestfactory/AmpRequestFactoryTest.java
src/test/java/org/prebid/server/bidder/improvedigital/ImprovedigitalBidderTest.java
src/test/resources/org/prebid/server/it/amp/test-generic-bid-request.json
src/test/resources/org/prebid/server/it/amp/test-genericAlias-bid-request.json

Apparently Google documentation had an error. To avoid breaking changes we now support both `ConsentedProvidersSettings` and `consented_providers_settings` fields.
Unit tests + functional tests.

Amp: update consented providers settings support

---

src/test/groovy/org/prebid/server/functional/model/config/AdminConfig.groovy
src/test/groovy/org/prebid/server/functional/model/response/auction/TraceOutcome.groovy
src/test/groovy/org/prebid/server/functional/tests/module/GeneralModuleSpec.groovy

Functional tests for module execution host config check

---

src/main/java/org/prebid/server/hooks/execution/HookStageExecutor.java
src/test/java/org/prebid/server/hooks/execution/HookStageExecutorTest.java

Modules: Fix NPE that can occur during  hooks execution

---

extra/modules/pb-richmedia-filter/src/main/java/org/prebid/server/hooks/modules/pb/richmedia/filter/config/PbRichmediaFilterModuleConfiguration.java
src/test/groovy/org/prebid/server/functional/tests/module/ModuleBaseSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/module/richmedia/RichMediaFilterSpec.groovy

The pb-richmedia-filter module was requiring `filter-mraid` and `mraid-script-pattern` to be set globally. This is sometimes pointless.
This change makes those properties optional so that module can be enabled globally, but configured per-account.

Make pr-richmedia-filter global properties optional

---

extra/modules/greenbids-real-time-data/src/test/java/org/prebid/server/hooks/modules/greenbids/real/time/data/v1/GreenbidsRealTimeDataProcessedAuctionRequestHookTest.java

We overlooked that unit tests for GreenBid module were using a real world URL to pull a file from the internet. The file is no more, so tests now fail which breaks the build of the project.
This is a quick and dirty "fix" until tests are properly updated by maintainer @EvgeniiMunin .

GreenBids module: Ignore broken tests

---

src/main/java/org/prebid/server/analytics/reporter/agma/AgmaAnalyticsReporter.java
src/test/java/org/prebid/server/analytics/reporter/agma/AgmaAnalyticsReporterTest.java

We got reports that using non existing Stored Requests / Impressions leads to a Nullpointer

AGMA: Fix Nullpointer on empty auction context

---

src/main/java/org/prebid/server/bidder/epsilon/EpsilonBidder.java
src/main/resources/bidder-config/epsilon.yaml
src/test/java/org/prebid/server/bidder/epsilon/EpsilonBidderTest.java

Adding audio type
https://github.com/prebid/prebid-server-java/issues/3605

Conversant: Enable audio requests #3605

---

src/test/groovy/org/prebid/server/functional/tests/module/GeneralModuleSpec.groovy

update functional test for module execution

---

src/main/resources/bidder-config/pubmatic.yaml
src/test/resources/org/prebid/server/it/openrtb2/pubmatic/test-auction-pubmatic-request.json
src/test/resources/org/prebid/server/it/openrtb2/pubmatic/test-pubmatic-bid-request.json

See: https://github.com/prebid/prebid-server-java/issues/3581
Ported from PBS-Go: https://github.com/prebid/prebid-server/pull/4078
Keeping the bidder config for PBS-java updated
If tests are green, we're good to go, right? :blush:

Fix #3581 declare PubMatic support for openRTB 2.6

---

docs/build.md

Documentation housekeeping
`build.md` was mentioning wrong Java version
N/A

Docs: Fix incorrect Java version reference in the build.md

---

src/main/resources/bidder-config/pgamssp.yaml

Merged changes from Go adapter: https://github.com/prebid/prebid-server/pull/4056
```
% curl https://vendor-list.consensu.org/v3/vendor-list.json | jq '.vendors."1353"'
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  652k  100  652k    0     0  2744k      0 --:--:-- --:--:-- --:--:-- 2753k
{
"id": 1353,
"name": "PGAM Media LLC",
"purposes": [
1,
3,
4,
5,
6,
7,
8,
9,
10
],
"legIntPurposes": [],
"flexiblePurposes": [],
"specialPurposes": [
3
],
"features": [
3
],
"specialFeatures": [
1
],
"cookieMaxAgeSeconds": 1209600,
"usesCookies": true,
"cookieRefresh": true,
"urls": [
{
"langId": "en",
"privacy": "https://pgammedia.com/privacy-policy/",
"legIntClaim": "https://pgammedia.com/privacy-policy/"
}
], …
```

PgamSSP adapter : add GVL ID

---

src/test/groovy/org/prebid/server/functional/tests/privacy/ActivityTraceLogSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAmpSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GppSyncUserActivitiesSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/PrivacyBaseSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/TcfFullTransmitEidsActivitiesSpec.groovy

Update privacy functional test: GVL file handling

---

src/main/java/org/prebid/server/bidder/smaato/SmaatoBidder.java
src/test/java/org/prebid/server/bidder/smaato/SmaatoBidderTest.java
src/test/resources/org/prebid/server/it/openrtb2/smaato/test-auction-smaato-request.json
src/test/resources/org/prebid/server/it/openrtb2/smaato/test-smaato-bid-request.json

Smaato: Send imp.ext object

---

src/main/java/org/prebid/server/bidder/flipp/FlippBidder.java
src/test/java/org/prebid/server/bidder/flipp/FlippBidderTest.java
src/test/resources/org/prebid/server/it/openrtb2/flipp/test-auction-flipp-response.json

Flipp: use height value from server response

---

src/main/java/org/prebid/server/bidder/pubmatic/PubmaticBidder.java
src/test/java/org/prebid/server/bidder/pubmatic/PubmaticBidderTest.java
src/test/resources/org/prebid/server/it/openrtb2/pubmatic/test-pubmatic-bid-request.json

Pubmatic: Bidder Updates

---

src/main/resources/bidder-config/adkernel.yaml

Added `rxnetwork` as alias for `adkernel`

rxnetwork: adding rxnetwork alias to adkernel

---

.github/workflows/code-path-changes.yml
.github/workflows/scripts/codepath-notification
.github/workflows/scripts/send-notification-on-change.js

Allow adapters and module owners to register for alerts when a PR is opened against their code. See https://github.com/prebid/prebid-server/issues/4075
I tested this over in the sourcecred repo and have set up the config file just for Index Exchange at this point. Working on Prebid documentation for it.

GitHub: codepath alerts

---

.github/workflows/pr-java-ci.yml

I noticed that on my  PR no caching is taking place.
https://github.com/prebid/prebid-server-java/pull/3613/checks shows
> Creating settings.xml with server-id: github
> Writing to /home/runner/.m2/settings.xml
> maven cache is not found
Make PR tests faster

Add cache-dependency-path

---

src/test/groovy/org/prebid/server/functional/model/config/AccountPriceFloorsConfig.groovy
src/test/groovy/org/prebid/server/functional/model/config/PriceFloorsFetch.groovy
src/test/groovy/org/prebid/server/functional/model/request/auction/ExtPrebidFloors.groovy
src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsBaseSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsRulesSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsSignalingSpec.groovy

Test: Price floors max rules dimensions

---

src/main/java/org/prebid/server/auction/BidderAliases.java
src/main/java/org/prebid/server/auction/ExchangeService.java
src/main/java/org/prebid/server/auction/privacy/enforcement/TcfEnforcement.java
src/main/java/org/prebid/server/privacy/gdpr/VendorIdResolver.java
src/test/groovy/org/prebid/server/functional/model/bidder/BidderName.groovy
src/test/groovy/org/prebid/server/functional/model/request/auction/Bidder.groovy
src/test/groovy/org/prebid/server/functional/tests/AliasSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/ImpRequestSpec.groovy
src/test/java/org/prebid/server/auction/BidderAliasesTest.java
src/test/java/org/prebid/server/auction/ExchangeServiceTest.java

https://github.com/prebid/prebid-server/issues/2391

Update Alias Behavior

---

src/test/groovy/org/prebid/server/functional/tests/SetUidSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GdprSetUidSpec.groovy

Tests: Increase coverage for setUid endpoint

---

src/main/java/org/prebid/server/cookie/CookieSyncService.java
src/main/java/org/prebid/server/handler/SetuidHandler.java
src/main/java/org/prebid/server/util/StreamUtil.java
src/test/groovy/org/prebid/server/functional/tests/SetUidSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GdprSetUidSpec.groovy
src/test/java/org/prebid/server/handler/SetuidHandlerTest.java

Setuid: Cookie Family Fix

---

src/main/java/org/prebid/server/bidder/metax/MetaxBidder.java
src/test/java/org/prebid/server/bidder/metax/MetaxBidderTest.java

Add BidVideo for video ads
https://github.com/prebid/prebid-server-java/issues/3631

Metax: Update bidder (#3631)

---

src/main/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidder.java
src/test/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidderTest.java

Adnuntius: Use format=prebidServer on adserver requests

---

src/test/groovy/org/prebid/server/functional/tests/EidsSpec.groovy

Tests: Eidpermissions Request Validation Update

---

src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/PrivacyBaseSpec.groovy

Test: Buyeruid scrubbed metric

---

src/test/groovy/org/prebid/server/functional/tests/AliasSpec.groovy

Tests: Fix Bidder Aliases Validation

---

src/main/java/org/prebid/server/auction/requestfactory/AmpRequestFactory.java
src/main/java/org/prebid/server/auction/requestfactory/AuctionRequestFactory.java
src/main/java/org/prebid/server/auction/requestfactory/Ortb2RequestFactory.java
src/main/java/org/prebid/server/auction/requestfactory/VideoRequestFactory.java
src/main/java/org/prebid/server/validation/RequestValidator.java
src/test/groovy/org/prebid/server/functional/tests/EidsSpec.groovy
src/test/java/org/prebid/server/auction/requestfactory/AmpRequestFactoryTest.java
src/test/java/org/prebid/server/auction/requestfactory/AuctionRequestFactoryTest.java
src/test/java/org/prebid/server/auction/requestfactory/Ortb2RequestFactoryTest.java
src/test/java/org/prebid/server/auction/requestfactory/VideoRequestFactoryTest.java
src/test/java/org/prebid/server/validation/RequestValidatorTest.java

https://github.com/prebid/prebid-server/issues/4114

Eidpermissions Request Validation Update

---

src/main/java/org/prebid/server/auction/privacy/enforcement/TcfEnforcement.java
src/main/java/org/prebid/server/metric/MetricName.java
src/main/java/org/prebid/server/metric/Metrics.java
src/main/java/org/prebid/server/spring/config/PrivacyServiceConfiguration.java
src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
src/test/java/org/prebid/server/auction/privacy/enforcement/TcfEnforcementTest.java
src/test/java/org/prebid/server/metric/MetricsTest.java

Buyeruid Scrubbed Metric

---

src/main/java/org/prebid/server/validation/ImpValidator.java
src/test/groovy/org/prebid/server/functional/tests/AliasSpec.groovy
src/test/java/org/prebid/server/validation/ImpValidatorTest.java

https://github.com/prebid/prebid-server/issues/2391

Fix Bidder Aliases Validation

---

src/main/java/org/prebid/server/cookie/CookieSize.java
src/main/java/org/prebid/server/cookie/UidsCookieService.java
src/main/java/org/prebid/server/cookie/UidsCookieSize.java

- `.000000000Z` -> `.000000Z`
- fixed bug when we adding `cookieName id` size for each `uid` instead once for whole `cookie`
- changed logic so we can add as many uids as possible without any risks
- refactoring

Change size prediction logic

---

src/main/java/org/prebid/server/auction/ImpAdjuster.java
src/test/groovy/org/prebid/server/functional/model/request/auction/ImpExt.groovy
src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/bidder/openx/OpenxSpec.groovy
src/test/java/org/prebid/server/auction/ImpAdjusterTest.java
src/test/resources/org/prebid/server/it/openrtb2/ix/test-ix-bid-request.json

In https://github.com/prebid/prebid-server-java/pull/3670 I mistreated imp.ext.igs type and made it to be an array instead of object.
Unit tests.

Core: Fix PAA imp.ext.igs.ae population

---

src/main/java/org/prebid/server/bidder/insticator/InsticatorBidder.java
src/test/java/org/prebid/server/bidder/insticator/InsticatorBidderTest.java

Insticator bidder adaptor had an issue in video validation
This is a one-line fix to the video validation logic
N/A

Insticator: fix video validation logic

---

docs/config-app.md
docs/metrics.md
src/main/java/org/prebid/server/auction/requestfactory/AmpRequestFactory.java
src/main/java/org/prebid/server/auction/requestfactory/AuctionRequestFactory.java
src/main/java/org/prebid/server/auction/requestfactory/Ortb2RequestFactory.java
src/main/java/org/prebid/server/auction/requestfactory/VideoRequestFactory.java
src/main/java/org/prebid/server/metric/MetricName.java
src/main/java/org/prebid/server/metric/Metrics.java
src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
src/main/java/org/prebid/server/validation/RequestValidator.java
src/main/resources/application.yaml
src/test/java/org/prebid/server/auction/requestfactory/AmpRequestFactoryTest.java
src/test/java/org/prebid/server/auction/requestfactory/AuctionRequestFactoryTest.java
src/test/java/org/prebid/server/auction/requestfactory/Ortb2RequestFactoryTest.java
src/test/java/org/prebid/server/auction/requestfactory/VideoRequestFactoryTest.java
src/test/java/org/prebid/server/metric/MetricsTest.java
src/test/java/org/prebid/server/validation/RequestValidatorTest.java

Fix [issue #3592](https://github.com/prebid/prebid-server-java/issues/3592). Bad Input Error if pbjs s2s config contains alias configuration for a disabled adapter.
Move unknown bidder and bidder is deactivated errors to warnings level.
Add unknown_bidder and deactivated_bidder metrics
Changes are covered by unit tests.

Fix #3592. Bad Input Error if pbjs s2s config contains alias configuration for a disabled adapter

---

src/main/resources/bidder-config/compass.yaml

https://github.com/prebid/prebid-server-java/issues/3734

Compass: Add user sync GPP support #3734

---

src/main/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidder.java
src/main/java/org/prebid/server/bidder/adnuntius/model/response/AdnuntiusAd.java
src/test/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidderTest.java
src/test/resources/org/prebid/server/it/openrtb2/adnuntius/test-adnuntius-bid-response.json

https://github.com/prebid/prebid-server-java/issues/3736

Adnuntius: Copy advertiserDomains to ORTB bid response adomain #3736

---

src/main/java/org/prebid/server/validation/BidderParamValidator.java
src/test/java/org/prebid/server/bidder/adtrgtme/AdtrgtmeBidderTest.java
src/test/java/org/prebid/server/it/ApplicationTest.java
src/test/java/org/prebid/server/validation/BidderParamValidatorTest.java

Use a hard-alias schema if present

---

src/main/java/org/prebid/server/bidder/ix/IxBidder.java
src/test/java/org/prebid/server/bidder/ix/IxBidderTest.java

Fix IX bidder's crash with Nullpointer at merging NativeImpTrackers for adm when Imptrackers are absent. 
It makes auction fail. 
Stacktrace:
```2025-02-18T22:22:42.529Z ERROR 1 --- [ntloop-thread-7] o.p.s.handler.openrtb2.AuctionHandler    : Critical error while running the auction
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "com.iab.openrtb.response.Response.getImptrackers()" is null
at org.prebid.server.bidder.ix.IxBidder.mergeNativeImpTrackers(IxBidder.java:392)
at org.prebid.server.bidder.ix.IxBidder.mergeNativeImpTrackers(IxBidder.java:382)
at org.prebid.server.bidder.ix.IxBidder.updateBidAdmWithNativeAttributes(IxBidder.java:364)
at org.prebid.server.bidder.ix.IxBidder.toBidderBid(IxBidder.java:281)
at …
```

Fix IX bidder crash

---

src/test/groovy/org/prebid/server/functional/model/request/cache/BidCachePut.groovy
src/test/groovy/org/prebid/server/functional/tests/CacheSpec.groovy

Functional tests for prebid cache traceability

---

extra/modules/greenbids-real-time-data/src/main/java/org/prebid/server/hooks/modules/greenbids/real/time/data/core/GreenbidsInvocationService.java
extra/modules/greenbids-real-time-data/src/main/java/org/prebid/server/hooks/modules/greenbids/real/time/data/model/result/AnalyticsResult.java
extra/modules/greenbids-real-time-data/src/main/java/org/prebid/server/hooks/modules/greenbids/real/time/data/v1/GreenbidsRealTimeDataProcessedAuctionRequestHook.java
extra/modules/greenbids-real-time-data/src/test/java/org/prebid/server/hooks/modules/greenbids/real/time/data/core/GreenbidsInvocationServiceTest.java
extra/modules/greenbids-real-time-data/src/test/java/org/prebid/server/hooks/modules/greenbids/real/time/data/util/TestBidRequestProvider.java
extra/modules/greenbids-real-time-data/src/test/java/org/prebid/server/hooks/modules/greenbids/real/time/data/v1/GreenbidsRealTimeDataProcessedAuctionRequestHookTest.java
src/main/java/org/prebid/server/analytics/reporter/greenbids/GreenbidsAnalyticsReporter.java
src/test/java/org/prebid/server/analytics/reporter/greenbids/GreenbidsAnalyticsReporterTest.java

We want to populate the `appliedTo` field in the analytics tag and change the structure of analytics results to one imp per result. The example of the modified analytics tag results is as follows:
```json
"results": [
{
"status": "success",
"values": {
"pub_banniere_haute": {
"greenbids": {
"fingerprint": "dd151fbe-38f5-440e-a72d-17810ed8bb9e",
"keptInAuction": {
"improvedigital": true,
"appnexus": true,
"pubmatic": true,
"rubicon": true,
"teads": true
},
"isExploration": false
},
"tid": "e4e1f086-085b-4ecc-aadc-630d023c1ca2"
}
},
"appliedTo": {
"impIds": [
"pub_banniere_haute"
],
"bidders": null
"request": false,
"response": false,
"bidIds": null
}
},
{
"status": "success",
"values": {
"pub_native_web_atf1": {
"greenbids": {
"fingerprint": "dd151fbe-38f5-440e-a72d-17810ed8bb9e", …
```

Greenbids: Populate AppliedTo and change structure of analytics results in Analytics Tag

---

src/main/java/org/prebid/server/bidder/admatic/AdmaticBidder.java
src/test/java/org/prebid/server/bidder/admatic/AdmaticBidderTest.java

https://github.com/prebid/prebid-server-java/issues/3707

Admatic: Update headers for adapter

---

src/main/resources/bidder-config/admatic.yaml
src/test/java/org/prebid/server/it/AdtTest.java
src/test/resources/org/prebid/server/it/openrtb2/adt/test-adt-bid-request.json
src/test/resources/org/prebid/server/it/openrtb2/adt/test-adt-bid-response.json
src/test/resources/org/prebid/server/it/openrtb2/adt/test-auction-adt-request.json
src/test/resources/org/prebid/server/it/openrtb2/adt/test-auction-adt-response.json
src/test/resources/org/prebid/server/it/test-application.properties

https://github.com/prebid/prebid-server-java/issues/3753

Adt: port new alias of Admatic from Go

---

docs/developers/bid-adapter-porting-guide.md

Docs: Create a Doc with Guidance for Porting from Go

---

src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java
src/test/resources/org/prebid/server/it/openrtb2/magnite/test-magnite-bid-request.json
src/test/resources/org/prebid/server/it/openrtb2/rubicon/test-rubicon-bid-request.json

Rubicon: simplify logic for truncating segtaxes

---

extra/modules/greenbids-real-time-data/pom.xml
extra/pom.xml
src/test/groovy/org/prebid/server/functional/tests/AliasSpec.groovy
src/test/java/org/prebid/server/geolocation/MaxMindGeoLocationServiceTest.java
src/test/java/org/prebid/server/validation/BidderParamValidatorTest.java

* Updated three dependencies to address several CVEs and improve security posture: geoip2, json-schema-validator, and pinned commons-logging to a safe version.
* Updated unit tests for geoip2 and json-schema-validator for dependency updates.
* Updated geoip2 removed several constructors requiring more mocking for the Geo types.
* Updated json-schema-validator returns an additional message for some failed validations, ""$: should be valid to one and only one schema, but 0 are valid"
Update dependencies to improve security posture.
* Relied on existing unit tests for verification of changes.
* Used `mvn clean package` for build and test after each change.
- [Y] Are your changes following [our code style guidelines](https://github.com/prebid/prebid-server-java/blob/master/docs/developers/code …

Housekeeping: Update 3rd party dependencies

---

.github/workflows/scripts/codepath-notification

Seeding the code path notification with additional bidders before opening the door to the Prebid community. These ones will all ask anyhow.

Adding other SSPs to codepath-notification

---

src/main/java/org/prebid/server/bidder/adverxo/AdverxoBidder.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/adverxo/ExtImpAdverxo.java
src/main/java/org/prebid/server/spring/config/bidder/AdverxoBidderConfiguration.java
src/main/resources/bidder-config/adverxo.yaml
src/main/resources/static/bidder-params/adverxo.json
src/test/java/org/prebid/server/bidder/adverxo/AdverxoBidderTest.java
src/test/java/org/prebid/server/it/AdportTest.java
src/test/java/org/prebid/server/it/AdverxoTest.java
src/test/java/org/prebid/server/it/BidsmindTest.java
src/test/java/org/prebid/server/it/MobuppsTest.java
src/test/resources/org/prebid/server/it/openrtb2/adport/test-adport-bid-request.json
src/test/resources/org/prebid/server/it/openrtb2/adport/test-adport-bid-response.json
src/test/resources/org/prebid/server/it/openrtb2/adport/test-auction-adport-request.json
src/test/resources/org/prebid/server/it/openrtb2/adport/test-auction-adport-response.json
src/test/resources/org/prebid/server/it/openrtb2/adverxo/test-adverxo-bid-request.json
src/test/resources/org/prebid/server/it/openrtb2/adverxo/test-adverxo-bid-response.json
src/test/resources/org/prebid/server/it/openrtb2/adverxo/test-auction-adverxo-request.json
src/test/resources/org/prebid/server/it/openrtb2/adverxo/test-auction-adverxo-response.json
src/test/resources/org/prebid/server/it/openrtb2/bidsmind/test-auction-bidsmind-request.json
src/test/resources/org/prebid/server/it/openrtb2/bidsmind/test-auction-bidsmind-response.json
src/test/resources/org/prebid/server/it/openrtb2/bidsmind/test-bidsmind-bid-request.json
src/test/resources/org/prebid/server/it/openrtb2/bidsmind/test-bidsmind-bid-response.json
src/test/resources/org/prebid/server/it/openrtb2/mobupps/test-auction-mobupps-request.json
src/test/resources/org/prebid/server/it/openrtb2/mobupps/test-auction-mobupps-response.json
src/test/resources/org/prebid/server/it/openrtb2/mobupps/test-mobupps-bid-request.json
src/test/resources/org/prebid/server/it/openrtb2/mobupps/test-mobupps-bid-response.json
src/test/resources/org/prebid/server/it/test-application.properties

https://github.com/prebid/prebid-server-java/issues/3677#event-16015779221

Adverxo: New adapter ported from Go

---

src/main/java/org/prebid/server/activity/infrastructure/ActivityInfrastructure.java
src/main/java/org/prebid/server/activity/infrastructure/creator/rule/PrivacyModulesRuleCreator.java
src/main/java/org/prebid/server/activity/infrastructure/debug/ActivityInfrastructureDebug.java
src/main/java/org/prebid/server/activity/infrastructure/privacy/AbstainPrivacyModule.java
src/main/java/org/prebid/server/activity/infrastructure/privacy/SkippedPrivacyModule.java
src/main/java/org/prebid/server/activity/infrastructure/rule/AndRule.java
src/test/groovy/org/prebid/server/functional/tests/privacy/ActivityTraceLogSpec.groovy
src/test/java/org/prebid/server/activity/infrastructure/debug/ActivityInfrastructureDebugTest.java

Skipped Privacy Modules

---

Dockerfile
Dockerfile-modules

Bumping the Docker image version to use the newer base image as the current default one will be EOL next year.
Never image is needed to support some of the dependency update work
Existing test suite should be enough

Docker: Update base Docker image version

---

src/test/groovy/org/prebid/server/functional/tests/AlternateBidderCodeSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/BidAdjustmentSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy

Test:Multiple bidder codes 

---

src/main/java/org/prebid/server/auction/BidResponseCreator.java
src/main/java/org/prebid/server/auction/ExchangeService.java
src/main/java/org/prebid/server/auction/aliases/BidderAliases.java
src/main/java/org/prebid/server/auction/model/BidderResponseInfo.java
src/main/java/org/prebid/server/bidadjustments/BidAdjustmentsProcessor.java
src/main/java/org/prebid/server/validation/RequestValidator.java
src/test/groovy/org/prebid/server/functional/tests/AlternateBidderCodeSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/BidAdjustmentSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
src/test/java/org/prebid/server/auction/BidResponseCreatorTest.java
src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
src/test/java/org/prebid/server/auction/aliases/BidderAliasesTest.java
src/test/java/org/prebid/server/bidadjustments/BidAdjustmentsProcessorTest.java
src/test/java/org/prebid/server/validation/RequestValidatorTest.java

Multiple Bidder Codes Fix

---

src/test/groovy/org/prebid/server/functional/tests/AuctionSpec.groovy
src/test/groovy/org/prebid/server/functional/util/PBSUtils.groovy

Tests: Enforce Random Bid Id Feature

---

src/main/java/org/prebid/server/bidder/aidem/AidemBidder.java
src/main/resources/bidder-config/aidem.yaml
src/main/resources/static/bidder-params/aidem.json
src/test/java/org/prebid/server/bidder/aidem/AidemBidderTest.java

https://github.com/prebid/prebid-server-java/issues/3821

Aidem: Support only banner and video formats

---

src/main/java/org/prebid/server/bidder/ogury/OguryBidder.java
src/main/java/org/prebid/server/spring/config/bidder/OguryConfiguration.java
src/main/resources/bidder-config/ogury.yaml
src/main/resources/static/bidder-params/ogury.json
src/test/java/org/prebid/server/bidder/ogury/OguryBidderTest.java
src/test/java/org/prebid/server/it/OguryTest.java
src/test/resources/org/prebid/server/it/openrtb2/ogury/test-auction-ogury-request.json
src/test/resources/org/prebid/server/it/openrtb2/ogury/test-auction-ogury-response.json
src/test/resources/org/prebid/server/it/openrtb2/ogury/test-ogury-bid-request.json
src/test/resources/org/prebid/server/it/openrtb2/ogury/test-ogury-bid-response.json
src/test/resources/org/prebid/server/it/test-application.properties

New Ogury adapter (Port PR from PBS-Go)
[#3700](https://github.com/prebid/prebid-server-java/issues/3700)
Unit tests with decent coverage

Ogury: port new adapter from Go

---

src/test/groovy/org/prebid/server/functional/model/request/auction/AuctionEnvironment.groovy
src/test/groovy/org/prebid/server/functional/tests/AlternateBidderCodeSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/BidAdjustmentSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/bidder/openx/OpenxSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsRulesSpec.groovy

Test: Multiple bidder codes

---

src/main/java/org/prebid/server/hooks/execution/HookStageExecutor.java
src/main/java/org/prebid/server/hooks/execution/model/ExecutionPlan.java

Modules execution plan: fix NPE

---

src/main/java/org/prebid/server/bidder/oms/OmsBidder.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/omx/ExtImpOms.java
src/main/resources/bidder-config/oms.yaml
src/main/resources/static/bidder-params/oms.json
src/test/java/org/prebid/server/bidder/oms/OmsBidderTest.java
src/test/resources/org/prebid/server/it/openrtb2/oms/test-auction-oms-request.json
src/test/resources/org/prebid/server/it/openrtb2/oms/test-auction-oms-response.json
src/test/resources/org/prebid/server/it/openrtb2/oms/test-oms-bid-request.json
src/test/resources/org/prebid/server/it/openrtb2/oms/test-oms-bid-response.json

https://github.com/prebid/prebid-server-java/issues/3770

OMS: add video support

---

src/main/java/org/prebid/server/auction/gpp/model/GppModelWrapper.java
src/test/groovy/org/prebid/server/functional/tests/privacy/GppSyncUserActivitiesSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitEidsActivitiesSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitUfpdActivitiesSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/PrivacyBaseSpec.groovy
src/test/java/org/prebid/server/auction/gpp/model/GppContextCreatorTest.java
src/test/java/org/prebid/server/auction/gpp/model/GppModelWrapperTest.java

IAB GPP library fails to parse valid GPP sections due to a lack of padding.
This is a hack to add a padding to a GPP string to allow IAB GPP library to parse it.

Core: Pad GPP consent string sections

---

src/test/groovy/org/prebid/server/functional/model/bidder/AppNexus.groovy
src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy

Test: stored imp and stored request

---

src/main/java/org/prebid/server/json/JsonMerger.java
src/main/java/org/prebid/server/json/merge/JsonMergePatch.java
src/main/java/org/prebid/server/json/merge/JsonMergePatchDeserializer.java
src/main/java/org/prebid/server/json/merge/NonObjectMergePatch.java
src/main/java/org/prebid/server/json/merge/ObjectMergePatch.java
src/test/groovy/org/prebid/server/functional/model/bidder/AppNexus.groovy
src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
src/test/java/org/prebid/server/json/merge/JsonMergePatchTest.java

https://github.com/prebid/prebid-server-java/issues/3760

Fix Stored Request Merging

---

src/main/java/org/prebid/server/bidder/seedtag/SeedtagBidder.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/seedtag/ExtImpSeedtag.java
src/main/java/org/prebid/server/spring/config/bidder/SeedtagConfiguration.java
src/main/resources/bidder-config/seedtag.yaml
src/main/resources/static/bidder-params/seedtag.json
src/test/java/org/prebid/server/bidder/seedtag/SeedtagBidderTest.java
src/test/java/org/prebid/server/it/SeedtagTest.java
src/test/resources/org/prebid/server/it/openrtb2/seedtag/test-auction-seedtag-request.json
src/test/resources/org/prebid/server/it/openrtb2/seedtag/test-auction-seedtag-response.json
src/test/resources/org/prebid/server/it/openrtb2/seedtag/test-seedtag-bid-request.json
src/test/resources/org/prebid/server/it/openrtb2/seedtag/test-seedtag-bid-response.json
src/test/resources/org/prebid/server/it/test-application.properties

https://github.com/prebid/prebid-server-java/issues/3787

New Adapter: Seedtag

---

src/main/java/org/prebid/server/bidder/thetradedesk/TheTradeDeskBidder.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/thetradedesk/ExtImpTheTradeDesk.java
src/main/resources/static/bidder-params/thetradedesk.json
src/test/java/org/prebid/server/bidder/thetradedesk/TheTradeDeskBidderTest.java
src/test/resources/org/prebid/server/it/openrtb2/thetradedesk/test-auction-thetradedesk-request.json
src/test/resources/org/prebid/server/it/openrtb2/thetradedesk/test-thetradedesk-bid-request.json
src/test/resources/org/prebid/server/it/test-application.properties

Port TheTradeDesk: Dynamically construct endpoint using supplySourceId

---

src/main/java/org/prebid/server/bidder/invibes/InvibesBidder.java
src/test/java/org/prebid/server/bidder/invibes/InvibesBidderTest.java

InvibesBidder: fix parameter parsing issue

---

src/main/java/org/prebid/server/bidder/zeta_global_ssp/ZetaGlobalSspBidder.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/zeta_global_ssp/ExtImpZetaGlobalSSP.java
src/main/java/org/prebid/server/spring/config/bidder/ZetaGlobalSspConfiguration.java
src/main/resources/bidder-config/generic.yaml
src/main/resources/bidder-config/zeta_global_ssp.yaml
src/main/resources/static/bidder-params/zeta_global_ssp.json
src/test/java/org/prebid/server/bidder/zeta_global_ssp/ZetaGlobalSspBidderTest.java
src/test/resources/org/prebid/server/it/openrtb2/zeta_global_ssp/test-auction-zeta_global_ssp-request.json
src/test/resources/org/prebid/server/it/openrtb2/zeta_global_ssp/test-zeta_global_ssp-bid-request.json
src/test/resources/org/prebid/server/it/openrtb2/zeta_global_ssp/test-zeta_global_ssp-bid-response.json
src/test/resources/org/prebid/server/it/test-application.properties

https://github.com/prebid/prebid-server-java/issues/3818

Zeta Global SSP: Add sid parameter and audio support, no longer generic

---

src/test/groovy/org/prebid/server/functional/tests/privacy/GppSyncUserActivitiesSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitEidsActivitiesSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitUfpdActivitiesSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/PrivacyBaseSpec.groovy

Test: Invalid GPP string for request handling

---

src/main/java/org/prebid/server/bidder/epsilon/EpsilonBidder.java
src/main/resources/bidder-config/epsilon.yaml
src/test/java/org/prebid/server/bidder/epsilon/EpsilonBidderTest.java

- [ X ] new feature
Update the Epsilon bid adapter to allow Native requests
This is a port from PBS https://github.com/prebid/prebid-server/pull/4277

Epsilon: native support

---

src/main/java/org/prebid/server/floors/BasicPriceFloorProcessor.java
src/main/java/org/prebid/server/floors/PriceFloorFetcher.java
src/main/java/org/prebid/server/floors/proto/FetchResult.java
src/main/java/org/prebid/server/spring/config/PriceFloorsConfiguration.java
src/test/groovy/org/prebid/server/functional/model/privacy/Metric.groovy
src/test/groovy/org/prebid/server/functional/model/response/auction/Bid.groovy
src/test/groovy/org/prebid/server/functional/tests/BaseSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/BidValidationSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/MetricsSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/bidder/openx/OpenxSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsBaseSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsRulesSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsSignalingSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAmpSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GppFetchBidActivitiesSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GppSyncUserActivitiesSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitEidsActivitiesSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitPreciseGeoActivitiesSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitUfpdActivitiesSpec.groovy
src/test/java/org/prebid/server/floors/BasicPriceFloorProcessorTest.java
src/test/java/org/prebid/server/floors/PriceFloorFetcherTest.java

Price Floor Logs Update

---

src/main/java/org/prebid/server/activity/infrastructure/creator/ActivityInfrastructureCreator.java
src/main/java/org/prebid/server/activity/infrastructure/creator/privacy/uscustomlogic/USCustomLogicModuleCreator.java
src/main/java/org/prebid/server/activity/infrastructure/creator/privacy/usnat/USNatModuleCreator.java
src/main/java/org/prebid/server/activity/infrastructure/creator/rule/PrivacyModulesRuleCreator.java
src/main/java/org/prebid/server/spring/config/ActivityInfrastructureConfiguration.java
src/test/groovy/org/prebid/server/functional/tests/privacy/GppSyncUserActivitiesSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitEidsActivitiesSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitUfpdActivitiesSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/PrivacyBaseSpec.groovy
src/test/java/org/prebid/server/activity/infrastructure/creator/ActivityInfrastructureCreatorTest.java
src/test/java/org/prebid/server/activity/infrastructure/creator/privacy/uscustomlogic/USCustomLogicModuleCreatorTest.java
src/test/java/org/prebid/server/activity/infrastructure/creator/privacy/usnat/USNatModuleCreatorTest.java
src/test/java/org/prebid/server/activity/infrastructure/creator/rule/PrivacyModulesRuleCreatorTest.java

ActivityInfrastructure: Add exception handling

---

src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java
src/test/resources/org/prebid/server/it/openrtb2/magnite/test-auction-magnite-response.json
src/test/resources/org/prebid/server/it/openrtb2/magnite/test-magnite-bid-response.json
src/test/resources/org/prebid/server/it/openrtb2/rubicon/test-auction-rubicon-response.json
src/test/resources/org/prebid/server/it/openrtb2/rubicon/test-rubicon-bid-response.json

Rubicon Adapter: set additional meta fields

---

src/test/groovy/org/prebid/server/functional/service/PrebidServerService.groovy
src/test/groovy/org/prebid/server/functional/testcontainers/PbsConfig.groovy
src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/CurrencyConversion.groovy
src/test/groovy/org/prebid/server/functional/tests/BidAdjustmentSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/CurrencySpec.groovy
src/test/groovy/org/prebid/server/functional/tests/StoredResponseSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsAdjustmentSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsBaseSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsCurrencySpec.groovy
src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsSignalingSpec.groovy
src/test/groovy/org/prebid/server/functional/util/CurrencyUtil.groovy

Functional tests/currency mock

---

docs/application-settings.md
src/main/java/org/prebid/server/auction/ExchangeService.java
src/main/java/org/prebid/server/settings/model/AccountAuctionConfig.java
src/main/java/org/prebid/server/settings/model/AccountCacheConfig.java
src/test/groovy/org/prebid/server/functional/model/config/AccountAuctionConfig.groovy
src/test/groovy/org/prebid/server/functional/model/config/AccountCacheConfig.groovy
src/test/groovy/org/prebid/server/functional/tests/CacheSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/module/responsecorrenction/ResponseCorrectionSpec.groovy
src/test/java/org/prebid/server/auction/ExchangeServiceTest.java

[Interim Proposal (step 1)](https://github.com/prebid/prebid-server/issues/4150#issuecomment-2640872319)

Add Account auction.cache.enabled Flag

---

src/main/resources/bidder-config/thetradedesk.yaml

Allow integration to be done to The Trade Desk using either thetradedesk or ttd bidder code through an alias.
Prebid.js uses ttd bidder code while PBS uses thetradedesk. Allow both to have a seamless experience.
Already tested by Magnite locally.

Add ttd/thetradedesk alias

---

src/main/java/org/prebid/server/bidder/missena/MissenaAdRequest.java
src/main/java/org/prebid/server/bidder/missena/MissenaBidder.java
src/main/java/org/prebid/server/bidder/missena/MissenaUserParams.java
src/main/java/org/prebid/server/spring/config/bidder/MissenaConfiguration.java
src/main/resources/bidder-config/missena.yaml
src/main/resources/static/bidder-params/missena.json
src/test/java/org/prebid/server/bidder/missena/MissenaBidderTest.java
src/test/java/org/prebid/server/it/MissenaTest.java
src/test/resources/org/prebid/server/it/openrtb2/missena/test-missena-bid-request.json

Missena Adapter: Add formats and settings params

---

src/test/groovy/org/prebid/server/functional/tests/CacheSpec.groovy

Test: Internal cache destination config

---

src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/Bidder.groovy
src/test/groovy/org/prebid/server/functional/tests/TargetingSpec.groovy

Fix flaky functional test

---

extra/bundle/pom.xml
extra/modules/confiant-ad-quality/pom.xml
extra/modules/fiftyone-devicedetection/pom.xml
extra/modules/greenbids-real-time-data/pom.xml
extra/modules/ortb2-blocking/pom.xml
extra/modules/pb-request-correction/pom.xml
extra/modules/pb-response-correction/pom.xml
extra/modules/pb-richmedia-filter/pom.xml
extra/modules/pom.xml
extra/pom.xml
pom.xml

Prebid Server prepare release 3.27.0

---

pom.xml

mysql-connector-j and postgresql drivers moved to test scope since they're not used in core.
Investigation into CVE-2025-30706 for mysql-connector-j showed both drivers are used in test and can be removed from the release build.
Local build, unit and functional tests complete successfully.
- [Y] Are your changes following [our code style guidelines](https://github.com/prebid/prebid-server-java/blob/master/docs/developers/code-style.md)?
- [N] Are there any breaking changes in your code?
- [Y] Does your test coverage exceed 90%?
- [N] Are there any erroneous console logs, debuggers or leftover code in your changes?

Housekeeping: Move DB drivers to test scope

---

src/main/java/org/prebid/server/bidder/gumgum/GumgumBidder.java
src/test/java/org/prebid/server/bidder/gumgum/GumgumBidderTest.java

GumGum: Collect the ad unit name for reporting

---

docs/config-app.md
src/main/java/org/prebid/server/spring/config/VertxConfiguration.java
src/main/resources/application.yaml

Added new property to enable round-robin inet address selection of the ip address to use.
This change will add new toggle to control ip address selection to not hit same ip and evenly distribute load.
Doesn't need tests since its just vertx library feature toggle.

Core: Add toggle to enable round-robin inet address selection of the ip address to use 

---

src/test/groovy/org/prebid/server/functional/testcontainers/container/NetworkServiceContainer.groovy
src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/HttpSettings.groovy
src/test/groovy/org/prebid/server/functional/tests/HttpSettingsSpec.groovy

Tests: RFC 3986 compatibility as optional for HttpApplicationSettings

---

src/main/java/org/prebid/server/bidder/zentotem/ZentotemBidder.java
src/main/java/org/prebid/server/spring/config/bidder/ZentotemConfiguration.java
src/main/resources/bidder-config/zentotem.yaml
src/main/resources/static/bidder-params/zentotem.json
src/test/java/org/prebid/server/bidder/zentotem/ZentotemBidderTest.java
src/test/java/org/prebid/server/it/ZentotemTest.java
src/test/resources/org/prebid/server/it/openrtb2/zentotem/test-auction-zentotem-request.json
src/test/resources/org/prebid/server/it/openrtb2/zentotem/test-auction-zentotem-response.json
src/test/resources/org/prebid/server/it/openrtb2/zentotem/test-zentotem-bid-request.json
src/test/resources/org/prebid/server/it/openrtb2/zentotem/test-zentotem-bid-response.json
src/test/resources/org/prebid/server/it/test-application.properties

New Zentotem Adapter

---

src/main/java/org/prebid/server/bidder/stroeercore/StroeerCoreBidder.java
src/main/java/org/prebid/server/bidder/stroeercore/model/StroeerCoreBid.java
src/main/java/org/prebid/server/spring/config/bidder/StroeerCoreConfiguration.java
src/main/resources/static/bidder-params/stroeerCore.json
src/test/java/org/prebid/server/bidder/stroeercore/StroeerCoreBidderTest.java
src/test/resources/org/prebid/server/it/openrtb2/stroeercore/test-auction-stroeercore-response.json
src/test/resources/org/prebid/server/it/openrtb2/stroeercore/test-stroeercore-bid-response.json

Stroeercore Adapter: Add adomain to bids

---

src/main/java/org/prebid/server/bidder/pubmatic/PubmaticBidder.java
src/main/java/org/prebid/server/bidder/pubmatic/model/response/PubmaticBidExt.java
src/test/java/org/prebid/server/bidder/pubmatic/PubmaticBidderTest.java
src/test/resources/org/prebid/server/it/openrtb2/pubmatic/test-auction-pubmatic-response.json
src/test/resources/org/prebid/server/it/openrtb2/pubmatic/test-pubmatic-bid-response.json

Pubmatic Adapter: Set bid.meta.mediaType=video when bid.ext.ibv=true

---

src/main/java/org/prebid/server/bidder/nexx360/Nexx360Bidder.java
src/main/java/org/prebid/server/bidder/nexx360/Nexx360ExtBid.java
src/main/java/org/prebid/server/bidder/nexx360/Nexx360ExtRequest.java
src/main/java/org/prebid/server/bidder/nexx360/Nexx360ExtRequestCaller.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/nexx360/ExtImpNexx360.java
src/main/java/org/prebid/server/spring/config/bidder/Nexx360Configuration.java
src/main/resources/bidder-config/nexx360.yaml
src/main/resources/static/bidder-params/nexx360.json
src/test/java/org/prebid/server/bidder/nexx360/Nexx360BidderTest.java
src/test/java/org/prebid/server/it/EasybidTest.java
src/test/java/org/prebid/server/it/Nexx360Test.java
src/test/java/org/prebid/server/it/OneAccordTest.java
src/test/java/org/prebid/server/it/PrismaSspTest.java
src/test/resources/org/prebid/server/it/openrtb2/easybid/test-auction-easybid-request.json
src/test/resources/org/prebid/server/it/openrtb2/easybid/test-auction-easybid-response.json
src/test/resources/org/prebid/server/it/openrtb2/easybid/test-easybid-bid-request.json
src/test/resources/org/prebid/server/it/openrtb2/easybid/test-easybid-bid-response.json
src/test/resources/org/prebid/server/it/openrtb2/nexx360/test-auction-nexx360-request.json
src/test/resources/org/prebid/server/it/openrtb2/nexx360/test-auction-nexx360-response.json
src/test/resources/org/prebid/server/it/openrtb2/nexx360/test-nexx360-bid-request.json
src/test/resources/org/prebid/server/it/openrtb2/nexx360/test-nexx360-bid-response.json
src/test/resources/org/prebid/server/it/openrtb2/oneaccord/test-1accord-bid-request.json
src/test/resources/org/prebid/server/it/openrtb2/oneaccord/test-1accord-bid-response.json
src/test/resources/org/prebid/server/it/openrtb2/oneaccord/test-auction-1accord-request.json
src/test/resources/org/prebid/server/it/openrtb2/oneaccord/test-auction-1accord-response.json
src/test/resources/org/prebid/server/it/openrtb2/prismassp/test-auction-prismassp-request.json
src/test/resources/org/prebid/server/it/openrtb2/prismassp/test-auction-prismassp-response.json
src/test/resources/org/prebid/server/it/openrtb2/prismassp/test-prismassp-bid-request.json
src/test/resources/org/prebid/server/it/openrtb2/prismassp/test-prismassp-bid-response.json
src/test/resources/org/prebid/server/it/test-application.properties

New Nexx360 Adapter

---

src/main/java/org/prebid/server/bidder/madsense/MadsenseBidder.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/madsense/ExtImpMadsense.java
src/main/java/org/prebid/server/spring/config/bidder/MadsenseConfiguration.java
src/main/resources/bidder-config/madsense.yaml
src/main/resources/static/bidder-params/madsense.json
src/test/java/org/prebid/server/bidder/madsense/MadsenseBidderTest.java
src/test/java/org/prebid/server/it/MadsenseTest.java
src/test/resources/org/prebid/server/it/openrtb2/madsense/test-auction-madsense-request.json
src/test/resources/org/prebid/server/it/openrtb2/madsense/test-auction-madsense-response.json
src/test/resources/org/prebid/server/it/openrtb2/madsense/test-madsense-bid-request.json
src/test/resources/org/prebid/server/it/openrtb2/madsense/test-madsense-bid-response.json
src/test/resources/org/prebid/server/it/test-application.properties

New Madsense Adapter

---

src/main/java/org/prebid/server/bidder/tappx/TappxBidder.java
src/test/java/org/prebid/server/bidder/tappx/TappxBidderTest.java
src/test/resources/org/prebid/server/it/openrtb2/tappx/test-auction-tappx-request.json
src/test/resources/org/prebid/server/it/openrtb2/tappx/test-tappx-bid-request.json

Tappx Adapter: Add GPID support

---

src/main/java/org/prebid/server/bidder/minutemedia/MinuteMediaBidder.java
src/main/java/org/prebid/server/spring/config/bidder/MinuteMediaConfiguration.java
src/main/resources/bidder-config/minutemedia.yaml
src/test/java/org/prebid/server/bidder/minutemedia/MinuteMediaBidderTest.java
src/test/resources/org/prebid/server/it/test-application.properties

MinuteMedia Adapter: Add test endpoint

---

src/main/java/org/prebid/server/bidder/connatix/ConnatixBidder.java
src/test/java/org/prebid/server/bidder/connatix/ConnatixBidderTest.java
src/test/resources/org/prebid/server/it/openrtb2/connatix/test-banner-auction-connatix-request.json
src/test/resources/org/prebid/server/it/openrtb2/connatix/test-banner-connatix-bid-request.json

We are adding support for GPID. The changes consist of reading the gpid in imp[i].ext and setting it in the outgoing bid request in the same location
required to support GPID
unit test added

Connatix Bidder Adapter: support GPID

---

src/main/java/org/prebid/server/bidder/thetradedesk/TheTradeDeskBidder.java
src/test/java/org/prebid/server/bidder/thetradedesk/TheTradeDeskBidderTest.java

TheTradeDesk adapter should resolve burl if not resolved

---

src/main/java/org/prebid/server/bidder/pubmatic/PubmaticBidder.java
src/main/java/org/prebid/server/bidder/pubmatic/model/request/PubmaticMarketplace.java
src/test/java/org/prebid/server/bidder/pubmatic/PubmaticBidderTest.java

Pubmatic: Support Alternate Bidder Codes

---

src/main/resources/metrics-config/prometheus-labels.yaml

A new metric was added, but the prometheus labels were missing
A new metric was added ( activity ) without adding a prometheus match rule
Prometheus labels work as expected
We run it in production already

add activity metric to prometheus-labels.yaml

---

src/main/java/org/prebid/server/bidder/smartadserver/SmartadserverBidder.java
src/main/java/org/prebid/server/proto/openrtb/ext/request/smartadserver/ExtImpSmartadserver.java
src/main/java/org/prebid/server/spring/config/bidder/SmartadserverConfiguration.java
src/main/resources/bidder-config/smartadserver.yaml
src/test/java/org/prebid/server/bidder/smartadserver/SmartadserverBidderTest.java
src/test/java/org/prebid/server/it/SmartadserverTest.java
src/test/resources/org/prebid/server/it/openrtb2/smartadserver/test-auction-smartadserver-request.json
src/test/resources/org/prebid/server/it/openrtb2/smartadserver/test-smartadserver-bid-request.json
src/test/resources/org/prebid/server/it/test-application.properties

Smartadserver: Add second endpoint for programmatic guaranteed

---

src/test/groovy/org/prebid/server/functional/model/request/auction/IxDiag.groovy
src/test/groovy/org/prebid/server/functional/util/PBSUtils.groovy

Fix issue with invalid functional tests

---

src/main/java/org/prebid/server/auction/externalortb/ProfilesProcessor.java
src/main/java/org/prebid/server/settings/DatabaseApplicationSettings.java
src/main/java/org/prebid/server/settings/FileApplicationSettings.java
src/main/java/org/prebid/server/spring/config/SettingsConfiguration.java
src/test/groovy/org/prebid/server/functional/model/request/auction/Banner.groovy
src/test/groovy/org/prebid/server/functional/model/request/auction/Format.groovy
src/test/groovy/org/prebid/server/functional/model/request/auction/Video.groovy
src/test/groovy/org/prebid/server/functional/model/response/auction/Bid.groovy
src/test/groovy/org/prebid/server/functional/testcontainers/PbsConfig.groovy
src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/Bidder.groovy
src/test/groovy/org/prebid/server/functional/tests/AmpSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/BidderFormatSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/ProfileSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/SeatNonBidSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsRulesSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/storage/AmpS3Spec.groovy

Profile: Fix NPE. Make DB config optional.

---

src/main/resources/bidder-config/connatix.yaml

Adds macros for GPP
equivalent in Go: https://github.com/prebid/prebid-server/pull/4525

Connatix Bid Adapter: adds GPP macros

---

src/main/java/org/prebid/server/bidder/thirtythreeacross/ThirtyThreeAcrossBidder.java
src/main/resources/bidder-config/thirtythreeacross.yaml
src/main/resources/static/bidder-params/thirtythreeacross.json
src/test/java/org/prebid/server/bidder/thirtythreeacross/ThirtyThreeAcrossBidderTest.java

Bring this adapter up-to-date with recent changes that have been done in the PBS Go Adapter and PBJS Adapter.
- Remove default values for the deprecated attribute video.placement
- Add missing GPP and GPP_SID params to the user sync request
- Allow config option "zoneId" to be used as a replacement for siteId.
Adapter needed an update and it's not reflecting important data that we need such as GPP parameters.
Specs coverage and QA applied.

33across: adapter maintenance

---

sample/configs/localdev-config.yaml
sample/profiles/README.md
sample/requests/localdev-test-request.http
sample/requests/localdev-test-stored-auction-response.http
sample/requests/localdev-test-stored-bidder-response.http
sample/stored/sample-stored-auction-response.json
sample/stored/sample-stored-bidder-response.json

Request examples that should help in Prebid Server development. The examples should be self-explanatory

Documentation: Local dev request examples

---

src/test/groovy/org/prebid/server/functional/tests/TargetingSpec.groovy

Test: Fix default value of targeting.hb_pb

---

src/test/groovy/org/prebid/server/functional/model/response/auction/ErrorType.groovy
src/test/groovy/org/prebid/server/functional/tests/ImpRequestSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/privacy/GdprSetUidSpec.groovy

Test: Bidder Specific Imp Level Params Should Apply to a Specific Alias

---

src/test/groovy/org/prebid/server/functional/testcontainers/PbsConfig.groovy
src/test/groovy/org/prebid/server/functional/testcontainers/container/PrebidServerContainer.groovy
src/test/groovy/org/prebid/server/functional/tests/CacheSpec.groovy
src/test/groovy/org/prebid/server/functional/tests/TargetingSpec.groovy

Test: Add a warning for when targeting attributes are truncated

---

extra/modules/live-intent-omni-channel-identity/src/main/java/org/prebid/server/hooks/modules/liveintent/omni/channel/identity/config/LiveIntentOmniChannelIdentityConfiguration.java
extra/modules/live-intent-omni-channel-identity/src/main/java/org/prebid/server/hooks/modules/liveintent/omni/channel/identity/v1/hooks/LiveIntentOmniChannelIdentityProcessedAuctionRequestHook.java
extra/modules/live-intent-omni-channel-identity/src/test/java/org/prebid/server/hooks/modules/liveintent/omni/channel/identity/v1/LiveIntentOmniChannelIdentityProcessedAuctionRequestHookTest.java

Respecting activity restriction when enriching bid request from LiveIntent

LiveIntent module: Restrict LI enrichment based on allowed activity
