- docs/differenceBetweenPBSGo-and-Java.md
> Document differences between PBSGo and PBS-Java

- src/main/resources/static/bidder-params/rubicon.json
This valid openrtb request fails with a data type error:
```
{
"id": "7b3e93dc-10cc-42cd-b855-76ddea2e3f7d",
"source": {
"tid": "7b3e93dc-10cc-42cd-b855-76ddea2e3f7d"
},
"tmax": 1000,
"imp": [
{
"id": "test-div",
"ext": {
"rubicon": {
"accountId": 1001,
"siteId": 113932,
"zoneId": 535510,
"inventory": {
"rating": [
"5-star"
],
"prodtype": [
"tech",
"mobile"
]
},
"visitor": {
"ucat": [
"new"
],
"search": [
"iphone"
]
}
}
},
"secure": 0,
"banner": {
"format": [
{
"w": 300,
"h": 250
},
{
"w": 300,
"h": 600
}
]
}
}
],
"test": 1,
"site": {
"publisher": {
"id": "1001"
},
"page": "http://localhost/prebid_server_test_1001_gdpr.html"
},
"user": {
"ext": {
"digitrust": {
"id": "B+pL2o/72Ece/VNhE1FjdK1hDI99YIQ5DAN/BQTjdgWKiqKIkh49YTC4jJnwuXXxC9Chg036stdDBpJujn0z9pt4D4xEwgtoJQof6vUD5NGZdA8m4k+bb6NeJlo …
```
> Rubicon adapter: fix inventory/visitor data type

- docs/developers/add-new-bidder.md
- src/main/java/org/prebid/server/bidder/adform/AdformAdapter.java
- src/main/java/org/prebid/server/bidder/adform/AdformBidder.java
- src/main/java/org/prebid/server/bidder/adform/AdformHttpUtil.java
- src/main/java/org/prebid/server/bidder/adform/model/AdformBid.java
- src/main/java/org/prebid/server/bidder/adform/model/AdformParams.java
- src/main/java/org/prebid/server/bidder/adform/model/UrlParameters.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/adform/ExtImpAdform.java
- src/main/java/org/prebid/server/validation/ResponseBidValidator.java
- src/main/resources/static/bidder-params/adform.json
- src/test/java/org/prebid/server/bidder/adform/AdformAdapterTest.java
- src/test/java/org/prebid/server/bidder/adform/AdformBidderTest.java
- src/test/java/org/prebid/server/bidder/adform/AdformHttpUtilTest.java
- src/test/java/org/prebid/server/validation/BidderParamValidatorTest.java
- src/test/java/org/prebid/server/validation/ResponseBidValidatorTest.java
- src/test/resources/org/prebid/server/ApplicationTest/auction/test-adform-bid-response-1.json
- src/test/resources/org/prebid/server/ApplicationTest/auction/test-auction-request.json
- src/test/resources/org/prebid/server/ApplicationTest/auction/test-auction-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/test-adform-bid-response-1.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/test-auction-request.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/test-auction-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/test-cache-request.json
- src/test/resources/org/prebid/server/ApplicationTest/params/test-bidder-params-schemas.json
- Add crid and priceType support for Adform adapter.
- Fixed media type for adform adapter response.
> Made crid required request field.

- docs/config-app.md
- src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
- src/main/java/org/prebid/server/spring/config/WebConfiguration.java
- src/main/resources/application.yaml
Merged geolocation.cookie-sync-enabled and geolocation.openrtb2-auctions-enabled configuration properties into one gdpr.geolocation.enabled
> Merged geolocation configuration properties

- docs/config-app.md
- src/main/java/org/prebid/server/auction/ExchangeService.java
- src/main/java/org/prebid/server/gdpr/GdprService.java
- src/main/java/org/prebid/server/geolocation/GeoLocationService.java
- src/main/java/org/prebid/server/handler/SetuidHandler.java
- src/main/java/org/prebid/server/spring/config/WebConfiguration.java
- src/main/resources/application.yaml
- src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
- src/test/java/org/prebid/server/gdpr/GdprServiceTest.java
- src/test/java/org/prebid/server/handler/SetuidHandlerTest.java
Because geo location is asynchronous call it should support timeout.
> Added timeout to geo location service interface

- docs/config-app.md
- src/main/java/org/prebid/server/auction/PreBidRequestContextFactory.java
- src/main/java/org/prebid/server/handler/openrtb2/AuctionHandler.java
- src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
- src/main/java/org/prebid/server/spring/config/WebConfiguration.java
- src/main/resources/application.yaml
- src/test/java/org/prebid/server/auction/PreBidRequestContextFactoryTest.java
- src/test/java/org/prebid/server/handler/openrtb2/AuctionHandlerTest.java
Added max timeout to auction requests.
> Reworked auction timeouts

- src/main/java/org/prebid/server/bidder/sovrn/SovrnBidder.java
- src/test/java/org/prebid/server/bidder/sovrn/SovrnBidderTest.java
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/test-auction-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/test-cache-request.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/test-sovrn-bid-response-1.json
Added decoding of URL in adm bid response field.
> Make unescaping bid.adm for Sovrn bidder

- src/main/java/org/prebid/server/bidder/pubmatic/PubmaticAdapter.java
- src/test/java/org/prebid/server/bidder/pubmatic/PubmaticAdapterTest.java
added check for cookies to be not null
> Fix pubmatic adapter NullPointerException if request.app presents

- src/main/java/org/prebid/server/bidder/HttpAdapterConnector.java
- src/main/java/org/prebid/server/gdpr/GdprUtils.java
- src/main/java/org/prebid/server/handler/AuctionHandler.java
- src/main/java/org/prebid/server/handler/CookieSyncHandler.java
- src/main/java/org/prebid/server/proto/response/BidderStatus.java
- src/main/java/org/prebid/server/spring/config/WebConfiguration.java
- src/test/java/org/prebid/server/gdpr/GdprUtilsTest.java
- src/test/java/org/prebid/server/handler/AuctionHandlerTest.java
Erase UsersyncInfo for GDPR restricted bidders
> Made legacy auction endpoint gdpr aware

- src/main/java/org/prebid/server/auction/ExchangeService.java
- src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
$.user.geo.lat and $.user.geo.lon are rounded off along with $.device.geo attributes
> User geo rounded along with device geo

- src/main/java/com/iab/openrtb/response/Bid.java
- src/main/java/org/prebid/server/auction/AmpRequestFactory.java
- src/main/java/org/prebid/server/auction/ExchangeService.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtRequestPrebidCacheBids.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtRequestPrebidCacheVastxml.java
- src/test/java/org/prebid/server/auction/AmpRequestFactoryTest.java
- src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
added new param - ext.prebid.cache.{vastXml,bids}.returnCreative
it suppresses adm of request if false
> Added new cache param - returnCreative

- src/main/java/org/prebid/server/settings/HttpApplicationSettings.java
- src/test/java/org/prebid/server/settings/HttpApplicationSettingsTest.java
Enhanced the API used by the http application for stored request fetching
> Enhanced http application settings API

- src/main/java/org/prebid/server/auction/AuctionRequestFactory.java
- src/main/java/org/prebid/server/auction/ExchangeService.java
- src/main/java/org/prebid/server/gdpr/GdprService.java
- src/main/java/org/prebid/server/gdpr/vendorlist/VendorListService.java
- src/main/java/org/prebid/server/gdpr/vendorlist/proto/Vendor.java
- src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
- src/test/java/org/prebid/server/gdpr/GdprServiceTest.java
- src/test/java/org/prebid/server/gdpr/vendorlist/VendorListServiceTest.java
Revised GDPR vendor purposes handling
> Revised GDPR vendor purposes handling

- src/main/java/org/prebid/server/bidder/adkerneladn/AdkernelAdnBidder.java
- src/main/java/org/prebid/server/bidder/adkerneladn/AdkernelAdnMetaInfo.java
- src/main/java/org/prebid/server/bidder/adkerneladn/AdkernelAdnUsersyncer.java
- src/main/java/org/prebid/server/gdpr/GdprService.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/adkerneladn/ExtImpAdkernelAdn.java
- src/main/java/org/prebid/server/spring/config/bidder/AdkernelAdnConfiguration.java
- src/main/resources/application.yaml
- src/main/resources/static/bidder-params/adkernelAdn.json
- src/test/java/org/prebid/server/ApplicationTest.java
- src/test/java/org/prebid/server/bidder/adkerneladn/AdkernelAdnBidderTest.java
- src/test/java/org/prebid/server/bidder/adkerneladn/AdkernelAdnUsersyncerTest.java
- src/test/java/org/prebid/server/bidder/brightroll/BrightrollUsersyncerTest.java
- src/test/java/org/prebid/server/validation/RequestValidatorTest.java
- src/test/resources/org/prebid/server/ApplicationTest/info-bidders/test-info-bidders-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/test-adkerneladn-bid-request-1.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/test-adkerneladn-bid-request-2.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/test-adkerneladn-bid-response-1.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/test-adkerneladn-bid-response-2.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/test-auction-request.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/test-auction-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/test-cache-request.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/test-cache-response.json
- src/test/resources/org/prebid/server/ApplicationTest/params/test-bidder-params-schemas.json
- src/test/resources/org/prebid/server/ApplicationTest/test-application.properties
> Add AdkernelAdn bidder

- docs/config-app.md
- src/main/java/org/prebid/server/spring/config/WebConfiguration.java
- src/main/resources/application.yaml
https://github.com/rubicon-project/prebid-server-java/issues/180
> TLS/SSL Support

- src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/test-auction-response.json
> Fix tests broken by merging new features

- README.md
- docs/config-app.md
https://github.com/rubicon-project/prebid-server-java/issues/186
> add cache.path to docs and minimal config

- src/main/java/org/prebid/server/bidder/brightroll/BrightrollBidder.java
- src/test/java/org/prebid/server/bidder/brightroll/BrightrollBidderTest.java
- Updated Brightroll bidder to set default auction type to first price
- Corrected unit tests to reflect the change.
> Brightroll bidder Update

- src/main/java/org/prebid/server/handler/SetuidHandler.java
- src/test/java/org/prebid/server/handler/SetuidHandlerTest.java
Added checking for `InvalidRequestException` if GDPR fails.
> Fix null pointer exception in SetuidHandler

- src/main/java/org/prebid/server/spring/config/SettingsConfiguration.java
Updated DB driver options:
- **postgres** - `ssl=false&socketTimeout=1&tcpKeepAlive=true`
- **mysql** - `useSSL=false&socketTimeout=1000&tcpKeepAlive=true`
> Fix DB connection issue on TCP layer

- src/main/java/org/prebid/server/bidder/appnexus/AppnexusAdapter.java
- src/main/java/org/prebid/server/bidder/conversant/ConversantAdapter.java
- src/main/java/org/prebid/server/bidder/facebook/FacebookAdapter.java
- src/main/java/org/prebid/server/bidder/ix/IxAdapter.java
- src/main/java/org/prebid/server/bidder/lifestreet/LifestreetAdapter.java
- src/main/java/org/prebid/server/bidder/pubmatic/PubmaticAdapter.java
- src/main/java/org/prebid/server/bidder/pulsepoint/PulsepointAdapter.java
- src/main/java/org/prebid/server/bidder/rubicon/RubiconAdapter.java
- src/main/java/org/prebid/server/bidder/sovrn/SovrnAdapter.java
- src/test/java/org/prebid/server/bidder/appnexus/AppnexusAdapterTest.java
- src/test/java/org/prebid/server/bidder/conversant/ConversantAdapterTest.java
- src/test/java/org/prebid/server/bidder/facebook/FacebookAdapterTest.java
- src/test/java/org/prebid/server/bidder/ix/IxAdapterTest.java
- src/test/java/org/prebid/server/bidder/lifestreet/LifestreetAdapterTest.java
- src/test/java/org/prebid/server/bidder/pubmatic/PubmaticAdapterTest.java
- src/test/java/org/prebid/server/bidder/rubicon/RubiconAdapterTest.java
- Updated legacy auctions to support multiformat impressions,
- Corrected unit tests.
> Update legacy auctions to support multi-format impressions

- src/main/java/org/prebid/server/auction/ExchangeService.java
- src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
Fixed an issue when the absent publisher.id was causing NPE
> Fix absent publisher.id causing NPE

- src/main/java/org/prebid/server/auction/ExchangeService.java
- src/main/java/org/prebid/server/proto/openrtb/ext/response/ExtBidResponse.java
- src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
- src/test/java/org/prebid/server/handler/openrtb2/AmpHandlerTest.java
- src/test/resources/org/prebid/server/ApplicationTest/cache/update/test-auction-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/adform/test-auction-adform-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/adkerneladn/test-auction-adkerneladn-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/adtelligent/test-auction-adtelligent-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/beachfront/test-auction-beachfront-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/brightroll/test-auction-brightroll-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/conversant/alias/test-auction-conversant-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/conversant/test-auction-conversant-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/eplanning/test-auction-eplanning-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/facebook/test-auction-facebook-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/ix/test-auction-ix-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/lifestreet/test-auction-lifestreet-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/openx/test-auction-openx-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/pubmatic/test-auction-pubmatic-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/pulsepoint/test-auction-pulsepoint-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/rhythmone/test-auction-rhythmone-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/rubicon_appnexus/test-auction-rubicon-appnexus-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/somoaudience/test-auction-somoaudience-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/sovrn/test-auction-sovrn-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/ttx/test-auction-ttx-response.json
- Added request.tmax as a tmaxrequest field to bid response extension,
- Corrected bidders' tests.
> Add a tmaxrequest field to bid response extension

- src/main/java/org/prebid/server/validation/RequestValidator.java
- src/test/java/org/prebid/server/validation/RequestValidatorTest.java
- Fixed banner width and height allowing negative or zero values;
- Added necessary test cases.
> Fixed banner width and height allowing negative or zero values

- src/main/java/org/prebid/server/bidder/rubicon/RubiconSize.java
Added Rubicon 320x240 size (ID:108)
> Add Rubicon 320x240 size (ID:108)

- src/main/resources/bidder-config/brightroll.yaml
Updated Brightroll bidder configuration usersync URL
> Update Brightroll bidder configuration usersync url

- src/main/java/org/prebid/server/cookie/UidsCookieService.java
Added an explicit path on the cookies
> Add an explicit path on the cookies

- src/main/resources/application.yaml
- src/test/java/org/prebid/server/auction/CurrencyConversionServiceTest.java
Updated default currency rates URL
> Updated default currency rates URL

- docs/config-app.md
- src/main/java/org/prebid/server/settings/JdbcApplicationSettings.java
- src/main/java/org/prebid/server/settings/mapper/JdbcStoredDataResultMapper.java
- src/main/java/org/prebid/server/settings/service/HttpPeriodicRefreshService.java
- src/main/java/org/prebid/server/settings/service/JdbcPeriodicRefreshService.java
- src/main/java/org/prebid/server/spring/config/InitializationConfiguration.java
- src/main/java/org/prebid/server/spring/config/SettingsConfiguration.java
- src/main/java/org/prebid/server/vertx/jdbc/BasicJdbcClient.java
- src/main/java/org/prebid/server/vertx/jdbc/CircuitBreakerSecuredJdbcClient.java
- src/main/java/org/prebid/server/vertx/jdbc/JdbcClient.java
- src/test/java/org/prebid/server/settings/JdbcApplicationSettingsTest.java
- src/test/java/org/prebid/server/settings/mapper/JdbcStoredDataResultMapperTest.java
- src/test/java/org/prebid/server/settings/service/HttpPeriodicRefreshServiceTest.java
- src/test/java/org/prebid/server/settings/service/JdbcPeriodicRefreshServiceTest.java
- Added Database polling for stored request cache;
- Minor code fixes and adjustments.
> Add database polling for stored request cache

- src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
Hot-fix error with incorrect path for geolocation archive causing failure to load AppContext
> Fix error with incorrect resource classpath for geolocation

- src/main/java/org/prebid/server/bidder/beachfront/BeachfrontBidder.java
- src/main/java/org/prebid/server/bidder/beachfront/BeachfrontUsersyncer.java
- src/main/java/org/prebid/server/spring/config/bidder/BeachfrontConfiguration.java
- src/main/resources/bidder-config/beachfront.yaml
- src/test/java/org/prebid/server/bidder/beachfront/BeachfrontBidderTest.java
- src/test/java/org/prebid/server/bidder/beachfront/BeachfrontUsersyncerTest.java
- Updated Beachfron bidder configuration, version and usersyncer;
- Updated related tests to reflect changes.
> Update Beachfront bidder version, usersync url and related tests

- checkstyle.xml
- src/main/java/com/iab/openrtb/response/BidResponse.java
- src/main/java/org/prebid/server/spring/env/YamlPropertySourceFactory.java
Added [NeedBraces](http://checkstyle.sourceforge.net/config_blocks.html#NeedBraces) checkstyle rule.
> Add NeedBraces checkstyle rule

- src/main/java/org/prebid/server/spring/config/bidder/PubmaticConfiguration.java
> Fix Pubmatic Usersyncer

- docs/build.md
- docs/code-reviews.md
- docs/contributing.md
- docs/endpoints/auction.md
- docs/endpoints/info/bidders/bidderName.md
- docs/endpoints/openrtb2/auction.md
> Fix outdated URLs in documentation

- src/main/java/org/prebid/server/auction/AmpResponsePostProcessor.java
- src/main/java/org/prebid/server/handler/openrtb2/AmpHandler.java
> Allow wider AMP endpoint decoration

- docs/config-app.md
- src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
- src/main/resources/application.yaml
> Enable compression between pbs and bidders

- src/main/java/org/prebid/server/bidder/brightroll/BrightrollBidder.java
- src/test/java/org/prebid/server/bidder/brightroll/BrightrollBidderTest.java
- Updated Brightroll Bidder to apply changes for customized requests;
- Updated and added unit tests to reflect the changes.
> Update Brightroll bidder - add changes for customized request

- src/main/java/org/prebid/server/bidder/adform/AdformAdapter.java
- src/main/java/org/prebid/server/bidder/adform/AdformBidder.java
- src/main/java/org/prebid/server/bidder/adform/AdformHttpUtil.java
- src/main/java/org/prebid/server/bidder/adform/model/UrlParameters.java
- src/test/java/org/prebid/server/ApplicationTest.java
- src/test/java/org/prebid/server/bidder/adform/AdformAdapterTest.java
- src/test/java/org/prebid/server/bidder/adform/AdformBidderTest.java
- src/test/java/org/prebid/server/bidder/adform/AdformHttpUtilTest.java
- src/test/resources/org/prebid/server/ApplicationTest/auction/adform/test-auction-adform-response.json
- src/test/resources/org/prebid/server/ApplicationTest/openrtb2/adform/test-auction-adform-response.json
- Updated Adform adapter and bidder to pass bid request currency or default it to USD;
- Updated test cases to reflect the changes.
> Update adform bidder - pass bid request currency (default to USD)

- checkstyle.xml
- pom.xml
- Updated checkstyle version;
- Updated checkstyle configuration.
> Update checkstyle version and it's configuration

- src/main/resources/bidder-config/beachfront.yaml
- Updated BeachFront bidder banner and cookie sync endpoints.
> Update BeachFront bidder user sync endpoint

- src/main/java/org/prebid/server/proto/openrtb/ext/request/yieldmo/ExtImpYieldmo.java
- src/main/resources/static/bidder-params/yieldmo.json
- src/test/resources/org/prebid/server/it/openrtb2/yieldmo/test-auction-yieldmo-request.json
- src/test/resources/org/prebid/server/it/openrtb2/yieldmo/test-auction-yieldmo-response.json
- Updated Yieldmo bidder param placementid into placementId.
> Update Yieldmo bidder parameter

- src/main/resources/bidder-config/sonobi.yaml
- Updated Sonobi bidder endpoint
> Update Sonobi bidder endpoint url

- src/main/java/org/prebid/server/bidder/eplanning/EplanningBidder.java
- src/main/resources/bidder-config/eplanning.yaml
- src/test/java/org/prebid/server/bidder/eplanning/EplanningBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/eplanning/test-auction-eplanning-response.json
> Set eplanning's vendor-id and support empty spaces and ads in response

- src/main/java/org/prebid/server/auction/AmpRequestFactory.java
- src/main/java/org/prebid/server/auction/ExchangeService.java
- src/main/java/org/prebid/server/bidder/HttpBidderRequester.java
- src/main/java/org/prebid/server/bidder/ix/IxBidder.java
- src/main/java/org/prebid/server/validation/RequestValidator.java
CL:
- Enhanced log message for bidder error
- Fixed code smells
> Enhance log message for bidder error

- src/main/java/org/prebid/server/auction/AmpRequestFactory.java
- src/test/java/org/prebid/server/auction/AmpRequestFactoryTest.java
Fixes https://github.com/prebid/prebid-server/issues/827
> AMP multi-size param should not replace original size

- docs/config-app.md
- src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
- src/main/java/org/prebid/server/vertx/http/BasicHttpClient.java
- src/main/resources/application.yaml
- src/test/java/org/prebid/server/vertx/http/BasicHttpClientTest.java
> Allow following HTTP redirections and configure the amount

- docs/endpoints/getuids.md
- src/main/java/org/prebid/server/cookie/UidsCookie.java
- src/main/java/org/prebid/server/handler/GetuidsHandler.java
- src/main/java/org/prebid/server/spring/config/WebConfiguration.java
- src/test/java/org/prebid/server/handler/GetuidsHandlerTest.java
> Add GET /getuids endpoint

- docs/metrics.md
- src/main/java/org/prebid/server/handler/CookieSyncHandler.java
- src/main/java/org/prebid/server/metric/MetricName.java
- src/main/java/org/prebid/server/metric/Metrics.java
- src/test/java/org/prebid/server/handler/CookieSyncHandlerTest.java
- src/test/java/org/prebid/server/metric/MetricsTest.java
> Add cookie_sync.matches metrics

- src/main/java/org/prebid/server/bidder/adform/AdformAdapter.java
- src/main/java/org/prebid/server/bidder/adform/AdformBidder.java
- src/main/java/org/prebid/server/bidder/adform/AdformHttpUtil.java
- src/main/java/org/prebid/server/bidder/adform/model/UrlParameters.java
- src/test/java/org/prebid/server/bidder/adform/AdformAdapterTest.java
- src/test/java/org/prebid/server/bidder/adform/AdformBidderTest.java
- src/test/java/org/prebid/server/bidder/adform/AdformHttpUtilTest.java
- src/test/java/org/prebid/server/it/ApplicationTest.java
- Updated Adform bidder's currency support.
> Update Adform bidder's currency support

- src/main/java/org/prebid/server/handler/info/BiddersHandler.java
- src/test/java/org/prebid/server/handler/info/BiddersHandlerTest.java
- Updated GET /info/bidders to return list of active bidders only.
> Update GET /info/bidders to return active bidders only

- src/test/java/org/prebid/server/it/ApplicationTest.java
- Added a GET /getuids endpoint test to ApplicationTest.
> Add GET /getuids endpoint test in ApplicationTest

- src/main/java/org/prebid/server/handler/CookieSyncHandler.java
- src/test/java/org/prebid/server/handler/CookieSyncHandlerTest.java
> Fix cookie sync limit when there are live uids

- src/main/java/org/prebid/server/spring/config/bidder/AdformConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/AdkernelAdnConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/AdtelligentConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/AppnexusConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/BeachfrontConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/BrightrollConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/ConsumableConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/ConversantConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/EplanningConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/FacebookConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/GamoshiConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/GridConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/GumgumConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/IxConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/LifestreetConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/OpenxConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/PubmaticConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/PulsepointConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/RhythmoneConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/RubiconConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/SomoaudienceConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/SonobiConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/SovrnConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/TtxConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/YieldmoConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/util/BidderDepsAssembler.java
- src/main/java/org/prebid/server/spring/config/bidder/util/BidderInfoCreator.java
- src/main/java/org/prebid/server/spring/config/bidder/util/UsersyncerCreator.java
- src/main/resources/bidder-config/beachfront.yaml
- Improved Bidders' java configuration classes;
- Minor code refactoring of bidder config involved classes.
> Improve bidders' java configuration classes, minor code refactoring

- src/main/resources/bidder-config/ttx.yaml
- src/test/java/org/prebid/server/it/TtxTest.java
- src/test/resources/org/prebid/server/it/openrtb2/ttx/test-ttx-bid-request-1.json
- Enabled user sync for 33across bidder - changed bidder's config and adjusted integration test.
> Enable 33across bidder user sync

- src/main/java/org/prebid/server/auction/StoredRequestProcessor.java
- src/main/java/org/prebid/server/metric/MetricName.java
- src/main/java/org/prebid/server/metric/Metrics.java
- src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
- src/test/java/org/prebid/server/auction/StoredRequestProcessorTest.java
- src/test/java/org/prebid/server/metric/MetricsTest.java
- Added metrics for stored requests and imps hits and misses.
> Add stored data metrics

- src/main/resources/bidder-config/eplanning.yaml
- Updated Eplanning bidder user sync config.
> Update Eplanning bidder user sync

- src/main/java/org/prebid/server/auction/AmpRequestFactory.java
- src/main/java/org/prebid/server/auction/AuctionRequestFactory.java
- src/main/java/org/prebid/server/auction/ExchangeService.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtMediaTypePriceGranularity.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtPriceGranularity.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtRequestTargeting.java
- src/main/java/org/prebid/server/validation/RequestValidator.java
- src/test/java/org/prebid/server/auction/AmpRequestFactoryTest.java
- src/test/java/org/prebid/server/auction/AuctionRequestFactoryTest.java
- src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
- src/test/java/org/prebid/server/validation/RequestValidatorTest.java
- Added Media Type Price Granularity support.
> Add Media Type Price Granularity implementation

- src/main/java/org/prebid/server/auction/AmpRequestFactory.java
- src/main/java/org/prebid/server/bidder/brightroll/BrightrollBidder.java
- src/main/java/org/prebid/server/bidder/consumable/model/ConsumableAdType.java
- src/main/java/org/prebid/server/bidder/ix/IxBidder.java
- src/main/java/org/prebid/server/bidder/pubmatic/PubmaticAdapter.java
- src/main/java/org/prebid/server/gdpr/GdprService.java
- src/main/java/org/prebid/server/geolocation/GeoLocationService.java
- src/main/java/org/prebid/server/settings/mapper/JdbcStoredDataResultMapper.java
- src/main/java/org/prebid/server/validation/RequestValidator.java
- src/main/java/org/prebid/server/vertx/http/HttpClient.java
- src/main/java/org/prebid/server/vertx/jdbc/JdbcClient.java
- src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
- src/test/java/org/prebid/server/bidder/brightroll/BrightrollBidderTest.java
- src/test/java/org/prebid/server/bidder/eplanning/EplanningBidderTest.java
- src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java
- src/test/java/org/prebid/server/util/HttpUtilTest.java
- src/test/java/org/prebid/server/validation/RequestValidatorTest.java
CL:
- Fixed digitrust validation in `RequestValidator`.
- Clean code smells.
> Fix NPE in RequestValidator when checking digitrust

- src/main/java/org/prebid/server/auction/AuctionRequestFactory.java
- src/main/java/org/prebid/server/bidder/adform/AdformRequestUtil.java
- src/main/java/org/prebid/server/bidder/openx/OpenxBidder.java
- src/main/java/org/prebid/server/bidder/openx/proto/OpenxImpExt.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/openx/ExtImpOpenx.java
- src/test/java/org/prebid/server/bidder/openx/OpenxBidderTest.java
- src/test/java/org/prebid/server/validation/BidderParamValidatorTest.java
- src/test/resources/org/prebid/server/it/openrtb2/openx/test-auction-openx-request.json
- src/test/resources/org/prebid/server/it/openrtb2/openx/test-auction-openx-response.json
- src/test/resources/org/prebid/server/it/openrtb2/openx/test-openx-bid-request-1.json
Map<String, String> customParams -> Map<String, JsonNode> customParams;
Rewrite tests
Add new methods in test class
- Map<String, JsonNode> stringJsonNodeMap(String key, String value)
- Map<String, JsonNode> stringJsonNodeMap(String key, List<String> values)
> Change OpenX request.customParams

- src/main/resources/bidder-config/improvedigital.yaml
- src/main/resources/static/bidder-params/improvedigital.json
ImproveDigital configuration update
> ImproveDigital configuration update

- src/main/java/org/prebid/server/auction/ExchangeService.java
- src/main/java/org/prebid/server/cache/CacheService.java
- src/main/java/org/prebid/server/events/EventsService.java
- src/main/java/org/prebid/server/gdpr/GdprService.java
- src/test/java/org/prebid/server/cache/CacheServiceTest.java
- src/test/java/org/prebid/server/events/EventsServiceTest.java
- src/test/java/org/prebid/server/gdpr/GdprServiceTest.java
There 3 places where Account is fetching:
- GdprService (enforce flag) - fallback to NULL.
- CacheService (ttls) - fallback to NULL.
- EventsService (events flag) - fallback to false.
> Refactoring missed Account handling

- src/main/resources/bidder-config/gamoshi.yaml
- Added new vendor id for gamoshi bidder
> Add new vendor id for gamoshi bidder

- src/main/java/org/prebid/server/bidder/conversant/ConversantAdapter.java
- src/main/java/org/prebid/server/bidder/conversant/ConversantBidder.java
- src/test/java/org/prebid/server/bidder/conversant/ConversantAdapterTest.java
- src/test/java/org/prebid/server/bidder/conversant/ConversantBidderTest.java
Modified Conversant adapter/bidder to set `app.id` from `ext.siteId`.
> Modify Conversant adapter/bidder to set app id from ext site id

- src/main/java/org/prebid/server/bidder/adform/AdformAdapter.java
- src/main/java/org/prebid/server/bidder/adform/AdformBidder.java
- src/main/java/org/prebid/server/bidder/adform/AdformHttpUtil.java
- src/main/java/org/prebid/server/bidder/adform/model/AdformParams.java
- src/main/java/org/prebid/server/bidder/adform/model/UrlParameters.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/adform/ExtImpAdform.java
- src/test/java/org/prebid/server/bidder/adform/AdformAdapterTest.java
- src/test/java/org/prebid/server/bidder/adform/AdformBidderTest.java
- src/test/java/org/prebid/server/bidder/adform/AdformHttpUtilTest.java
- src/test/java/org/prebid/server/validation/BidderParamValidatorTest.java
- Added key values and keywords support for Adform bidder;
- Updated unit tests to reflect the changes.
> Add keyvalues and keywords support for Adform bidder

- src/test/java/org/prebid/server/bidder/adkerneladn/AdkernelAdnBidderTest.java
- src/test/java/org/prebid/server/it/MgidTest.java
- src/test/java/org/prebid/server/it/RtbhouseTest.java
- src/test/resources/org/prebid/server/it/openrtb2/mgid/test-auction-mgid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/mgid/test-auction-mgid-response.json
- src/test/resources/org/prebid/server/it/openrtb2/mgid/test-cache-mgid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/mgid/test-mgid-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/rtbhouse/test-auction-rtbhouse-request.json
- src/test/resources/org/prebid/server/it/openrtb2/rtbhouse/test-auction-rtbhouse-response.json
- src/test/resources/org/prebid/server/it/openrtb2/rtbhouse/test-rtbhouse-bid-request-1.json
- src/test/resources/org/prebid/server/it/openrtb2/visx/test-auction-visx-request.json
- src/test/resources/org/prebid/server/it/openrtb2/visx/test-auction-visx-response.json
- src/test/resources/org/prebid/server/it/openrtb2/visx/test-cache-visx-request.json
- src/test/resources/org/prebid/server/it/openrtb2/visx/test-visx-bid-request.json
Corrected integration tests and test files for new bidders to correspond with existing practice and reflect expected auction transformations.
> Correct minor issues with integration tests for new bidders

- docs/endpoints/openrtb2/auction.md
- Added missing features' description to openrtb2/auction.md doc to be up to date with GO version.
> Add missing features' description to openrtb2/auction.md doc

- src/main/java/org/prebid/server/auction/ExchangeService.java
- src/main/java/org/prebid/server/events/EventsService.java
- src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
- src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
- src/test/java/org/prebid/server/events/EventsServiceTest.java
Refactor ExchangeService
RefactorTests
> Make EventsService to use account from AuctionContext

- docs/bidders/rubicon.md
- src/main/java/org/prebid/server/bidder/sharethrough/SharethroughBidder.java
- src/main/java/org/prebid/server/bidder/sharethrough/SharethroughRequestUtil.java
- src/test/java/org/prebid/server/bidder/sharethrough/SharethroughBidderTest.java
- src/test/java/org/prebid/server/bidder/sharethrough/SharethroughRequestUtilTest.java
- src/test/java/org/prebid/server/it/SharethroughTest.java
- src/test/resources/org/prebid/server/it/openrtb2/sharethrough/test-auction-sharethrough-request.json
- src/test/resources/org/prebid/server/it/openrtb2/sharethrough/test-auction-sharethrough-response.json
update rubicon md
update Sharethrough headers
- X-Forwarded-For depends on Device.ip
- User-Agent depends on Device.ua
- Add schema (http://) to hosts
Fix tests.
> Update Sharethrough headers

- src/main/java/org/prebid/server/auction/AuctionRequestFactory.java
- src/main/java/org/prebid/server/auction/ExchangeService.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtPublisher.java
- src/test/java/org/prebid/server/auction/AuctionRequestFactoryTest.java
- src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
- Added publisher.ext.parentAccount support;
- Updated unite tests to reflect the changes.
> Add Publisher parentAccount support

- src/main/java/org/prebid/server/auction/AmpRequestFactory.java
- src/test/java/org/prebid/server/auction/AmpRequestFactoryTest.java
- Added gdpr_consent string handling for AMP requests - the value is now copied from request's URL parameters to `bidrequest.user.ext.consent` field;
- Added unit tests to reflect the changes.
> Add gdpr_consent string handling for AMP requests

- src/main/java/org/prebid/server/handler/OptoutHandler.java
- src/main/java/org/prebid/server/handler/SetuidHandler.java
- src/main/java/org/prebid/server/util/HttpUtil.java
- src/test/java/org/prebid/server/handler/OptoutHandlerTest.java
- src/test/java/org/prebid/server/handler/SetuidHandlerTest.java
- src/test/java/org/prebid/server/util/HttpUtilTest.java
https://github.com/prebid/prebid-server/issues/900
- Added `SameSite=none` to `Set-Cookie` header.
- Implemented through Headers without vertx.Cookie.addCookie(), bc Vertx don`t have special method for that case.
> Add SameSite=none to cookie

- src/main/resources/bidder-config/improvedigital.yaml
Updated Improvedigital email address.
> Update Improvedigital email address

- src/main/resources/bidder-config/visx.yaml
Updated usersync url for VIS.X bidder.
> Update VIS.X usersync url

- src/main/java/org/prebid/server/settings/CachingApplicationSettings.java
- src/test/java/org/prebid/server/settings/CachingApplicationSettingsTest.java
Used    
`private final Map<String, PreBidException> accountNotFoundCache;`
> Cache for previously not found items

- src/main/java/org/prebid/server/auction/BidResponseCreator.java
- src/test/java/org/prebid/server/auction/BidResponseCreatorTest.java
- Fixed a gap in `BidResponseCreator` logic when `nbr` flag was not given a value when there were no bids from bidders - the response would contain no `nbr` flag but no `seatbid`s either;
- Also, refactored `BidResponseCreator#create` flow - added a short-circuit return for a case like this one;
- Corrected existing unit tests and added couple more to cover the logic changes.
> Fix nbr flag in BidResponse when no bids are present

- docs/config-app.md
- docs/endpoints/cookieSync.md
- src/main/java/org/prebid/server/handler/CookieSyncHandler.java
- src/main/java/org/prebid/server/proto/request/CookieSyncRequest.java
- src/main/java/org/prebid/server/spring/config/WebConfiguration.java
- src/main/resources/application.yaml
- src/test/java/org/prebid/server/handler/CookieSyncHandlerTest.java
- src/test/java/org/prebid/server/it/ApplicationTest.java
See  https://github.com/prebid/prebid-server/issues/924
> Cooperative cookie

- src/main/java/org/prebid/server/analytics/model/AmpEvent.java
- src/main/java/org/prebid/server/analytics/model/AuctionEvent.java
- src/main/java/org/prebid/server/handler/openrtb2/AmpHandler.java
- src/main/java/org/prebid/server/handler/openrtb2/AuctionHandler.java
- src/test/java/org/prebid/server/handler/openrtb2/AmpHandlerTest.java
- src/test/java/org/prebid/server/handler/openrtb2/AuctionHandlerTest.java
Replace BidRequest with AuctionContext.
Update tests.
> Inline AuctionContext in (Amp/Auction)Event

- src/main/java/org/prebid/server/settings/JdbcApplicationSettings.java
- src/main/java/org/prebid/server/settings/model/Account.java
- src/test/java/org/prebid/server/settings/FileApplicationSettingsTest.java
- src/test/java/org/prebid/server/settings/JdbcApplicationSettingsTest.java
- src/test/resources/org/prebid/server/it/test-app-settings.yaml
Update ApplicationSettings tests.
Update yml
> Add analyticsSamplingFactor to Account model

- docs/endpoints/cookieSync.md
- src/main/java/org/prebid/server/handler/CookieSyncHandler.java
- src/main/java/org/prebid/server/spring/config/WebConfiguration.java
- src/main/resources/application.yaml
- src/test/java/org/prebid/server/handler/CookieSyncHandlerTest.java
- src/test/java/org/prebid/server/it/ApplicationTest.java
Updated tests. 
Updated documentation. 
Enabled coop-cookie.
> Coop-cookie for all active bidders when no priorities provided.

- src/main/java/org/prebid/server/auction/BidResponseCreator.java
- src/main/java/org/prebid/server/auction/ExchangeService.java
- src/main/java/org/prebid/server/auction/TargetingKeywordsCreator.java
- src/main/java/org/prebid/server/events/EventsService.java
- src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
- src/test/java/org/prebid/server/auction/AmpRequestFactoryTest.java
- src/test/java/org/prebid/server/auction/BidResponseCreatorTest.java
- src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
- src/test/java/org/prebid/server/auction/TargetingKeywordsCreatorTest.java
- src/test/java/org/prebid/server/bidder/verizonmedia/VerizonmediaBidderTest.java
- src/test/java/org/prebid/server/events/EventsServiceTest.java
- src/test/resources/org/prebid/server/it/openrtb2/rubicon_appnexus/test-auction-rubicon-appnexus-response.json
Changed `hb_winurl` targeting key to `/event?t=win&b=BIDID&a=ACCOUNT&f=i`
> Refine hb_winurl targeting key

- docs/metrics.md
Updated `metrcis.md `document with descriptions of media type and stored requests/imps metrics.
> Update metrcis.md document with new metrics description

- docs/bidders/tappx.md
- src/main/resources/bidder-config/appnexus.yaml
- src/main/resources/bidder-config/unruly.yaml
- Added Tappx bidder doc;
- Updated Appnexus and Unruly configuration files.
> Update bidders' docs and settings

- src/main/java/org/prebid/server/auction/BidResponsePostProcessor.java
- src/main/java/org/prebid/server/auction/ExchangeService.java
- src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
Pass Account to BidResponsePostProcessor
> Pass Account to BidResponsePostProcessor

- src/main/java/org/prebid/server/auction/AuctionRequestFactory.java
- src/main/java/org/prebid/server/handler/AuctionHandler.java
- src/main/java/org/prebid/server/handler/openrtb2/AmpHandler.java
- src/main/java/org/prebid/server/handler/openrtb2/AuctionHandler.java
- src/test/java/org/prebid/server/auction/ImplicitParametersExtractorTest.java
- src/test/java/org/prebid/server/auction/PreBidRequestContextFactoryTest.java
- src/test/java/org/prebid/server/auction/StoredRequestProcessorTest.java
- src/test/java/org/prebid/server/bidder/HttpAdapterConnectorTest.java
- src/test/java/org/prebid/server/cache/CacheServiceTest.java
- src/test/java/org/prebid/server/execution/RemoteFileSyncerTest.java
- src/test/java/org/prebid/server/handler/AuctionHandlerTest.java
- src/test/java/org/prebid/server/handler/CookieSyncHandlerTest.java
- src/test/java/org/prebid/server/handler/CurrencyRatesHandlerTest.java
- src/test/java/org/prebid/server/handler/GetuidsHandlerTest.java
- src/test/java/org/prebid/server/handler/SettingsCacheNotificationHandlerTest.java
- src/test/java/org/prebid/server/handler/info/BidderDetailsHandlerTest.java
- src/test/java/org/prebid/server/handler/openrtb2/AmpHandlerTest.java
- src/test/java/org/prebid/server/handler/openrtb2/AuctionHandlerTest.java
- src/test/java/org/prebid/server/health/DatabaseHealthCheckerTest.java
- src/test/java/org/prebid/server/settings/service/HttpPeriodicRefreshServiceTest.java
- src/test/java/org/prebid/server/settings/service/JdbcPeriodicRefreshServiceTest.java
- src/test/java/org/prebid/server/vertx/http/BasicHttpClientTest.java
Fixes error:
```
java.lang.IllegalStateException: Response is closed                                                                                                                                                          
at io.vertx.core.http.impl.HttpServerResponseImpl.checkValid(HttpServerResponseImpl.java:617)                                                                                                        
at io.vertx.core.http.impl.HttpServerResponseImpl.exceptionHandler(HttpServerResponseImpl.java:259)                                                                                                  
at org.prebid.server.handler.openrtb2.AuctionHandler.handleResult(AuctionHandler.java:123) …
```
> Fix "Response is closed" exception while adding exceptionHandler

- src/main/java/org/prebid/server/spring/config/WebConfiguration.java
- src/test/java/org/prebid/server/it/ApplicationTest.java
- src/test/resources/org/prebid/server/it/vtrack/test-cache-request.json
- src/test/resources/org/prebid/server/it/vtrack/test-vtrack-request.json
- src/test/resources/org/prebid/server/it/vtrack/test-vtrack-response.json
Change `GET` to `POST`
Integration test use bidder with `isModifyingVastXmlAllowed=true`, and account with `eventsEnabled=true`
> Add integration test for /vtrack endpoint

- docs/config-app.md
- src/main/java/org/prebid/server/auction/AuctionRequestFactory.java
- src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
- src/main/resources/application.yaml
- src/test/java/org/prebid/server/auction/AuctionRequestFactoryTest.java
Added Account ID blacklist, provided through configuration property `backlisted-accts`.
> Add Account ID blacklist

- src/main/resources/bidder-config/emxdigital.yaml
Updated EMXDigital usersync endpoint.
> Update EMXDigital usersync endpoint

- src/main/resources/bidder-config/unruly.yaml
Updated Unruly bidder's usersync type to `ifmare`.
> Update Unruly bidder's usersync type

- src/main/java/org/prebid/server/bidder/grid/GridBidder.java
- src/main/resources/bidder-config/grid.yaml
- src/test/java/org/prebid/server/bidder/grid/GridBidderTest.java
Updated The MediaGrid bidder - added a support of video imp/bid type.
> Update The MediaGrid bidder to add a video support

- src/main/java/org/prebid/server/util/HttpUtil.java
- src/test/java/org/prebid/server/util/HttpUtilTest.java
Chrome flag `cookies-without-same-site-must-be-secure` process cookie only with `SameSite=None; Secure `
> Add Secure flag to SameSite cookie for

- src/main/java/org/prebid/server/bidder/pubmatic/PubmaticBidder.java
- src/test/java/org/prebid/server/bidder/pubmatic/PubmaticBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/pubmatic/test-auction-pubmatic-response.json
- src/test/resources/org/prebid/server/it/openrtb2/pubmatic/test-cache-pubmatic-request.json
- src/test/resources/org/prebid/server/it/openrtb2/pubmatic/test-pubmatic-bid-response-1.json
`bid.ext.bidType` contains int value to set the bid Type.
> Pubmatic bid type defined in bid.ext.BidType

- src/main/java/org/prebid/server/handler/SetuidHandler.java
- src/main/java/org/prebid/server/spring/config/WebConfiguration.java
- src/test/java/org/prebid/server/handler/SetuidHandlerTest.java
Added `/setuid` bidder param validation validation.
> Add /setuid bidder validation

- src/main/java/org/prebid/server/bidder/synacormedia/SynacormediaBidder.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/synacormedia/ExtImpSynacormedia.java
- src/main/java/org/prebid/server/spring/config/bidder/SynacormediaConfiguration.java
- src/main/resources/bidder-config/synacormedia.yaml
- src/main/resources/static/bidder-params/synacormedia.json
- src/test/java/org/prebid/server/bidder/synacormedia/SynacormediaBidderTest.java
- src/test/java/org/prebid/server/it/SynacormediaTest.java
- src/test/resources/org/prebid/server/it/openrtb2/synacormedia/test-auction-synacormedia-request.json
- src/test/resources/org/prebid/server/it/openrtb2/synacormedia/test-auction-synacormedia-response.json
- src/test/resources/org/prebid/server/it/openrtb2/synacormedia/test-cache-synacormedia-request.json
- src/test/resources/org/prebid/server/it/openrtb2/synacormedia/test-cache-synacormedia-response.json
- src/test/resources/org/prebid/server/it/openrtb2/synacormedia/test-synacormedia-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/synacormedia/test-synacormedia-bid-response.json
- src/test/resources/org/prebid/server/it/test-application.properties
Added Synacor Media bidder implementation, unit and integration tests.
> Add SynacorMedia bidder implementation

- src/main/java/org/prebid/server/validation/RequestValidator.java
Fixed NPE occurring when validating price granularity if media type price granularity was present in request.
> Fix NPE occurring when validating price granularity

- src/main/resources/static/bidder-params/rubicon.json
Updated static parameters for Rubicon bidder.
> Update Rubicon static params

- src/main/resources/bidder-config/triplelift.yaml
Added config for TripleLift bidder usersync redirect.
> Allow usersync redirect for TripleLift bidder

- src/main/java/com/iab/openrtb/request/Asset.java
- src/main/java/com/iab/openrtb/response/Asset.java
- src/main/java/com/iab/openrtb/response/DataObject.java
- src/main/java/com/iab/openrtb/response/EventTracker.java
- src/main/java/com/iab/openrtb/response/ImageObject.java
- src/main/java/com/iab/openrtb/response/Link.java
- src/main/java/com/iab/openrtb/response/Response.java
- src/main/java/com/iab/openrtb/response/TitleObject.java
- src/main/java/com/iab/openrtb/response/VideoObject.java
- src/main/java/org/prebid/server/auction/BidResponseCreator.java
- src/test/java/org/prebid/server/auction/BidResponseCreatorTest.java
- Added updating type for native bid adm markup;
- Added necessary OpenRTB Native models.
> Add type for native bid adm markup

- docs/metrics.md
- src/main/java/org/prebid/server/cache/CacheService.java
- src/main/java/org/prebid/server/metric/MetricName.java
- src/main/java/org/prebid/server/metric/Metrics.java
- src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
- src/test/java/org/prebid/server/cache/CacheServiceTest.java
- src/test/java/org/prebid/server/metric/MetricsTest.java
`prebid_cache_request_success_time` `prebid_cache_request_error_time`
Tracks cacheService request time.
> Add cache request metrics

- src/main/java/org/prebid/server/bidder/sharethrough/SharethroughBidder.java
- src/main/java/org/prebid/server/bidder/sharethrough/model/SharethroughRequestBody.java
- src/main/java/org/prebid/server/bidder/sharethrough/model/StrUriParameters.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/sharethrough/ExtImpSharethrough.java
- src/main/resources/static/bidder-params/sharethrough.json
- src/test/java/org/prebid/server/bidder/sharethrough/SharethroughBidderTest.java
- src/test/java/org/prebid/server/bidder/sharethrough/SharethroughRequestUtilTest.java
- src/test/java/org/prebid/server/it/SharethroughTest.java
- src/test/resources/org/prebid/server/it/openrtb2/sharethrough/test-auction-sharethrough-request.json
- src/test/resources/org/prebid/server/it/openrtb2/sharethrough/test-auction-sharethrough-response.json
- src/test/resources/org/prebid/server/it/openrtb2/sharethrough/test-sharethrough-request.json
- Updated Sharethrough bidder to version 7;
- Updated unit and integration tests to reflect the changes.
> Update Sharethrough bidder to version 7

- src/test/resources/org/prebid/server/it/openrtb2/sharethrough/test-auction-sharethrough-response.json
The `{{ DEADLINE_FORMATTED_TIME }}` placeholder is used for time placeholder.
> Fix SharethroughTest to use placeholder for local environment time

- src/main/java/org/prebid/server/bidder/datablocks/DatablocksBidder.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/datablocks/ExtImpDatablocks.java
- src/main/java/org/prebid/server/spring/config/bidder/DatablocksConfiguration.java
- src/main/resources/bidder-config/datablocks.yaml
- src/main/resources/static/bidder-params/datablocks.json
- src/test/java/org/prebid/server/bidder/datablocks/DatablocksBidderTest.java
- src/test/java/org/prebid/server/it/DatablocksTest.java
- src/test/resources/org/prebid/server/it/openrtb2/datablocks/test-auction-datablocks-request.json
- src/test/resources/org/prebid/server/it/openrtb2/datablocks/test-auction-datablocks-response.json
- src/test/resources/org/prebid/server/it/openrtb2/datablocks/test-cache-datablocks-request.json
- src/test/resources/org/prebid/server/it/openrtb2/datablocks/test-cache-datablocks-response.json
- src/test/resources/org/prebid/server/it/openrtb2/datablocks/test-datablocks-bid-request-1.json
- src/test/resources/org/prebid/server/it/openrtb2/datablocks/test-datablocks-bid-request-2.json
- src/test/resources/org/prebid/server/it/openrtb2/datablocks/test-datablocks-bid-response-1.json
- src/test/resources/org/prebid/server/it/openrtb2/datablocks/test-datablocks-bid-response-2.json
- src/test/resources/org/prebid/server/it/test-application.properties
Added Datablocks bidder implementation, unit and integration tests.
Upd: added a usersync url update.
> Add Datablocks bidder implementation

- src/main/resources/bidder-config/synacormedia.yaml
Updated Synacormedia bidder user sync url protocol.
> Update Synacormedia usersync protocol

- src/main/resources/bidder-config/facebook.yaml
Added app request types for audience network bidder.
> Add app requests for Audience Network bidder

- src/main/resources/static/bidder-params/triplelift.json
Updated .json schema for TripleLift bidder to keep up with GO version.
> Simplify TripleLift's json schema

- src/main/resources/bidder-config/pubmatic.yaml
http://hbopenbid.pubmatic.com/translator?source=prebid-server
->
https://hbopenbid.pubmatic.com/translator?source=prebid-server
> Updated PubMatic endpoint to use https

- src/main/resources/application.yaml
Current tar archive does not contains required file.
> Fix MaxMind external file name

- src/main/java/org/prebid/server/auction/BidResponseCreator.java
- src/test/java/org/prebid/server/auction/BidResponseCreatorTest.java
Implements https://github.com/prebid/prebid-server/issues/1116
> Return nbr=0 for No-Bid response

- src/main/java/org/prebid/server/bidder/gamoshi/GamoshiBidder.java
- src/main/resources/bidder-config/gamoshi.yaml
- src/test/java/org/prebid/server/bidder/gamoshi/GamoshiBidderTest.java
- src/test/java/org/prebid/server/it/GamoshiTest.java
- Updated Gamoshi endpoint URL query parameters;
- Updated Gamoshi Usersync URL.
> Gamoshi Bidder updating cookie

- src/main/java/org/prebid/server/validation/RequestValidator.java
- src/test/java/org/prebid/server/validation/RequestValidatorTest.java
Updated native request validation to match GO version's behavior.
> Native validation update

- src/main/java/org/prebid/server/privacy/gdpr/vendorlist/VendorListService.java
The logs of VendorListService were reduced to short message.
> Reduce stacktrace of VendorListService

- src/main/resources/static/bidder-params/triplelift_native.json
Updated .json schema for TripleLiftNative bidder to keep up with GO version.
> Simplify triplelift_native.json schema

- src/main/java/org/prebid/server/bidder/facebook/FacebookBidder.java
- src/test/java/org/prebid/server/bidder/facebook/FacebookBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/facebook/test-facebook-bid-request-1.json
Check Format if height is null added
Test added
> Fix Facebook adapter ignoring banner.format sizes

- src/main/resources/bidder-config/ix.yaml
Update usersync url in ix.yaml to keep up with Go version.
Before:
http://ssum.casalemedia.com/usermatchredir?s=184932&cb=
After:
url: https://ssum-sec.casalemedia.com/usermatchredir?s=184932&cb=
> Update usersync url in ix.yaml

- src/main/resources/bidder-config/adform.yaml
- src/main/resources/bidder-config/adtelligent.yaml
- src/main/resources/bidder-config/appnexus.yaml
- src/main/resources/bidder-config/brightroll.yaml
- src/main/resources/bidder-config/conversant.yaml
- src/main/resources/bidder-config/lifestreet.yaml
- src/main/resources/bidder-config/pubmatic.yaml
- src/main/resources/bidder-config/pulsepoint.yaml
- src/main/resources/bidder-config/rhythmone.yaml
- src/main/resources/bidder-config/somoaudience.yaml
- src/main/resources/bidder-config/sovrn.yaml
Change usersync URL protocol in all bidders to https URLs instead of protocol relative (//) urls.
> Change usersync URL protocol in all bidders

- src/main/resources/bidder-config/conversant.yaml
Update usersync url of Conversant bidder to keep up with Go version.
> Update usersync url of Conversant bidder

- src/main/resources/bidder-config/triplelift.yaml
- src/main/resources/bidder-config/tripleliftnative.yaml
Update usersync url of TripleLift and TripleLiftNative bidders to keep up with Go version.
> Update usersync url of TripleLift and TripleLiftNative bidders

- src/main/resources/bidder-config/pubmatic.yaml
Update usersync url of Pubmatic bidder to keep up with Go version.
> Update usersync url of Pubmatic bidder

- src/main/java/org/prebid/server/bidder/synacormedia/SynacormediaBidder.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/synacormedia/ExtImpSynacormedia.java
- src/main/resources/static/bidder-params/synacormedia.json
- src/test/java/org/prebid/server/bidder/synacormedia/SynacormediaBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/synacormedia/test-auction-synacormedia-request.json
- src/test/resources/org/prebid/server/it/openrtb2/synacormedia/test-synacormedia-bid-request.json
Add TagId to Synacormedia Bidder and tests to keep up with Go version.
> Add TagId to Synacormedia Bidder

- docs/config-app.md
- src/main/java/org/prebid/server/handler/VtrackHandler.java
- src/main/java/org/prebid/server/spring/config/WebConfiguration.java
- src/main/resources/application.yaml
- src/test/java/org/prebid/server/handler/VtrackHandlerTest.java
Add `vtrack.allow-unkonwn-bidder` - config parameter;
Update doc.
Update tests.
> Add vtrack unknown bidder processing.

- src/main/java/org/prebid/server/bidder/brightroll/BrightrollBidder.java
- src/main/java/org/prebid/server/bidder/brightroll/BrightrollConstant.java
- src/main/resources/bidder-config/brightroll.yaml
- src/test/java/org/prebid/server/bidder/brightroll/BrightrollBidderTest.java
Initial changes to add the first publisher to Brightroll adapter
> Brightroll adapter- Initial changes to add  businessinsider

- src/main/resources/bidder-config/visx.yaml
Add app-media-types in visx.yaml of Visx bidder to keep up with Go version.
> Add app-media-types to visx.yaml of Visx bidder

- src/main/resources/bidder-config/brightroll.yaml
Need to update Cookie sync URL in brightroll adapter
Reviewers: @DGarbar
> Brightroll - cookie sync config update

- src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtImpPrebid.java
- src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java
``imp.video.ext.videotype="rewarded"`` should be only if 
``imp.ext.prebid.is_rewarded_inventory == 1``
> Rubicon Rewarded Video boolean bug fix

- src/main/java/org/prebid/server/handler/AuctionHandler.java
- src/main/java/org/prebid/server/handler/CookieSyncHandler.java
- src/main/java/org/prebid/server/handler/SetuidHandler.java
- src/main/java/org/prebid/server/privacy/gdpr/TcfDefinerService.java
- src/test/java/org/prebid/server/handler/AuctionHandlerTest.java
- src/test/java/org/prebid/server/handler/CookieSyncHandlerTest.java
- src/test/java/org/prebid/server/handler/SetuidHandlerTest.java
- src/test/java/org/prebid/server/privacy/gdpr/TcfDefinerServiceTest.java
Also change the behavior of `gdpr enable`.  Now account config will override the default
> Add account usage for setuid, cookieSync, legacy auction

- src/main/java/org/prebid/server/bidder/adtelligent/AdtelligentBidder.java
- src/main/java/org/prebid/server/bidder/brightroll/BrightrollBidder.java
- src/main/java/org/prebid/server/bidder/somoaudience/SomoaudienceBidder.java
- src/main/java/org/prebid/server/bidder/sovrn/SovrnBidder.java
- src/test/java/org/prebid/server/bidder/adtelligent/AdtelligentBidderTest.java
- src/test/java/org/prebid/server/bidder/brightroll/BrightrollBidderTest.java
- src/test/java/org/prebid/server/bidder/somoaudience/SomoaudienceBidderTest.java
- src/test/java/org/prebid/server/bidder/sovrn/SovrnBidderTest.java
Follow up #648, fix all bidders.
> Bidder currency bug fix

- src/main/java/org/prebid/server/privacy/gdpr/TcfDefinerService.java
- src/main/java/org/prebid/server/settings/model/GdprConfig.java
- src/test/java/org/prebid/server/privacy/gdpr/TcfDefinerServiceTest.java
https://github.com/prebid/prebid-server/issues/1251
> Add Consent string presence feature

- src/main/java/org/prebid/server/auction/AuctionRequestFactory.java
- src/main/java/org/prebid/server/exception/InvalidRequestException.java
- src/main/java/org/prebid/server/exception/UnauthorizedAccountException.java
- src/main/java/org/prebid/server/handler/openrtb2/AmpHandler.java
- src/main/java/org/prebid/server/handler/openrtb2/AuctionHandler.java
- src/main/java/org/prebid/server/privacy/gdpr/GdprService.java
- src/main/java/org/prebid/server/privacy/gdpr/TcfDefinerService.java
- src/main/java/org/prebid/server/privacy/gdpr/vendorlist/VendorListService.java
- src/main/java/org/prebid/server/vertx/http/BasicHttpClient.java
- src/test/java/org/prebid/server/auction/AuctionRequestFactoryTest.java
- src/test/java/org/prebid/server/handler/openrtb2/AmpHandlerTest.java
- src/test/java/org/prebid/server/handler/openrtb2/AuctionHandlerTest.java
Fixes:
- Remove HttpClient logging stacktrace.
- Refactored `UnauthorizedAccountException` message handing.
- Reduced TCF related error logging.
> Remove HttpClient logging stacktrace

- src/main/java/org/prebid/server/auction/AmpRequestFactory.java
- src/test/java/org/prebid/server/auction/AmpRequestFactoryTest.java
> Revert First Party Data AMP targeting

- src/main/resources/bidder-config/eplanning.yaml
Update usersync Url of Eplanning Bidder.
> Update usersync Url of Eplanning Bidder

- src/main/java/org/prebid/server/privacy/gdpr/tcfstrategies/purpose/typestrategies/PurposeTwoBasicEnforcePurposeStrategy.java
- src/main/java/org/prebid/server/spring/config/PrivacyServiceConfiguration.java
- src/test/java/org/prebid/server/privacy/gdpr/tcfstrategies/purpose/typestrategies/PurposeTwoBasicEnforcePurposeStrategyTest.java
purposes 1-10 (except 2) checks only for simple consent
purpose 2 check for PurposeLI consent
> Update Basic enforcement strategy

- src/main/java/org/prebid/server/bidder/brightroll/BrightrollBidder.java
- src/main/java/org/prebid/server/bidder/brightroll/model/PublisherOverride.java
- src/main/java/org/prebid/server/spring/config/bidder/BrightrollConfiguration.java
- src/main/resources/bidder-config/brightroll.yaml
- src/test/java/org/prebid/server/bidder/brightroll/BrightrollBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/brightroll/test-brightroll-bid-request-1.json
Description:
Adding bid floor as a configuration for publishers to config. This will be populated on request.imp.bidfloor  in the bid request. Business Insider currently not sending bid floor in their open RTB bid requests and want us to add their default global floor price (0.30 cents). So configuring that bid floor value for BusinessInsider.
Reviewers:
@bretg 
@rpanchyk
> Brightroll adapter - Adding bid floor config parameter

- src/main/java/org/prebid/server/bidder/OpenrtbBidder.java
- src/main/java/org/prebid/server/bidder/adgeneration/AdgenerationBidder.java
- src/test/java/org/prebid/server/bidder/adgeneration/AdgenerationBidderTest.java
- src/test/java/org/prebid/server/bidder/grid/GridBidderTest.java
Initially this PR was aimed for `Adgeneration` and `Grid` bidders, but affects all implemented bidders extended from `OpenrtbBidder`.
> Set bid currency in OpenRtb abstract bidder

- src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
- src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java
> Fix adslot to ignore first party data restrictions if no bidders

- src/main/java/org/prebid/server/auction/ExchangeService.java
- src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
> Remove imp.ext.context.data if not allowed for bidder

- src/main/resources/bidder-config/grid.yaml
Update configuration file of GridBidder
> Update app type in GridBidder

- src/main/java/org/prebid/server/bidder/telaria/TelariaBidder.java
- src/main/java/org/prebid/server/bidder/telaria/model/TelariaRequestExt.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/telaria/ExtImpTelaria.java
- src/test/java/org/prebid/server/bidder/telaria/TelariaBidderTest.java
- src/test/java/org/prebid/server/it/TelariaTest.java
- src/test/resources/org/prebid/server/it/openrtb2/telaria/test-auction-telaria-request.json
- src/test/resources/org/prebid/server/it/openrtb2/telaria/test-telaria-bid-request-1.json
Update Telaria Bidder with additional parameter ,,extra" in impression extention ExtImpTelaria.
Modify request.ext by adding ,,extra" parameter from TelariaRequestExt.
> Add extra parameter to ExtImp of TelariaBidder

- src/main/java/org/prebid/server/bidder/adform/AdformRequestUtil.java
- src/test/java/org/prebid/server/bidder/adform/AdformBidderTest.java
```
{
"test.com": {
"uId": 1
}
}
```
-->
```
{
"test.com": {
"uId": [1]
}
}
```
> fix eids object structure in Adform bidder

- src/main/resources/bidder-config/brightroll.yaml
- src/test/resources/org/prebid/server/it/openrtb2/brightroll/test-brightroll-bid-request-1.json
Updating adapter config bidfloor from 0.3 to 0.65 for BusinessInsider
Reviewers:
@bretg
@rpanchyk
> [Brightroll]Adapter config update : bidfloor from 0.3 to 0.65 for BusinessInsider

- src/main/java/org/prebid/server/geolocation/CircuitBreakerSecuredGeoLocationService.java
- src/main/java/org/prebid/server/vertx/CircuitBreaker.java
- src/main/java/org/prebid/server/vertx/http/CircuitBreakerSecuredHttpClient.java
- src/main/java/org/prebid/server/vertx/jdbc/CircuitBreakerSecuredJdbcClient.java
Changes:
- Disabled Vert.x circuit-breaker event-bus notification
- Added expiration for http circuit breaker after idle time exceeds
> Optimize circuit breaker creation and destroy

- src/main/java/org/prebid/server/bidder/triplelift/TripleliftBidder.java
- src/test/java/org/prebid/server/bidder/triplelift/TripleliftBidderTest.java
- src/test/java/org/prebid/server/it/TripleliftTest.java
> Review Triplelift bidder

- src/main/java/org/prebid/server/bidder/conversant/ConversantBidder.java
- src/test/java/org/prebid/server/bidder/conversant/ConversantBidderTest.java
> Review conversant adapter

- pom.xml
For upcoming release for #1059 & #1060
> Set 1.51.1 project version

- docs/application-settings.md
Adding detail and transitions around the accounts config
> accounts config doc updates

- src/main/java/org/prebid/server/proto/response/BidderInfo.java
- src/main/resources/application.yaml
Follow-up https://github.com/prebid/prebid-server/issues/1632
> Change GVL URL

- src/main/java/org/prebid/server/auction/BidderAliases.java
- src/main/java/org/prebid/server/auction/ExchangeService.java
- src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
- src/main/java/org/prebid/server/bidder/triplelift/TripleliftBidder.java
- src/main/java/org/prebid/server/json/JsonMerger.java
- src/main/java/org/prebid/server/settings/model/Account.java
- src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java
Fix for #931 and other minor clean code.
> Fix setting Rubicon size id using video placement

- src/main/java/org/prebid/server/auction/AuctionRequestFactory.java
- src/main/java/org/prebid/server/cache/CacheService.java
- src/test/java/org/prebid/server/auction/BidResponseCreatorTest.java
- src/test/java/org/prebid/server/cache/CacheServiceTest.java
> Fixed mismatched winUrl and VastXml

- docs/config-app.md
- src/main/java/org/prebid/server/auction/ExchangeService.java
- src/main/java/org/prebid/server/auction/SchainResolver.java
- src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
- src/main/resources/application.yaml
- src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
- src/test/java/org/prebid/server/auction/SchainResolverTest.java
Implements https://github.com/prebid/prebid-server/issues/1491
> Add support for host defined schain node

- src/main/resources/bidder-config/kubient.yaml
Changes from https://github.com/prebid/prebid-server/pull/1629/
> Set Kubient email to prebid@kubient.com

- src/main/java/org/prebid/server/auction/AuctionRequestFactory.java
- src/test/java/org/prebid/server/auction/AuctionRequestFactoryTest.java
- src/test/java/org/prebid/server/auction/ImplicitParametersExtractorTest.java
- src/test/resources/org/prebid/server/it/openrtb2/smaato/test-smaato-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/video/test-video-appnexus-bid-request-1.json
- src/test/resources/org/prebid/server/it/openrtb2/video/test-video-appnexus-bid-request-2.json
- src/test/resources/org/prebid/server/it/openrtb2/video/test-video-appnexus-request.json
- src/test/resources/org/prebid/server/it/openrtb2/yieldlab/test-auction-yieldlab-response.json
> Fix setting site domain

- src/main/java/org/prebid/server/auction/AuctionRequestFactory.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/ExtDevice.java
- src/test/java/org/prebid/server/auction/AuctionRequestFactoryTest.java
- src/test/java/org/prebid/server/auction/InterstitialProcessorTest.java
- src/test/java/org/prebid/server/validation/RequestValidatorTest.java
This PR addresses https://github.com/prebid/prebid-server/issues/1699.
> Workaround for bug in iOS 14 related to setting LMT flag

- src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java
Related to https://github.com/prebid/prebid-server/issues/1715
> Create test for checking sending bids with same impId.

- src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
- src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java
Fix for https://github.com/prebid/prebid-server-java/pull/1162
> Segments insert fix

- README.md
https://github.com/prebid/prebid-server/issues/1740
> Add request for registration

- docs/config-app.md
This is the first of some changes to the prometheus support.
I'll start with documenting that it acutally exists :smile:
> Document prometheus support

- src/main/resources/bidder-config/visx.yaml
{UUID} has not been expanded correctly in the user sync requests.
> VIS.X: Fixed usersync uuid macro

- src/main/resources/bidder-config/adtarget.yaml
- src/main/resources/bidder-config/adtelligent.yaml
`go` repo PR: https://github.com/prebid/prebid-server/pull/1770/
> Adtarget, Adtelligent, Mediafuse: Update sync type

- src/main/java/org/prebid/server/bidder/beachfront/BeachfrontBidder.java
- src/main/java/org/prebid/server/bidder/beachfront/model/BeachfrontBannerRequest.java
- src/test/java/org/prebid/server/bidder/beachfront/BeachfrontBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/beachfront/test-beachfront-bid-request-3.json
`go` repo PR: https://github.com/prebid/prebid-server/pull/1737/
> beachfront: Changes to support real 204

- src/main/resources/bidder-config/adtelligent.yaml
- src/test/resources/org/prebid/server/it/test-application.properties
This PR discards #1125 since built-in aliases implemented in #927
Initially ported from https://github.com/prebid/prebid-server/pull/1635
> Configure Mediafuse allias for Adtelligent

- src/main/resources/static/bidder-params/kidoz.json
https://github.com/prebid/prebid-server/pull/1808
> Kidoz: Update JSON Schema Reference To Type String

- src/main/resources/bidder-config/adyoulike.yaml
https://github.com/prebid/prebid-server/pull/1805
> Update Adyoulike endpoint to hit production servers

- src/main/java/org/prebid/server/bidder/tappx/TappxBidder.java
- src/test/java/org/prebid/server/bidder/tappx/TappxBidderTest.java
In order to fix issue described here: https://github.com/prebid/prebid-server-java/issues/1263
> Tappx: add path concat instead of rewrite

- src/main/resources/bidder-config/inmobi.yaml
From https://github.com/prebid/prebid-server/pull/1827
> InMobi: Updating support for sites

- src/main/java/org/prebid/server/vast/VastModifier.java
- src/test/java/org/prebid/server/vast/VastModifierTest.java
- src/test/resources/org/prebid/server/it/openrtb2/aja/test-auction-aja-response.json
- src/test/resources/org/prebid/server/it/openrtb2/aja/test-cache-aja-request.json
- src/test/resources/org/prebid/server/it/openrtb2/aja/test-cache-matcher-aja.json
- src/test/resources/org/prebid/server/it/openrtb2/datablocks/test-auction-datablocks-response.json
- src/test/resources/org/prebid/server/it/openrtb2/datablocks/test-cache-datablocks-request.json
- src/test/resources/org/prebid/server/it/openrtb2/datablocks/test-cache-matcher-datablocks.json
- src/test/resources/org/prebid/server/it/openrtb2/synacormedia/test-auction-synacormedia-response.json
- src/test/resources/org/prebid/server/it/openrtb2/synacormedia/test-cache-matcher-synacormedia.json
- src/test/resources/org/prebid/server/it/openrtb2/synacormedia/test-cache-synacormedia-request.json
- src/test/resources/org/prebid/server/it/openrtb2/zeroclickfraud/test-auction-zeroclickfraud-response.json
- src/test/resources/org/prebid/server/it/openrtb2/zeroclickfraud/test-cache-matcher-zeroclickfraud.json
- src/test/resources/org/prebid/server/it/openrtb2/zeroclickfraud/test-cache-zeroclickfraud-request.json
> Vast resolve logic update

- src/main/java/org/prebid/server/bidder/pubmatic/PubmaticBidder.java
- src/main/java/org/prebid/server/bidder/pubmatic/model/PubmaticExtAdServer.java
- src/main/java/org/prebid/server/bidder/pubmatic/model/PubmaticExtData.java
- src/main/java/org/prebid/server/bidder/pubmatic/proto/PubmaticImpExt.java
- src/test/java/org/prebid/server/bidder/pubmatic/PubmaticBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/pubmatic/test-auction-pubmatic-request.json
- src/test/resources/org/prebid/server/it/openrtb2/pubmatic/test-pubmatic-bid-request-1.json
Ported from https://github.com/prebid/prebid-server/pull/1880
> Pubmatic: Sending GPT slotname in impression extension

- src/main/java/org/prebid/server/geolocation/MaxMindGeoLocationService.java
- src/test/java/org/prebid/server/geolocation/MaxMindGeoLocationServiceTest.java
Fixes https://github.com/prebid/prebid-server-java/issues/1363
> Fix NullPointerException after MaxMindGeoLocationService could not find country by IP

- src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
- src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java
> Rubicon: Update site segTaxes, to work with 5 and 6

- src/main/java/org/prebid/server/spring/config/bidder/model/BidderConfigurationProperties.java
- src/main/java/org/prebid/server/spring/config/bidder/model/DefaultBidderConfigurationProperties.java
> Make implicit bidder config defaults more explicit

- src/test/groovy/org/prebid/server/functional/service/PrebidServerService.groovy
https://github.com/prebid/prebid-server-java/pull/1510
> Remove hardcoded media type for /bidders/params endpoint

- src/main/java/org/prebid/server/auction/CategoryMappingService.java
- src/main/java/org/prebid/server/auction/requestfactory/Ortb2ImplicitParametersResolver.java
- src/test/java/org/prebid/server/auction/CategoryMappingServiceTest.java
> Actualize category mapping feature - proposal

- src/main/java/org/prebid/server/auction/BidResponseCreator.java
- src/main/java/org/prebid/server/auction/PriceGranularity.java
- src/main/java/org/prebid/server/auction/categorymapping/BasicCategoryMappingService.java
- src/main/java/org/prebid/server/auction/categorymapping/CategoryMappingService.java
- src/main/java/org/prebid/server/auction/categorymapping/NoOpCategoryMappingService.java
- src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
- src/test/java/org/prebid/server/auction/BasicCategoryMappingServiceTest.java
- src/test/java/org/prebid/server/auction/BidResponseCreatorTest.java
> Add category mapping enabled toggle - proposal

- src/main/java/org/prebid/server/bidder/adf/AdfBidder.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/adf/ExtImpAdf.java
- src/main/resources/static/bidder-params/adf.json
- src/test/java/org/prebid/server/bidder/adf/AdfBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/adf/test-adf-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/adf/test-adf-bid-response.json
- src/test/resources/org/prebid/server/it/openrtb2/adf/test-auction-adf-request.json
- src/test/resources/org/prebid/server/it/openrtb2/adf/test-auction-adf-response.json
Same changes as in https://github.com/prebid/prebid-server/pull/2043
> Adf adpater: new params, multi-format bids support

- src/main/java/org/prebid/server/bidder/appnexus/AppnexusBidder.java
- src/main/java/org/prebid/server/bidder/appnexus/proto/AppnexusImpExtAppnexus.java
- src/main/java/org/prebid/server/bidder/appnexus/proto/AppnexusReqExt.java
- src/main/java/org/prebid/server/bidder/appnexus/proto/AppnexusReqExtAppnexus.java
- src/main/java/org/prebid/server/spring/config/bidder/AppnexusConfiguration.java
- src/main/java/org/prebid/server/spring/config/bidder/FacebookConfiguration.java
- src/main/resources/bidder-config/appnexus.yaml
- src/test/java/org/prebid/server/bidder/appnexus/AppnexusBidderTest.java
- src/test/java/org/prebid/server/it/ApplicationTest.java
- src/test/resources/org/prebid/server/it/amp/test-appnexus-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/rubicon_appnexus/test-appnexus-bid-request-1.json
- src/test/resources/org/prebid/server/it/openrtb2/rubicon_appnexus/test-appnexus-bid-request-2.json
- src/test/resources/org/prebid/server/it/openrtb2/rubicon_appnexus/test-auction-rubicon-appnexus-response.json
- src/test/resources/org/prebid/server/it/openrtb2/rubicon_appnexus_multi_bid/test-appnexus-bid-request-1.json
Implemented last changes from PBS-Go.
> Actualize Appnexus bidder changes

- src/main/java/org/prebid/server/auction/requestfactory/Ortb2ImplicitParametersResolver.java
- src/test/resources/org/prebid/server/it/openrtb2/aceex/test-auction-aceex-request.json
Updates from https://github.com/prebid/prebid-server/issues/2088
> Add gpid to supported imp ext fields

- src/main/resources/bidder-config/smaato.yaml
- src/main/resources/static/bidder-params/smaato.json
- src/test/resources/org/prebid/server/it/openrtb2/smaato/test-auction-smaato-request.json
- src/test/resources/org/prebid/server/it/openrtb2/smaato/test-smaato-bid-request.json
Includes these fixes:
1. https://github.com/prebid/prebid-server/pull/2064/
2. https://github.com/prebid/prebid-server/pull/2089/
3. Updated smaato.json.
> Change url in usersync, add intl field to json and update smaato.json

- src/test/groovy/org/prebid/server/functional/testcontainers/container/PrebidServerContainer.groovy
- src/test/groovy/org/prebid/server/functional/tests/AmpSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/AuctionSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/BidValidationSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/DealsSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/DebugSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/InfoBiddersSpec.groovy
- src/test/groovy/org/prebid/server/functional/util/PBSUtils.groovy
> Tests for default request

- src/main/java/org/prebid/server/auction/StoredRequestProcessor.java
- src/main/java/org/prebid/server/auction/VideoStoredRequestProcessor.java
- src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
- src/test/groovy/org/prebid/server/functional/testcontainers/container/PrebidServerContainer.groovy
- src/test/groovy/org/prebid/server/functional/tests/AmpSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/AuctionSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/BidValidationSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/DealsSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/DebugSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/InfoBiddersSpec.groovy
- src/test/groovy/org/prebid/server/functional/util/PBSUtils.groovy
- src/test/java/org/prebid/server/auction/StoredRequestProcessorTest.java
- src/test/java/org/prebid/server/auction/VideoStoredRequestProcessorTest.java
> Fix Stored vs Default request merging

- src/test/groovy/org/prebid/server/functional/model/request/amp/AmpRequest.groovy
- src/test/groovy/org/prebid/server/functional/model/request/amp/ConsentType.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/CcpaSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GdprSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/PrivacyBaseSpec.groovy
> Tests for validation amp request

- src/test/groovy/org/prebid/server/functional/tests/BidValidationSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/DebugSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/CcpaSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GdprSpec.groovy
> Update tests for debug errors, warnings

- src/main/resources/bidder-config/triplelift.yaml
- src/main/resources/bidder-config/tripleliftnative.yaml
- Adds iframe usersync to both Triplelift adapters
- Primary is iframe; secondary is redirect
> Triplelift: Add iframe sync

- docs/application-settings.md
- docs/config-app.md
https://github.com/prebid/prebid-server/issues/1650
> Add documentation for the debug control

- src/test/groovy/org/prebid/server/functional/model/bidderspecific/BidderRequest.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/BidRequestExt.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Fd.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Schain.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Source.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/SourceExt.groovy
- src/test/groovy/org/prebid/server/functional/tests/SchainSpec.groovy
> Add tests for another way to represent BidRequest.Source.Ext.Schain

- src/main/resources/bidder-config/adtelligent.yaml
- src/test/resources/org/prebid/server/it/test-application.properties
https://github.com/prebid/prebid-server/pull/2165
> New Bidder: Janet (Alias Of Adtelligent)

- src/main/java/org/prebid/server/bidder/adkernel/AdkernelBidder.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/adkernel/ExtImpAdkernel.java
- src/main/resources/bidder-config/adkernel.yaml
- src/main/resources/static/bidder-params/adkernel.json
- src/test/java/org/prebid/server/bidder/adkernel/AdkernelBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/adkernel/test-auction-adkernel-request.json
- src/test/resources/org/prebid/server/it/test-application.properties
https://github.com/prebid/prebid-server/pull/2169
> Adkernel: Add static endpoint

- src/test/groovy/org/prebid/server/functional/model/ChannelType.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/UserExt.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/CcpaAuctionSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
> Tests for 'pbjs' and 'web' channels

- src/test/groovy/org/prebid/server/functional/model/db/StoredResponse.groovy
- src/test/groovy/org/prebid/server/functional/model/db/typeconverter/StoredAuctionResponseConfigTypeConverter.groovy
- src/test/groovy/org/prebid/server/functional/model/db/typeconverter/StoredBidResponseConfigTypeConverter.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/AssetImage.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/DistributionChannel.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Imp.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/ImpExtPrebid.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Native.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Request.groovy
- src/test/groovy/org/prebid/server/functional/model/response/auction/Adm.groovy
- src/test/groovy/org/prebid/server/functional/model/response/auction/Bid.groovy
- src/test/groovy/org/prebid/server/functional/model/response/auction/BidExt.groovy
- src/test/groovy/org/prebid/server/functional/model/response/auction/BidResponse.groovy
- src/test/groovy/org/prebid/server/functional/model/response/auction/MediaType.groovy
- src/test/groovy/org/prebid/server/functional/model/response/auction/SeatBid.groovy
- src/test/groovy/org/prebid/server/functional/testcontainers/container/PrebidServerContainer.groovy
- src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/Bidder.groovy
- src/test/groovy/org/prebid/server/functional/tests/BidValidationSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/CacheSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/DealsSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/HttpSettingsSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/MultibidSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/NativeSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/SmokeSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pg/PgAuctionSpec.groovy
- src/test/groovy/org/prebid/server/functional/util/PBSUtils.groovy
- src/test/resources/org/prebid/server/functional/db_schema.sql
> Tests for native stored response with missing asset id

- src/main/java/org/prebid/server/bidder/adkerneladn/AdkernelAdnBidder.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/adkerneladn/ExtImpAdkernelAdn.java
- src/main/resources/bidder-config/adkerneladn.yaml
- src/main/resources/static/bidder-params/adkernelAdn.json
- src/test/java/org/prebid/server/bidder/adkerneladn/AdkernelAdnBidderTest.java
- src/test/java/org/prebid/server/it/AdkernelAdnTest.java
- src/test/resources/org/prebid/server/it/test-application.properties
https://github.com/prebid/prebid-server/pull/2185
> AdkernelAdn: add static endpoint host

- src/main/java/org/prebid/server/bidder/pubmatic/PubmaticBidder.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/pubmatic/ExtImpPubmatic.java
- src/main/resources/static/bidder-params/pubmatic.json
- src/test/java/org/prebid/server/bidder/pubmatic/PubmaticBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/pubmatic/test-auction-pubmatic-request.json
- src/test/resources/org/prebid/server/it/openrtb2/pubmatic/test-pubmatic-bid-request.json
https://github.com/prebid/prebid-server/pull/2184
> PubMatic: Add "kadfloor" parameter

- src/main/java/org/prebid/server/bidder/adot/AdotBidder.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/adot/ExtImpAdot.java
- src/main/resources/bidder-config/adot.yaml
- src/main/resources/static/bidder-params/adot.json
- src/test/java/org/prebid/server/bidder/adot/AdotBidderTest.java
https://github.com/prebid/prebid-server/pull/2164
> Adot: add new bid param publisherPath

- src/test/groovy/org/prebid/server/functional/model/request/auction/ImpExt.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/ImpExtContextData.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/ImpExtContextDataAdServer.groovy
- src/test/groovy/org/prebid/server/functional/tests/pg/TargetingFirstPartyDataSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pg/TargetingSpec.groovy
- Add tests to cover PBS takes alternative sources to match PG targeting
- Separate PG targeting spec on 2 specs: base spec and first party data specific spec
> Tests: Cover that PBS takes alternative sources to match PG targeting

- src/test/groovy/org/prebid/server/functional/model/response/auction/BidResponse.groovy
- src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsBaseSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsRulesSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
1 test is temporarily ignored due to unclear requirements. Waiting for resolution.
> Price Floors: Minor test fixes + temporary ignore of 1 test

- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsBaseSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsEnforcementSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsSignalingSpec.groovy
> Price floors/enhancements tests

- src/test/groovy/org/prebid/server/functional/model/deals/lineitem/targeting/TargetingType.groovy
- src/test/groovy/org/prebid/server/functional/tests/pg/TargetingFirstPartyDataSpec.groovy
Tests for https://github.com/prebid/prebid-server-java/pull/1832
> Add tests to cover PG user FPD targeting is taken from bidRequest.user

- src/main/java/org/prebid/server/bidder/amx/AmxBidder.java
- src/main/java/org/prebid/server/bidder/amx/model/AmxBidExt.java
- src/main/resources/bidder-config/amx.yaml
- src/test/java/org/prebid/server/bidder/amx/AmxBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/amx/test-amx-bid-response.json
- src/test/resources/org/prebid/server/it/openrtb2/amx/test-auction-amx-response.json
Corresponding ticker: [2220](https://github.com/prebid/prebid-server/pull/2220)
> Amx  adapter: add support native format

- src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
Tests for https://github.com/prebid/prebid-server-java/pull/1758
> Add test for pass server info to request

- src/main/java/org/prebid/server/bidder/yieldlab/YieldlabBidder.java
Corresponding ticket: [2213](https://github.com/prebid/prebid-server/pull/2213)
> Yieldlab: adapter fix GDPR handling for AMP

- src/test/groovy/org/prebid/server/functional/model/request/auction/BidderConfig.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/BidderConfigOrtb.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/ExtPrebidBidderConfig.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Prebid.groovy
- src/test/groovy/org/prebid/server/functional/tests/pg/TargetingFirstPartyDataSpec.groovy
Tests for https://github.com/prebid/prebid-server-java/pull/1817
> Add tests to cover PG targeting by bidder-specific config

- .github/workflows/pr-functional-tests.yml
- docs/developers/functional-tests.md
- pom.xml
- src/test/groovy/org/prebid/server/functional/model/response/auction/SeatBid.groovy
- src/test/groovy/org/prebid/server/functional/testcontainers/PbsServiceFactory.groovy
- src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/Bidder.groovy
- src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/HttpSettings.groovy
- src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/NetworkScaffolding.groovy
- src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/PubStackAnalytics.groovy
- src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/pg/Alert.groovy
- src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/pg/DeliveryStatistics.groovy
- src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/pg/GeneralPlanner.groovy
- src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/pg/UserData.groovy
- src/test/groovy/org/prebid/server/functional/tests/BaseSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pg/AlertSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pg/BasePgSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pg/PgAuctionSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pg/PgDealsOnlySpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pg/PlansSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pg/ReportSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pg/TargetingSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pg/UserDetailsSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsSignalingSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/CcpaAmpSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
- src/test/groovy/org/prebid/server/functional/util/PBSUtils.groovy
- src/test/groovy/org/prebid/server/functional/util/SystemProperties.groovy
Relax timeouts for functional tests to account for unstable GitHub Actions performance
> Tests: Relax timeouts

- src/test/groovy/org/prebid/server/functional/model/request/auction/PrebidCache.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Targeting.groovy
- src/test/groovy/org/prebid/server/functional/tests/TargetingPreferDealsSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/TargetingSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsEnforcementSpec.groovy
Tests for https://github.com/prebid/prebid-server-java/pull/1852 
Also, add some more tests to cover targeting.includeBidderKeys, targeting.winningOnly, targeting.includeWinners
> Add tests to cover targeting alwaysIncludeDeals flag

- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
Test for https://github.com/prebid/prebid-server-java/pull/1851
> Tests: Cache-Control header parsing

- pom.xml
- src/test/groovy/org/prebid/server/functional/tests/BidAdjustmentSpec.groovy
Tests for https://github.com/prebid/prebid-server-java/pull/1865
> Tests for bid adjustment factors

- src/test/groovy/org/prebid/server/functional/model/bidder/CompressionType.groovy
- src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
- src/test/groovy/org/prebid/server/functional/util/HttpUtil.groovy
Test for https://github.com/prebid/prebid-server-java/pull/1857
> Tests: Add `endpoint-compression` configuration property for `gzip` compression

- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
Test for https://github.com/prebid/prebid-server-java/pull/1876
> Test: Price Floors Always add `skipped` flag

- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsEnforcementSpec.groovy
Test for https://github.com/prebid/prebid-server-java/pull/1885
> Test: Price Floors don't enforce, if feature disabled by request

- src/test/groovy/org/prebid/server/functional/tests/AmpSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/AuctionSpec.groovy
Test for https://github.com/prebid/prebid-server-java/pull/1058 
Issue: https://github.com/prebid/prebid-server/issues/2045
> Test: Merged stored requests when using {{UUID}}

- src/test/groovy/org/prebid/server/functional/tests/StoredResponseSpec.groovy
Test for https://github.com/prebid/prebid-server-java/pull/1899
> Test: Add stored bid response impId macro replacement

- src/test/groovy/org/prebid/server/functional/model/deals/report/LineItemStatusReport.groovy
- src/test/groovy/org/prebid/server/functional/service/PrebidServerService.groovy
- src/test/groovy/org/prebid/server/functional/testcontainers/PbsPgConfig.groovy
- src/test/groovy/org/prebid/server/functional/tests/pg/LineItemStatusSpec.groovy
Tests for https://github.com/prebid/prebid-server-java/pull/1898
> Add tests to cover line item status endpoint

- src/test/groovy/org/prebid/server/functional/model/request/auction/ImpExtPrebid.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Prebid.groovy
- src/test/groovy/org/prebid/server/functional/model/response/auction/BidResponsePrebid.groovy
- src/test/groovy/org/prebid/server/functional/model/response/auction/Prebid.groovy
- src/test/groovy/org/prebid/server/functional/tests/AuctionSpec.groovy
Tests for :https://github.com/prebid/prebid-server-java/pull/1906
> Test: Add passthrough for request 

- src/main/java/org/prebid/server/bidder/unicorn/UnicornBidder.java
- src/test/java/org/prebid/server/bidder/unicorn/UnicornBidderTest.java
Updates based on
- https://github.com/prebid/prebid-server/pull/2265
- https://github.com/prebid/prebid-server/pull/2277
Includes only refactoring, as field `accountId` is required in the `Unicorn` validation schema.
> Unicorn: refactoring

- src/main/resources/bidder-config/kargo.yaml
Adds usersync URL and redirect to adapter config
> Kargo Bidder: Adding usersync URL

- src/main/resources/bidder-config/bidmyadz.yaml
- src/main/resources/bidder-config/bliink.yaml
- src/main/resources/bidder-config/vidoomy.yaml
When we copy from PBS-Go, please convert the {{macros}}. And note that the bliink bidder param must have been copied from apacdex.
> fixing usersync copy-paste errors

- src/test/groovy/org/prebid/server/functional/model/response/auction/BidResponse.groovy
- src/test/groovy/org/prebid/server/functional/tests/pg/PgBidResponseSpec.groovy
Test for https://github.com/prebid/prebid-server-java/pull/1927
> Test: Update validation of Pg Deal Bid 

- src/main/resources/bidder-config/nextmillenium.yaml
https://github.com/prebid/prebid-server/pull/2240
> `NextMillenium`: Add usersync url

- src/main/resources/bidder-config/nextmillenium.yaml
missing an n in the bidder name
> nextmillennium config typo

- src/main/resources/bidder-config/nextmillennium.yaml
received an updated group contact info
> nextmillennium contact info update

- src/main/resources/bidder-config/improvedigital.yaml
> Improve Digital adapter: enable gzip conversion of requests

- src/test/groovy/org/prebid/server/functional/model/request/auction/App.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Audio.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/BidRequest.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/BrandVersion.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Content.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Device.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Eid.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Imp.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/ImpExtPrebid.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Network.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Prebid.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Publisher.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Regs.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Site.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Source.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/SupplyChain.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/SupplyChainNode.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Uid.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/User.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/UserAgent.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/UserExt.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Video.groovy
- src/test/groovy/org/prebid/server/functional/model/response/auction/Bid.groovy
- src/test/groovy/org/prebid/server/functional/model/response/auction/MediaType.groovy
- src/test/groovy/org/prebid/server/functional/testcontainers/PbsConfig.groovy
- src/test/groovy/org/prebid/server/functional/tests/OrtbConverterSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsRulesSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/CcpaAuctionSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
Tests for https://github.com/prebid/prebid-server-java/pull/1911
`TODO:` section will remove after review
> Tests: Openrtb 2.6

- src/main/resources/bidder-config/invibes.yaml
Updated config file  to support gzip.
Please add the compression config to PBS-Go when the feature is added there.
> Invibes: Updated config file  to support gzip

- src/test/groovy/org/prebid/server/functional/model/request/auction/ImpExtPrebidFloors.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsCurrencySpec.groovy
Test for: https://github.com/prebid/prebid-server-java/pull/1975
> Test: Price Floors imp level floorMin

- src/main/resources/bidder-config/marsmedia.yaml
> Marsmedia: Change endpoint

- src/test/groovy/org/prebid/server/functional/model/db/StoredImp.groovy
- src/test/groovy/org/prebid/server/functional/model/pricefloors/PriceFloorField.groovy
- src/test/groovy/org/prebid/server/functional/model/pricefloors/Rule.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/ImpExt.groovy
- src/test/groovy/org/prebid/server/functional/testcontainers/PbsConfig.groovy
- src/test/groovy/org/prebid/server/functional/tests/BaseSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsRulesSpec.groovy
- src/test/resources/org/prebid/server/functional/db_schema.sql
Test for https://github.com/prebid/prebid-server-java/pull/1988
> Test: Price Floors to support adUnitCode

- extra/modules/pom.xml
- pom.xml
- src/main/java/org/prebid/server/validation/BidderParamValidator.java
- src/test/groovy/org/prebid/server/functional/testcontainers/Dependencies.groovy
- src/test/java/org/prebid/server/it/IntegrationTest.java
Please be advised that I was forced to bump one prod scope dependency and needed to do a very simple code change: JSON schema validator.
> Dependencies: Bump test dependencies

- src/test/groovy/org/prebid/server/functional/tests/HttpSettingsSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/SmokeSpec.groovy
Test for https://github.com/prebid/prebid-server-java/pull/1954
> Tests: Fix cookie-sync

- src/main/resources/bidder-config/sovrn.yaml
Corresponding ticket: https://github.com/prebid/prebid-server/pull/2397
> Core: Sovrn bidder add iframe url

- src/test/groovy/org/prebid/server/functional/tests/pg/TargetingFirstPartyDataSpec.groovy
Test for https://github.com/prebid/prebid-server-java/pull/2018
> Tests: PG FPD targeting at the imp-level

- src/test/groovy/org/prebid/server/functional/tests/pg/TargetingSpec.groovy
Test for: https://github.com/prebid/prebid-server-java/pull/2048
> Test: PG update paths for `adunit.adslot` targeting 

- src/test/groovy/org/prebid/server/functional/tests/pg/TokenSpec.groovy
- src/test/groovy/org/prebid/server/functional/util/HttpUtil.groovy
Test for https://github.com/prebid/prebid-server-java/pull/2044
> Test: Add support for `X-Prebid-PG-ignore-pacing` header 

- src/test/groovy/org/prebid/server/functional/tests/UserSyncSpec.groovy
- src/test/groovy/org/prebid/server/functional/util/HttpUtil.groovy
Test for https://github.com/prebid/prebid-server-java/pull/2037
> Test: Cookie-sync redirect url substitution when uid macro is absent

- src/main/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidder.java
- src/main/java/org/prebid/server/bidder/adnuntius/model/request/AdnuntiusAdUnit.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/adnuntius/ExtDeviceAdnuntius.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/adnuntius/ExtImpAdnuntius.java
- src/main/resources/static/bidder-params/adnuntius.json
- src/test/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/adnuntius/test-adnuntius-bid-request.json
Corresponding tickets: https://github.com/prebid/prebid-server/pull/2352 and https://github.com/prebid/prebid-server/pull/2306
> Core: Update Adnuntius Bidder

- src/test/groovy/org/prebid/server/functional/tests/pg/TargetingSpec.groovy
Test for https://github.com/prebid/prebid-server-java/pull/2058
> Test: Add functional test for PG Targeting video lookup size

- src/test/groovy/org/prebid/server/functional/model/bidder/BidderName.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Bidder.groovy
- src/test/groovy/org/prebid/server/functional/model/response/auction/ErrorType.groovy
- src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsEnforcementSpec.groovy
Test for https://github.com/prebid/prebid-server-java/pull/2064
> Test: Aliases compression property read 

- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
Fix for https://github.com/prebid/prebid-server-java/pull/2059
> Tests: Fix for Refine FPD

- src/test/groovy/org/prebid/server/functional/tests/AmpSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/AuctionSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/TimeoutSpec.groovy
Test for https://github.com/prebid/prebid-server-java/pull/2068
> Tests: Update an auction timeout if `bidRequest.tmax` has changed 

- src/test/groovy/org/prebid/server/functional/model/request/auction/Pbs.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Prebid.groovy
- src/test/groovy/org/prebid/server/functional/tests/AuctionSpec.groovy
Test for https://github.com/prebid/prebid-server-java/pull/2063
> Tests: Remove redundant fields from bidder request

- src/main/java/org/prebid/server/auction/requestfactory/Ortb2ImplicitParametersResolver.java
- src/test/groovy/org/prebid/server/functional/model/request/auction/Device.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/DeviceExt.groovy
- src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/LmtSpec.groovy
- src/test/groovy/org/prebid/server/functional/util/PBSUtils.groovy
- src/test/java/org/prebid/server/auction/requestfactory/Ortb2ImplicitParametersResolverTest.java
https://github.com/prebid/prebid-server/issues/1699
> `lmt` bug fix

- src/main/resources/bidder-config/ix.yaml
This is a port of https://github.com/prebid/prebid-server/pull/2328
> IX: Add iframe usersync support

- src/main/resources/bidder-config/dianomi.yaml
We noticed somehow the endpoint in our Yaml was wrong, so a nice simple PR to update it :)
> Dianomi: Endpoint update

- src/test/groovy/org/prebid/server/functional/tests/CookieSyncSpec.groovy
Fix for https://github.com/prebid/prebid-server-java/pull/2089
> Cookie-sync: Fix functional tests

- src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
Tests for [issue 2478](https://github.com/prebid/prebid-server/issues/2478)
> Add functional tests for `imp.secure`

- src/test/groovy/org/prebid/server/functional/model/bidder/Rubicon.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Prebid.groovy
- src/test/groovy/org/prebid/server/functional/model/response/auction/ImpRejectionReason.groovy
- src/test/groovy/org/prebid/server/functional/model/response/auction/NonBid.groovy
- src/test/groovy/org/prebid/server/functional/model/response/auction/SeatNonBid.groovy
- src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/NetworkScaffolding.groovy
- src/test/groovy/org/prebid/server/functional/tests/AuctionSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/DebugSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/HttpSettingsSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pg/TargetingSpec.groovy
Test for https://github.com/prebid/prebid-server-java/pull/2109
> Functional test for feature `returnallbidstatus` flag

- src/test/groovy/org/prebid/server/functional/tests/OrtbConverterSpec.groovy
Tests for https://github.com/prebid/prebid-server-java/pull/2117
> Tests for remove `gpp` data for 2.5 adapters.

- src/test/groovy/org/prebid/server/functional/tests/DebugSpec.groovy
Tests for https://github.com/prebid/prebid-server-java/pull/2122
> Fix functional `returnallbidstatus flag` tests

- src/test/groovy/org/prebid/server/functional/model/request/auction/BidRequest.groovy
- src/test/groovy/org/prebid/server/functional/service/PrebidServerService.groovy
- src/test/groovy/org/prebid/server/functional/tests/TimeoutSpec.groovy
Tests for https://github.com/prebid/prebid-server-java/pull/2113
> Functional tests for lower `tmax`

- .github/workflows/cross-repo-issue.yml
The PBS-Java version of the workflow added in prebid/prebid-cache#123
> Workflows: Cross-repo workflow

- .github/workflows/issue_prioritization.yml
applying the changes needed to accommodate the GH API updates as defined in https://github.com/prebid/prebid-server/pull/2547/files
> issue tracker workflow changes

- src/test/groovy/org/prebid/server/functional/model/request/cookiesync/CookieSyncRequest.groovy
- src/test/groovy/org/prebid/server/functional/tests/UserSyncSpec.groovy
Test for https://github.com/prebid/prebid-server-java/pull/2127
> Tests: Functional tests for `gpp`

- src/main/resources/bidder-config/resetdigital.yaml
they recently obtained a vendor ID
> Resetdigital: add GVL ID

- src/main/java/org/prebid/server/bidder/algorix/AlgorixBidder.java
- src/main/resources/static/bidder-params/algorix.json
- src/test/java/org/prebid/server/bidder/algorix/AlgorixBidderTest.java
update Algorix bidder support EU endpoint(use EUC region bidder param)
> Algorix: Add EUC endpoint

- src/main/resources/bidder-config/ccx.yaml
> CCX: Add user sync url

- src/test/groovy/org/prebid/server/functional/service/PrebidServerService.groovy
```
Error:  Failures: 
Error:    PriceFloorsFetchingSpec.PBS should log error and increase #FETCH_FAILURE_METRIC when Floors Provider's response size is more than fetch.max-file-size-kb:725 Condition not satisfied:
floorsLogs.size() == 1
|          |      |
[]         0      false
```
> Test: Fix functional tests with `logs`

- src/main/resources/bidder-config/between.yaml
> Between: Changed userSync url

- src/main/resources/bidder-config/generic.yaml
- src/test/resources/org/prebid/server/it/test-application.properties
> Blue: Add new bidder

- src/main/java/org/prebid/server/bidder/appnexus/AppnexusBidder.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/appnexus/ExtImpAppnexus.java
- src/main/resources/static/bidder-params/appnexus.json
- src/test/java/org/prebid/server/bidder/appnexus/AppnexusBidderTest.java
> AppNexus: Accept placementId as int or string

- src/main/java/org/prebid/server/bidder/zeta_global_ssp/ZetaGlobalSspBidder.java
- src/main/java/org/prebid/server/spring/config/bidder/ZetaGlobalSspConfiguration.java
- src/main/resources/bidder-config/zeta_global_ssp.yaml
- src/main/resources/static/bidder-params/zeta_global_ssp.json
- src/test/java/org/prebid/server/bidder/zeta_global_ssp/ZetaGlobalSspBidderTest.java
- src/test/java/org/prebid/server/it/ZetaGlobalSspTest.java
- src/test/resources/org/prebid/server/it/openrtb2/zeta_global_ssp/test-auction-zeta_global_ssp-request.json
- src/test/resources/org/prebid/server/it/openrtb2/zeta_global_ssp/test-auction-zeta_global_ssp-response.json
- src/test/resources/org/prebid/server/it/openrtb2/zeta_global_ssp/test-zeta_global_ssp-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/zeta_global_ssp/test-zeta_global_ssp-bid-response.json
- src/test/resources/org/prebid/server/it/test-application.properties
Docs: https://github.com/prebid/prebid.github.io/pull/4464
> New Adapter: Zeta Global SSP

- src/main/resources/bidder-config/madvertise.yaml
Madvertise: Updated contact email address
> Madvertise: Updated contact email address

- src/main/resources/bidder-config/impactify.yaml
Impactify: Updated contact email address
> Impactify: Updated contact email address

- src/main/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidder.java
- src/main/java/org/prebid/server/bidder/adnuntius/model/response/AdnuntiusAd.java
- src/test/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/adnuntius/test-adnuntius-bid-response.json
- src/test/resources/org/prebid/server/it/openrtb2/adnuntius/test-auction-adnuntius-response.json
> Adnuntius: Added dealId field

- src/main/java/org/prebid/server/bidder/limelightdigital/LimeLightDigitalBidder.java
- src/main/resources/bidder-config/limelightDigital.yaml
- src/test/java/org/prebid/server/bidder/limelightdigital/LimeLightDigitalBidderTest.java
- src/test/resources/org/prebid/server/it/test-application.properties
> Evtech: Added new bidder

- src/test/groovy/org/prebid/server/functional/testcontainers/PbsConfig.groovy
- src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
Fix for https://github.com/prebid/prebid-server-java/pull/2303
> Tests: Add functional fix for circumvent generic alias

- src/test/groovy/org/prebid/server/functional/model/request/auction/Imp.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Qty.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/RefSettings.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/RefType.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Refresh.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/SourceType.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Video.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/VideoPlacementSubtypes.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/VideoPlcmtSubtype.groovy
- src/test/groovy/org/prebid/server/functional/tests/OrtbConverterSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsCurrencySpec.groovy
- src/test/groovy/org/prebid/server/functional/util/PBSUtils.groovy
Tests for https://github.com/prebid/prebid-server-java/pull/2333
> Tests: Functional tests for `ortb` new fields

- src/main/java/org/prebid/server/validation/RequestValidator.java
- src/test/java/org/prebid/server/validation/RequestValidatorTest.java
- remove validation exception for empty eids
- update test
https://github.com/prebid/prebid-server/issues/2712
> Allow empty EIDs field

- src/main/java/org/prebid/server/bidder/pubmatic/PubmaticBidder.java
- src/test/java/org/prebid/server/bidder/pubmatic/PubmaticBidderTest.java
Implementation of https://github.com/prebid/prebid-server-java/issues/2339
> Pubmatic: Update kadfloor resolution

- src/main/resources/bidder-config/adview.yaml
Changes from https://github.com/prebid/prebid-server-java/issues/2330
> Adview: Endpoint configuration updates

- src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitUfpdActivitiesSpec.groovy
Update functional tests for https://github.com/prebid/prebid-server-java/pull/2358
> Tests: Add `user.id` for transmitUfpdSpec

- src/test/groovy/org/prebid/server/functional/model/request/auction/App.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/BidRequest.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Dooh.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Site.groovy
- src/test/groovy/org/prebid/server/functional/tests/OrtbConverterSpec.groovy
Tests for https://github.com/prebid/prebid-server-java/pull/2343
> Tests: Add functional tests for new 2.6 ortb fields

- src/main/resources/bidder-config/smartadserver.yaml
SmartAdServer is now owned by Equativ
> Update smartadserver contact info

- src/main/resources/bidder-config/smartadserver.yaml
> revising smartadserver contact

- src/main/java/org/prebid/server/cookie/UidsCookieService.java
- src/main/java/org/prebid/server/cookie/proto/Uids.java
- src/test/groovy/org/prebid/server/functional/model/UidsCookie.groovy
- src/test/groovy/org/prebid/server/functional/tests/HttpSettingsSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/SetUidSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pg/UserDetailsSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GppSyncUserActivitiesSpec.groovy
- src/test/java/org/prebid/server/cookie/UidsCookieServiceTest.java
- src/test/java/org/prebid/server/cookie/UidsCookieTest.java
- src/test/java/org/prebid/server/handler/GetuidsHandlerTest.java
- src/test/java/org/prebid/server/it/ApplicationTest.java
Changes from https://github.com/prebid/prebid-server-java/issues/2403
> Cookie-sync: Remove bday field from uids cookie

- src/test/groovy/org/prebid/server/functional/model/request/auction/RegsExt.groovy
- src/test/groovy/org/prebid/server/functional/tests/OrtbConverterSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GppAuctionSpec.groovy
Test for https://github.com/prebid/prebid-server-java/pull/2450
> Tests: `gpc` field

- src/test/groovy/org/prebid/server/functional/tests/InfoBiddersSpec.groovy
Updated tests for use **enabledOnly** variable in request
> Tests: Fix for info bidders spec

- src/main/java/org/prebid/server/bidder/smartadserver/SmartadserverBidder.java
- src/main/resources/bidder-config/smartadserver.yaml
- src/test/java/org/prebid/server/bidder/smartadserver/SmartadserverBidderTest.java
Pull request for [this issue](https://github.com/prebid/prebid-server-java/issues/2444)
> SmartAdServer: Added native support

- src/main/resources/bidder-config/imds.yaml
IMDS does not support syncing outside of the US/Canada
> Added note IMDS sync note

- docs/developers/unit-tests.md
Addresses: https://github.com/prebid/prebid-server-java/issues/2471
> Documentation: How to run unit tests

- src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAmpSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/PrivacyBaseSpec.groovy
Reimplement https://github.com/prebid/prebid-server-java/pull/2554
> Test: Fix flaky `gdpr` functional test

- src/test/groovy/org/prebid/server/functional/tests/AuctionSpec.groovy
Test for https://github.com/prebid/prebid-server-java/pull/2553
> Tests: Convert `region` to uppercase

- src/main/java/org/prebid/server/spring/config/WebConfiguration.java
- src/main/resources/application.yaml
Details about SO_REUSEPORT: https://man7.org/linux/man-pages/man7/socket.7.html
Deatils about TCP_QUICKACK: https://man7.org/linux/man-pages/man7/tcp.7.html
> TCP Native Transport properties for Vert.x HttpServerOptions

- src/main/java/org/prebid/server/handler/info/BiddersHandler.java
- src/main/java/org/prebid/server/handler/info/filters/BaseOnlyBidderInfoFilterStrategy.java
- src/main/java/org/prebid/server/handler/info/filters/BidderInfoFilterStrategy.java
- src/main/java/org/prebid/server/handler/info/filters/EnabledOnlyBidderInfoFilterStrategy.java
- src/main/java/org/prebid/server/spring/config/WebConfiguration.java
- src/test/groovy/org/prebid/server/functional/service/PrebidServerService.groovy
- src/test/groovy/org/prebid/server/functional/tests/InfoBiddersSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/LmtSpec.groovy
- src/test/groovy/org/prebid/server/functional/util/PBSUtils.groovy
- src/test/java/org/prebid/server/handler/info/BiddersHandlerTest.java
- src/test/java/org/prebid/server/it/ApplicationTest.java
According to https://github.com/prebid/prebid-server/issues/3079
> Add baseadaptersonly Query Param to Bidder Info

- src/main/java/org/prebid/server/bidder/stroeercore/StroeerCoreBidder.java
- src/main/java/org/prebid/server/bidder/stroeercore/model/StroeerCoreBid.java
- src/main/resources/bidder-config/stroeercore.yaml
- src/test/java/org/prebid/server/bidder/stroeercore/StroeerCoreBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/stroeercore/test-auction-stroeercore-request.json
- src/test/resources/org/prebid/server/it/openrtb2/stroeercore/test-auction-stroeercore-response.json
- src/test/resources/org/prebid/server/it/openrtb2/stroeercore/test-stroeercore-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/stroeercore/test-stroeercore-bid-response.json
Pass request video impressions to StroeerCore and properly process bid response from StroeerCore.
> Update Bidder Stroeercore: allow video traffic

- docs/config-app.md
- src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
- src/main/resources/application.yaml
- src/test/resources/org/prebid/server/it/test-application.properties
> Finished transition period for "auction.generate-source-tid" property

- src/main/resources/bidder-config/zeta_global_ssp.yaml
Get rid of `shortname` in bidding and user sync endpoints.
> Zeta Global SSP Bidder: update endpoints.

- src/main/resources/bidder-config/lunamedia.yaml
Results of a conversation with the lunamedia team
> lunamedia endpoint update

- src/main/java/org/prebid/server/bidder/gumgum/GumgumBidder.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/gumgum/ExtImpGumgum.java
- src/main/resources/static/bidder-params/gumgum.json
- src/test/java/org/prebid/server/bidder/gumgum/GumgumBidderTest.java
IN this changes we will start to pass the product param from Prebid Server to GG Ad Server under the impressions.ext param.
For any questions/comments pls feel free to reach out
Thanks
Natalia Castiglioni
> Add product support for gumgum

- src/test/groovy/org/prebid/server/functional/tests/TargetingSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAmpSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
Corresponding https://github.com/prebid/prebid-server-java/pull/2757 PR
> Test: Update gdpr log message and targeting

- src/main/resources/bidder-config/teads.yaml
> Teads: endpoint change

- src/main/java/org/prebid/server/bidder/freewheelssp/FreewheelSSPBidder.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/freewheelssp/ExtImpFreewheelSSP.java
- src/main/resources/bidder-config/freewheelssp.yaml
- src/main/resources/static/bidder-params/freewheelssp.json
- src/test/java/org/prebid/server/bidder/freewheelssp/FreewheelSSPBidderTest.java
Added support of GPP, ZoneID support of Integer or String values.
> FreewheelSSP bidder updates

- src/main/java/org/prebid/server/bidder/HttpBidderRequestEnricher.java
- src/main/java/org/prebid/server/util/HttpUtil.java
- src/test/groovy/org/prebid/server/functional/testcontainers/scaffolding/Bidder.groovy
- src/test/groovy/org/prebid/server/functional/tests/HeaderSpec.groovy
- src/test/java/org/prebid/server/bidder/HttpBidderRequestEnricherTest.java
https://github.com/prebid/prebid-server/issues/2646
> Forward Low Entropy Client Hints to Bidders

- src/main/resources/bidder-config/taboola.yaml
Corresponding issue https://github.com/prebid/prebid-server-java/issues/2617
> Taboola bidder adapter change endpoint

- docs/application-settings.md
Found an inconsistency in the example
> Fix application settings doc

- src/main/resources/bidder-config/imds.yaml
- src/main/resources/bidder-config/lockerdome.yaml
- src/main/resources/bidder-config/lunamedia.yaml
- src/main/resources/bidder-config/mobilefuse.yaml
- src/main/resources/bidder-config/rubicon.yaml
- src/main/resources/bidder-config/smaato.yaml
- src/main/resources/bidder-config/thirtythreeacross.yaml
Port of PR from Go resolves https://github.com/prebid/prebid-server-java/issues/2890
> adding geoscope entries

- src/main/java/org/prebid/server/bidder/stroeercore/StroeerCoreBidder.java
- src/main/java/org/prebid/server/bidder/stroeercore/model/StroeerCoreBid.java
- src/test/java/org/prebid/server/bidder/stroeercore/StroeerCoreBidderTest.java
Support for Digital Services Act (DSA)
> StroeerCore: support DSA

- src/main/resources/static/index.html
set static index page to use HTTPS link to prebid.org -- resolves https://github.com/prebid/prebid-server-java/issues/3010
> Update index page

- docs/application-settings.md
Missing documentation for new application properties described here: https://github.com/prebid/prebid-server/issues/2904
> Docs: Documentation for transmitEids

- pom.xml
> add Netty epoll arm64 dependency

- src/main/resources/bidder-config/rtbhouse.yaml
Regional endpoints made available.
Relates to https://github.com/prebid/prebid-server/pull/3551
Please reach us at [inventory_support@rtbhouse.com](mailto:inventory_support@rtbhouse.com) with [piotr.jaworski@rtbhouse.com](mailto:piotr.jaworski@rtbhouse.com) and cc [leandro.otani@rtbhouse.com](mailto:leandro.otani@rtbhouse.com).
> RTB House: regional endpoints

- src/main/resources/bidder-config/adf.yaml
prebid-server PR - https://github.com/prebid/prebid-server/pull/3585
> Adf adapter: cookie matching domain updated

- src/main/java/org/prebid/server/bidder/smrtconnect/SmrtconnectBidder.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/smrtconnect/ExtImpSmrtconnect.java
- src/main/java/org/prebid/server/spring/config/bidder/SmrtconnectConfiguration.java
- src/main/resources/bidder-config/smrtconnect.yaml
- src/main/resources/static/bidder-params/smrtconnect.json
- src/test/java/org/prebid/server/bidder/smrtconnect/SmrtconnectBidderTest.java
- src/test/java/org/prebid/server/it/SmrtconnectTest.java
- src/test/resources/org/prebid/server/it/openrtb2/smrtconnect/test-auction-smrtconnect-request.json
- src/test/resources/org/prebid/server/it/openrtb2/smrtconnect/test-auction-smrtconnect-response.json
- src/test/resources/org/prebid/server/it/openrtb2/smrtconnect/test-smrtconnect-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/smrtconnect/test-smrtconnect-bid-response.json
- src/test/resources/org/prebid/server/it/test-application.properties
I have added adapter for smrtconnect
> Smrtconnect: Add new bidder

- src/main/java/org/prebid/server/bidder/iqzone/IqzoneBidder.java
- src/test/java/org/prebid/server/bidder/iqzone/IqzoneBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/iqzone/test-auction-iqzone-response.json
- src/test/resources/org/prebid/server/it/openrtb2/iqzone/test-iqzone-bid-response.json
This reverts commit 9b842c5ac73ad22b621acd0326b98badc0127fa4.
https://github.com/prebid/prebid-server-java/pull/3044
> Revert "Iqzone: Add mType support (#3044)"

- src/main/java/org/prebid/server/bidder/iqzone/IqzoneBidder.java
- src/test/java/org/prebid/server/bidder/iqzone/IqzoneBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/iqzone/test-auction-iqzone-response.json
- src/test/resources/org/prebid/server/it/openrtb2/iqzone/test-iqzone-bid-response.json
This reverts commit a46a54c716a418697cde7bfcb7dafa28bf68122b.
https://github.com/prebid/prebid-server-java/pull/3089
> Revert "Revert "Iqzone: Add mType support (#3044)" (#3089)"

- src/main/resources/application.yaml
Relarted to https://github.com/prebid/prebid-server-java/pull/3028
> Housekeeping: Remove unused PG properties

- src/main/resources/bidder-config/mgidx.yaml
Related to issue https://github.com/prebid/prebid-server-java/issues/3138
> Update mgidx endpoints

- src/main/java/org/prebid/server/auction/BidResponseCreator.java
- src/main/java/org/prebid/server/settings/model/AccountAuctionEventConfig.java
This reverts commit 988fcbe343c1984905f03157e1d321e9c9bddfb6.
> Revert "Core: Finish transition period for alias resolving (#2644)"

- src/main/java/org/prebid/server/proto/openrtb/ext/request/rise/ExtImpRise.java
- src/main/resources/static/bidder-params/rise.json
- src/test/java/org/prebid/server/bidder/rise/RiseBidderTest.java
- src/test/java/org/prebid/server/it/RiseTest.java
- src/test/resources/org/prebid/server/it/openrtb2/rise/test-auction-rise-request.json
- src/test/resources/org/prebid/server/it/openrtb2/rise/test-rise-bid-request.json
> Rise: Add placementId parameter to bidder ext

- src/test/groovy/org/prebid/server/functional/model/bidder/BidderName.groovy
- src/test/groovy/org/prebid/server/functional/model/pricefloors/ModelGroup.groovy
- src/test/groovy/org/prebid/server/functional/model/pricefloors/PriceFloorData.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/ExtPrebidPriceFloorEnforcement.groovy
- src/test/groovy/org/prebid/server/functional/tests/AliasSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/AuctionSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/BaseSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsBaseSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsEnforcementSpec.groovy
> Add functional tests for noFloorSignalBidders support

- src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
- src/main/java/org/prebid/server/bidder/rubicon/proto/request/RubiconVideoExtRp.java
- src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java
> Rubicon: Remove only server side video.size_id logic

- src/test/groovy/org/prebid/server/functional/tests/privacy/GppAmpSpec.groovy
> Test: Warning for invalid `gppSid`

- src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
- src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java
> Rubicon: No longer copy FPD fields

- src/main/resources/bidder-config/epsilon.yaml
- src/test/resources/org/prebid/server/it/openrtb2/epsilon/alias/test-epsilon-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/epsilon/test-epsilon-bid-request.json
- [ x] documentation
- [ x] configuration
Updating server docs based on dev team requests
updating documentation to match what we support
Tested and looked at code base
> Epsilon: Update endpoint and ORTB supported version

- docs/application-settings.md
> Documentation: Add missed account properties

- docs/build-aws.md
This PR includes details on Prebid Server Deployment on AWS solution and associated links.
_Prebid Server Deployment on AWS_ solution is an open-source solution which allows users to easily deploy and operate Prebid Server. Including this in the `docs` will facilitate users looking to adopt Prebid Server to quickly discover and deploy Prebid Server into their AWS accounts.
N/A.
> Update build-aws.md to include documentation on Prebid Server Deployment on AWS Solution

- src/main/java/org/prebid/server/bidder/appnexus/AppnexusBidder.java
- src/main/java/org/prebid/server/bidder/appnexus/proto/AppnexusExtImp.java
- src/main/java/org/prebid/server/bidder/appnexus/proto/ExtImp.java
- src/test/java/org/prebid/server/bidder/appnexus/AppnexusBidderTest.java
> Appnexus Bidder: Forward GPID

- src/main/java/org/prebid/server/bidder/pubmatic/PubmaticBidder.java
- src/main/java/org/prebid/server/bidder/pubmatic/model/request/PubmaticBidderImpExt.java
- src/test/java/org/prebid/server/bidder/pubmatic/PubmaticBidderTest.java
> Pubmatic: pass gpid

- src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
- src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/magnite/test-magnite-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/rubicon/test-rubicon-bid-request.json
> Rubicon Bidder: Support Segtax

- src/main/resources/bidder-config/mabidder.yaml
> Mabidder: Set geoscope to CAN

- src/main/resources/bidder-config/nobid.yaml
> Nobid: Add iframe sync support

- src/main/resources/bidder-config/axonix.yaml
> Axonix: Add userSync

- src/main/resources/bidder-config/ix.yaml
- src/test/resources/org/prebid/server/it/openrtb2/ix/test-ix-bid-request.json
> IX: indicate support for OpenRTB 2.6

- src/main/java/org/prebid/server/auction/ExchangeService.java
- src/main/java/org/prebid/server/auction/StoredResponseProcessor.java
- src/test/groovy/org/prebid/server/functional/tests/SeatNonBidSpec.groovy
- src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
- src/test/java/org/prebid/server/auction/StoredResponseProcessorTest.java
> Fix Seat Non Bid Returning on the Stored Response

- src/test/groovy/org/prebid/server/functional/model/pricefloors/PriceFloorField.groovy
- src/test/groovy/org/prebid/server/functional/model/pricefloors/Rule.groovy
- src/test/groovy/org/prebid/server/functional/model/response/auction/ErrorType.groovy
- src/test/groovy/org/prebid/server/functional/tests/BaseSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/EidsSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsBaseSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsCurrencySpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsEnforcementSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsRulesSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsSignalingSpec.groovy
> Test: Price floors per bidder

- src/main/resources/bidder-config/pgamssp.yaml
> PgamSSP: Gpp support

- src/main/java/org/prebid/server/cache/BasicModuleCacheService.java
- src/test/java/org/prebid/server/cache/BasicModuleCacheServiceTest.java
> Core: Make app required field for module storage

- .github/workflows/issue_prioritization.yml
> Workflows: Update issue tracking node version

- src/main/java/org/prebid/server/bidder/smaato/SmaatoBidder.java
- src/main/resources/bidder-config/smaato.yaml
- src/test/java/org/prebid/server/bidder/smaato/SmaatoBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/smaato/test-smaato-bid-request.json
> Smaato Bidder: Update Client Version

- src/main/resources/static/bidder-params/yandex.json
> Yandex: Bidder Params

- src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/rubicon/ExtImpRubicon.java
- src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java
> Rubicon: Remove pchain support

- src/main/java/org/prebid/server/bidder/yeahmobi/YeahmobiBidder.java
- src/main/java/org/prebid/server/util/BidderUtil.java
- src/main/resources/bidder-config/yeahmobi.yaml
- src/test/java/org/prebid/server/bidder/yeahmobi/YeahmobiBidderTest.java
> Yeahmobi: Update bidder

- src/main/java/org/prebid/server/bidder/admatic/AdmaticBidder.java
- src/main/java/org/prebid/server/bidder/loyal/LoyalBidder.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/admatic/AdmaticImpExt.java
- src/main/java/org/prebid/server/spring/config/bidder/AdmaticConfiguration.java
- src/main/resources/bidder-config/admatic.yaml
- src/main/resources/static/bidder-params/admatic.json
- src/test/java/org/prebid/server/bidder/admatic/AdmaticBidderTest.java
- src/test/java/org/prebid/server/it/AdmaticTest.java
- src/test/resources/org/prebid/server/it/openrtb2/admatic/test-admatic-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/admatic/test-admatic-bid-response.json
- src/test/resources/org/prebid/server/it/openrtb2/admatic/test-auction-admatic-request.json
- src/test/resources/org/prebid/server/it/openrtb2/admatic/test-auction-admatic-response.json
- src/test/resources/org/prebid/server/it/test-application.properties
> Admatic Bidder

- src/main/java/org/prebid/server/bidder/driftpixel/DriftpixelBidder.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/driftpixel/DriftpixelImpExt.java
- src/main/java/org/prebid/server/spring/config/bidder/DriftpixelConfiguration.java
- src/main/resources/bidder-config/driftpixel.yaml
- src/main/resources/static/bidder-params/driftpixel.json
- src/test/java/org/prebid/server/bidder/driftpixel/DriftpixelBidderTest.java
- src/test/java/org/prebid/server/it/DriftpixelTest.java
- src/test/resources/org/prebid/server/it/openrtb2/driftpixel/test-auction-driftpixel-request.json
- src/test/resources/org/prebid/server/it/openrtb2/driftpixel/test-auction-driftpixel-response.json
- src/test/resources/org/prebid/server/it/openrtb2/driftpixel/test-driftpixel-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/driftpixel/test-driftpixel-bid-response.json
- src/test/resources/org/prebid/server/it/test-application.properties
> Driftpixel Bidder

- src/main/java/org/prebid/server/bidder/mediago/MediaGoBidder.java
- src/main/java/org/prebid/server/bidder/mediago/MediaGoExt.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/mediago/MediaGoImpExt.java
- src/main/java/org/prebid/server/spring/config/bidder/MediaGoConfiguration.java
- src/main/resources/bidder-config/mediago.yaml
- src/main/resources/static/bidder-params/mediago.json
- src/test/java/org/prebid/server/bidder/mediago/MediaGoBidderTest.java
- src/test/java/org/prebid/server/it/MediaGoTest.java
- src/test/resources/org/prebid/server/it/openrtb2/mediago/test-auction-mediago-request.json
- src/test/resources/org/prebid/server/it/openrtb2/mediago/test-auction-mediago-response.json
- src/test/resources/org/prebid/server/it/openrtb2/mediago/test-mediago-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/mediago/test-mediago-bid-response.json
- src/test/resources/org/prebid/server/it/test-application.properties
> MediaGo Bidder

- src/main/resources/bidder-config/smarthub.yaml
- src/test/java/org/prebid/server/it/TredioTest.java
- src/test/resources/org/prebid/server/it/openrtb2/tredio/test-auction-tredio-request.json
- src/test/resources/org/prebid/server/it/openrtb2/tredio/test-auction-tredio-response.json
- src/test/resources/org/prebid/server/it/openrtb2/tredio/test-tredio-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/tredio/test-tredio-bid-response.json
- src/test/resources/org/prebid/server/it/test-application.properties
> Smarthub Bidder: Tredio Alias

- src/main/java/org/prebid/server/bidder/openweb/OpenWebBidder.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/openweb/ExtImpOpenweb.java
- src/main/resources/bidder-config/openweb.yaml
- src/main/resources/static/bidder-params/openweb.json
- src/test/java/org/prebid/server/bidder/openweb/OpenWebBidderTest.java
- src/test/java/org/prebid/server/it/OpenWebTest.java
- src/test/resources/org/prebid/server/it/openrtb2/openweb/test-auction-openweb-request.json
- src/test/resources/org/prebid/server/it/openrtb2/openweb/test-auction-openweb-response.json
- src/test/resources/org/prebid/server/it/openrtb2/openweb/test-openweb-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/openweb/test-openweb-bid-response.json
> Openweb: Update bidder

- src/main/java/org/prebid/server/bidder/freewheelssp/FreewheelSSPBidder.java
- src/test/java/org/prebid/server/bidder/freewheelssp/FreewheelSSPBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/freewheelssp/test-freewheelssp-bid-request.json
> Freewheelssp: Update bidder

- src/main/java/org/prebid/server/auction/SkippedAuctionService.java
- src/test/java/org/prebid/server/auction/SkippedAuctionServiceTest.java
> SkipAuction Fix

- src/main/java/org/prebid/server/bidder/displayio/DisplayioBidder.java
- src/main/java/org/prebid/server/bidder/displayio/DisplayioRequestExt.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/displayio/DisplayioImpExt.java
- src/main/java/org/prebid/server/spring/config/bidder/DisplayioConfiguration.java
- src/main/resources/bidder-config/displayio.yaml
- src/main/resources/static/bidder-params/displayio.json
- src/test/java/org/prebid/server/bidder/displayio/DisplayioBidderTest.java
- src/test/java/org/prebid/server/it/DisplayioTest.java
- src/test/resources/org/prebid/server/it/openrtb2/displayio/test-auction-displayio-request.json
- src/test/resources/org/prebid/server/it/openrtb2/displayio/test-auction-displayio-response.json
- src/test/resources/org/prebid/server/it/openrtb2/displayio/test-displayio-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/displayio/test-displayio-bid-response.json
- src/test/resources/org/prebid/server/it/test-application.properties
> Displayio Bidder

- src/main/resources/bidder-config/inmobi.yaml
> InMobi: include iframe & native for M-Web

- src/main/resources/bidder-config/adprime.yaml
> Adprime Bidder Update

- src/test/groovy/org/prebid/server/functional/model/bidder/Generic.groovy
- src/test/groovy/org/prebid/server/functional/model/bidderspecific/BidderImp.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/ImpExt.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/ImpExtContext.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/ImpExtContextData.groovy
- src/test/groovy/org/prebid/server/functional/tests/BidderParamsSpec.groovy
> Test: `imp.ext`

- src/main/resources/bidder-config/criteo.yaml
> Criteo Bidder: Native Support

- src/main/java/org/prebid/server/bidder/adkernel/AdkernelBidder.java
- src/test/java/org/prebid/server/bidder/adkernel/AdkernelBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/adkernel/test-adkernel-bid-response.json
- src/test/resources/org/prebid/server/it/openrtb2/adkernel/test-auction-adkernel-response.json
> Adkernel: Bid type resolving update

- src/main/java/org/prebid/server/bidder/connectad/ConnectAdBidder.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/connectad/ExtImpConnectAd.java
- src/main/java/org/prebid/server/spring/config/bidder/ConnectAdConfiguration.java
- src/main/resources/bidder-config/connectad.yaml
- src/main/resources/static/bidder-params/connectad.json
- src/test/java/org/prebid/server/bidder/connectad/ConnectAdBidderTest.java
> ConnectAd: Update bidder

- src/test/groovy/org/prebid/server/functional/model/mock/services/vendorlist/GvlSpecificationVersion.groovy
- src/test/groovy/org/prebid/server/functional/model/mock/services/vendorlist/VendorListResponse.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAmpSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
- src/test/groovy/org/prebid/server/functional/util/privacy/TcfConsent.groovy
> Test: `tcfPolicyVersion5`

- src/main/java/org/prebid/server/bidder/tripleliftnative/TripleliftNativeBidder.java
- src/main/java/org/prebid/server/bidder/tripleliftnative/TripleliftNativeExtImp.java
- src/main/java/org/prebid/server/bidder/tripleliftnative/TripleliftNativeExtImpData.java
- src/main/resources/bidder-config/tripleliftnative.yaml
- src/main/resources/static/bidder-params/triplelift_native.json
- src/test/java/org/prebid/server/bidder/tripleliftnative/TripleliftNativeBidderTest.java
> Triplelift Native Bidder Update

- src/test/groovy/org/prebid/server/functional/model/bidder/BidderName.groovy
- src/test/groovy/org/prebid/server/functional/model/bidderspecific/BidderImp.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Deal.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/DealExt.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/DealLineItem.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Format.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/ImpExtPrebid.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Pmp.groovy
- src/test/groovy/org/prebid/server/functional/tests/BidderFormatSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/ImpRequestSpec.groovy
> Add functional tests for bidder specific imp-level parameters

- src/main/java/org/prebid/server/bidder/unruly/UnrulyBidder.java
- src/main/java/org/prebid/server/proto/openrtb/ext/response/ExtBidPrebidVideo.java
- src/test/java/org/prebid/server/bidder/unruly/UnrulyBidderTest.java
> Unruly: Add duration to video bids

- src/main/java/org/prebid/server/bidder/amx/AmxBidder.java
- src/main/java/org/prebid/server/bidder/amx/model/AmxBidExt.java
- src/test/java/org/prebid/server/bidder/amx/AmxBidderTest.java
> AMX: Demand Source and aDomain support

- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsEnforcementSpec.groovy
One less flaky tests in the grand fight against flaking tests.
One less potential job restart.
None needed
> Tests: Fix flaky floors test

- src/main/resources/bidder-config/rubicon.yaml
The rubicon adapter will not choke on multiformat.
We need to start the process of showing others how to set this value.
> Add multiformat support for rubicon bidder

- src/main/java/org/prebid/server/bidder/criteo/CriteoBidResponse.java
- src/main/java/org/prebid/server/bidder/criteo/CriteoBidder.java
- src/main/java/org/prebid/server/bidder/criteo/CriteoExtBidResponse.java
- src/main/java/org/prebid/server/bidder/criteo/CriteoIgiExtBidResponse.java
- src/main/java/org/prebid/server/bidder/criteo/CriteoIgsIgiExtBidResponse.java
- src/test/java/org/prebid/server/bidder/criteo/CriteoBidderTest.java
> Criteo Bidder: Support Fledge

- src/test/groovy/org/prebid/server/functional/model/request/auction/BidderControls.groovy
- src/test/groovy/org/prebid/server/functional/tests/FilterMultiFormatSpec.groovy
> Increase test coverage for naming and alias cases in bidderControls

- src/main/resources/bidder-config/playdigo.yaml
> Playdigo Bidder: Usersync Support

- src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
- src/main/java/org/prebid/server/spring/config/bidder/RubiconConfiguration.java
- src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java
- src/test/java/org/prebid/server/it/MagniteTest.java
- src/test/java/org/prebid/server/it/RubiconTest.java
- src/test/java/org/prebid/server/it/hooks/HooksTest.java
- src/test/resources/org/prebid/server/it/hooks/reject/test-rubicon-bid-request-1.json
- src/test/resources/org/prebid/server/it/hooks/sample-module/test-rubicon-bid-request-1.json
- src/test/resources/org/prebid/server/it/openrtb2/magnite/test-magnite-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/rubicon/test-rubicon-bid-request.json
> Rubicon: Updated xapi integration

- src/main/java/org/prebid/server/bidder/rubicon/RubiconBidder.java
- src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java
> Rubicon: Fix currency conversion bug

- src/test/groovy/org/prebid/server/functional/tests/ImpRequestSpec.groovy
> Add a functional test to ensure that bidder implementation is always merged

- src/main/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidder.java
- src/test/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidderTest.java
> Adnuntius: Use format=prebid on adserver requests

- src/main/resources/bidder-config/smarthub.yaml
- src/test/java/org/prebid/server/it/FelixadsTest.java
- src/test/java/org/prebid/server/it/VimayxTest.java
- src/test/resources/org/prebid/server/it/openrtb2/felixads/test-auction-felixads-request.json
- src/test/resources/org/prebid/server/it/openrtb2/felixads/test-auction-felixads-response.json
- src/test/resources/org/prebid/server/it/openrtb2/felixads/test-felixads-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/felixads/test-felixads-bid-response.json
- src/test/resources/org/prebid/server/it/openrtb2/vimayx/test-auction-vimayx-request.json
- src/test/resources/org/prebid/server/it/openrtb2/vimayx/test-auction-vimayx-response.json
- src/test/resources/org/prebid/server/it/openrtb2/vimayx/test-vimayx-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/vimayx/test-vimayx-bid-response.json
- src/test/resources/org/prebid/server/it/test-application.properties
> Smarthub: New aliasses (`VimayX`, `FelixAds`)

- src/main/resources/bidder-config/consumable.yaml
> Consumable: Endpoint update

- src/main/resources/bidder-config/freewheelssp.yaml
- src/main/resources/bidder-config/kargo.yaml
- src/main/resources/bidder-config/mobilefuse.yaml
- src/main/resources/bidder-config/pulsepoint.yaml
- src/main/resources/bidder-config/vidazoo.yaml
- src/test/resources/org/prebid/server/it/openrtb2/freewheelssp/test-freewheelssp-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/kargo/test-kargo-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/mobilefuse/test-mobilefuse-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/pulsepoint/test-pulsepoint-bid-request-params-as-string.json
- src/test/resources/org/prebid/server/it/openrtb2/pulsepoint/test-pulsepoint-bid-request.json
> Bidders Ortb Version Update

- src/main/java/org/prebid/server/currency/CurrencyConversionService.java
- src/main/java/org/prebid/server/vertx/verticles/server/DaemonVerticle.java
> Fix bug caused by incorrect usage of Promise

- src/main/java/org/prebid/server/bidder/escalax/EscalaxBidder.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/escalax/ExtImpEscalax.java
- src/main/java/org/prebid/server/spring/config/bidder/EscalaxConfiguration.java
- src/main/resources/bidder-config/aax.yaml
- src/main/resources/bidder-config/aidem.yaml
- src/main/resources/bidder-config/escalax.yaml
- src/main/resources/bidder-config/freewheelssp.yaml
- src/main/resources/bidder-config/kargo.yaml
- src/main/resources/bidder-config/sovrn.yaml
- src/main/resources/bidder-config/sovrnXsp.yaml
- src/main/resources/static/bidder-params/escalax.json
- src/test/java/org/prebid/server/bidder/escalax/EscalaxBidderTest.java
- src/test/java/org/prebid/server/it/EscalaxTest.java
- src/test/resources/org/prebid/server/it/openrtb2/escalax/test-auction-escalax-request.json
- src/test/resources/org/prebid/server/it/openrtb2/escalax/test-auction-escalax-response.json
- src/test/resources/org/prebid/server/it/openrtb2/escalax/test-escalax-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/escalax/test-escalax-bid-response.json
- src/test/resources/org/prebid/server/it/test-application.properties
> Escalax Bidder

- extra/bundle/pom.xml
- pom.xml
- src/test/groovy/org/prebid/server/functional/model/ModuleName.groovy
- src/test/groovy/org/prebid/server/functional/model/config/AppVideoHtml.groovy
- src/test/groovy/org/prebid/server/functional/model/config/ModuleHookImplementation.groovy
- src/test/groovy/org/prebid/server/functional/model/config/Ortb2BlockingConfig.groovy
- src/test/groovy/org/prebid/server/functional/model/config/PbResponseCorrection.groovy
- src/test/groovy/org/prebid/server/functional/tests/module/ModuleBaseSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/module/analyticstag/AnalyticsTagsModuleSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/module/requestcorrenction/ResponseCorrectionSpec.groovy
> Test: `response correction` module

- .github/workflows/docker-image-publish.yml
Its just quality of life improvement for mac users.
> Github Actions: Add support for multiplatform docker image (x86-64, arm)

- src/test/groovy/org/prebid/server/functional/tests/TargetingSpec.groovy
> Test: `"hb_env"`

- extra/modules/pb-response-correction/src/main/java/org/prebid/server/hooks/modules/pb/response/correction/config/ResponseCorrectionModuleConfiguration.java
- extra/modules/pb-response-correction/src/main/java/org/prebid/server/hooks/modules/pb/response/correction/core/ResponseCorrectionProvider.java
- extra/modules/pb-response-correction/src/main/java/org/prebid/server/hooks/modules/pb/response/correction/v1/ResponseCorrectionAllProcessedBidResponsesHook.java
- extra/modules/pb-response-correction/src/main/java/org/prebid/server/hooks/modules/pb/response/correction/v1/ResponseCorrectionModule.java
- extra/modules/pb-response-correction/src/test/java/org/prebid/server/hooks/modules/pb/response/correction/core/ResponseCorrectionProviderTest.java
- extra/modules/pb-response-correction/src/test/java/org/prebid/server/hooks/modules/pb/response/correction/v1/ResponseCorrectionAllProcessedBidResponsesHookTest.java
Making the module bean name more specific to avoid bean name clashes.
> Make Response correction module bean name more explicit

- src/main/java/org/prebid/server/analytics/reporter/agma/AgmaAnalyticsReporter.java
- src/main/java/org/prebid/server/analytics/reporter/agma/EventBuffer.java
- src/test/java/org/prebid/server/analytics/reporter/agma/AgmaAnalyticsReporterTest.java
- src/test/java/org/prebid/server/analytics/reporter/agma/EventBufferTest.java
> Agma: Race condition fix

- src/main/java/org/prebid/server/analytics/reporter/agma/AgmaAnalyticsReporter.java
> Agma: Leftovers

- src/main/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidder.java
- src/main/java/org/prebid/server/bidder/adnuntius/model/response/AdnuntiusAd.java
- src/main/java/org/prebid/server/bidder/adnuntius/model/response/AdnuntiusAdvertiser.java
- src/main/java/org/prebid/server/bidder/adnuntius/model/response/AdnuntiusBidExt.java
- src/main/java/org/prebid/server/proto/openrtb/ext/response/ExtBidDsa.java
- src/test/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidderTest.java
> Adnuntius Adapter: DSA Support

- src/main/resources/bidder-config/generic.yaml
Fix for usersync redirect URL - need to use secure url
Usersync redirect URL was not set correctly
> Nativo: Fix usersync redirect url

- src/test/groovy/org/prebid/server/functional/model/request/auction/Eid.groovy
- src/test/groovy/org/prebid/server/functional/tests/OrtbConverterSpec.groovy
> Test:`user.eids[].{inserter,matcher,mm}`

- src/main/java/org/prebid/server/auction/AnalyticsTagsEnricher.java
- src/main/java/org/prebid/server/auction/BidsAdjuster.java
- src/main/java/org/prebid/server/auction/ExchangeService.java
- src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
- src/main/java/org/prebid/server/util/ListUtil.java
- src/main/java/org/prebid/server/util/PbsUtil.java
- src/test/java/org/prebid/server/auction/BidsAdjusterTest.java
- src/test/java/org/prebid/server/auction/ExchangeServiceTest.java
> Refactoring: Extract bidAdjustments code from exchangeService

- extra/modules/pb-response-correction/src/main/java/org/prebid/server/hooks/modules/pb/response/correction/v1/ResponseCorrectionAllProcessedBidResponsesHook.java
- src/test/groovy/org/prebid/server/functional/model/config/ModuleHookImplementation.groovy
> Rename Response Correction Hook

- src/main/java/com/iab/openrtb/request/Eid.java
- src/test/groovy/org/prebid/server/functional/model/request/auction/Eid.groovy
- src/test/groovy/org/prebid/server/functional/tests/OrtbConverterSpec.groovy
https://github.com/prebid/prebid-server/issues/3762
> Add New Fields to Eid Object

- src/test/java/org/prebid/server/bidder/rubicon/RubiconBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/generic/test-auction-generic-response.json
- src/test/resources/org/prebid/server/it/openrtb2/generic/test-generic-bid-response.json
> Passthrough bid.ext.prebid.meta

- src/test/groovy/org/prebid/server/functional/model/request/auction/StoredAuctionResponse.groovy
- src/test/groovy/org/prebid/server/functional/tests/StoredResponseSpec.groovy
> Add functional tests for stored auction response on imp lvl

- src/test/groovy/org/prebid/server/functional/tests/module/responsecorrenction/ResponseCorrectionSpec.groovy
> Test: Rename package name

- src/main/java/org/prebid/server/analytics/reporter/AnalyticsReporterDelegator.java
- src/test/java/org/prebid/server/analytics/reporter/AnalyticsReporterDelegatorTest.java
> Fix Analytics

- src/test/groovy/org/prebid/server/functional/tests/AnalyticsSpec.groovy
> Set log analytics as enabled by default in account configuration

- src/main/java/org/prebid/server/bidder/inmobi/InmobiBidder.java
- src/test/java/org/prebid/server/bidder/inmobi/InmobiBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/inmobi/test-auction-inmobi-response.json
- src/test/resources/org/prebid/server/it/openrtb2/inmobi/test-inmobi-bid-response.json
> InMobi Bidder: Mtype Support

- src/main/java/org/prebid/server/bidder/missena/MissenaAdRequest.java
- src/main/java/org/prebid/server/bidder/missena/MissenaAdResponse.java
- src/main/java/org/prebid/server/bidder/missena/MissenaBidder.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/missena/ExtImpMissena.java
- src/main/java/org/prebid/server/spring/config/bidder/MissenaConfiguration.java
- src/main/resources/bidder-config/missena.yaml
- src/main/resources/static/bidder-params/missena.json
- src/test/java/org/prebid/server/bidder/missena/MissenaBidderTest.java
- src/test/java/org/prebid/server/it/MissenaTest.java
- src/test/resources/org/prebid/server/it/openrtb2/missena/test-auction-missena-request.json
- src/test/resources/org/prebid/server/it/openrtb2/missena/test-auction-missena-response.json
- src/test/resources/org/prebid/server/it/openrtb2/missena/test-missena-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/missena/test-missena-bid-response.json
- src/test/resources/org/prebid/server/it/test-application.properties
> Missena Bidder

- .github/workflows/codeql-analysis.yml
> Github: Add CodeQl action support

- src/main/resources/bidder-config/bluesea.yaml
> BlueSea Bidder: Site Support

- src/test/groovy/org/prebid/server/functional/model/bidder/GeneralBidderAdapter.groovy
> Fix invalid functional test

- .github/pull_request_template.md
https://github.com/prebid/prebid-server/issues/3307
> Add Reviewer Checklist

- src/main/resources/static/bidder-params/loopme.json
> Loopme: update bidder params

- docs/admin-endpoints.md
Documentation for admin endpoints.
> Docs: Admin endpoints

- src/test/groovy/org/prebid/server/functional/model/pricefloors/PriceFloorData.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsBaseSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsCurrencySpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
> Add functional tests for useFetchDataRate field

- src/main/java/org/prebid/server/bidder/pgamssp/PgamSspBidder.java
- src/main/java/org/prebid/server/spring/config/bidder/PgamSspConfiguration.java
- src/test/java/org/prebid/server/bidder/pgamssp/PgamSspBidderTest.java
> PgamSsp: Add currency conversion

- src/main/resources/bidder-config/iqzone.yaml
> IqZone: Add usersync

- src/test/groovy/org/prebid/server/functional/model/config/AccountAuctionConfig.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/AdjustmentRule.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/AdjustmentType.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/BidAdjustment.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/BidAdjustmentFactors.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/BidAdjustmentMediaType.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/BidAdjustmentRule.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/BidRequest.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Prebid.groovy
- src/test/groovy/org/prebid/server/functional/tests/BidAdjustmentSpec.groovy
> Tests: Bid Adjustments Feature 

- src/main/java/org/prebid/server/bidder/HttpBidderRequester.java
- src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java
- src/test/java/org/prebid/server/bidder/HttpBidderRequesterTest.java
> Sample HttpBidderRequester Logs

- extra/modules/fiftyone-devicedetection/pom.xml
> Remove Redundant Logback Dependency

- docs/developers/code-style.md
Increasing contributor velocity
Better readability of the style guide
> Add code highlighting

- src/test/groovy/org/prebid/server/functional/tests/DebugSpec.groovy
> Test: Debug metrics

- src/main/resources/bidder-config/krushmedia.yaml
> Krushmedia: Usersync update

- src/main/resources/bidder-config/algorix.yaml
update for add Algorix GVL Vender ID.
> AlgoriX: Add GVL vendor ID

- src/main/resources/bidder-config/richaudience.yaml
https://github.com/prebid/prebid-server/pull/2343
> Richaudience Bidder: Add Redirect Sync

- src/test/groovy/org/prebid/server/functional/model/request/auction/BidRequest.groovy
- src/test/groovy/org/prebid/server/functional/tests/BidAdjustmentSpec.groovy
> Tests: `plcmt` logic to bidadjustment mediatype

- src/test/groovy/org/prebid/server/functional/testcontainers/container/PrebidServerContainer.groovy
- src/test/groovy/org/prebid/server/functional/tests/module/GeneralModuleSpec.groovy
> Add functional tests for module-execution host level config

- sample/configs/prebid-config-with-51d-dd.yaml
- sample/configs/prebid-config-with-module.yaml
> Docs: PBS sample

- src/main/resources/bidder-config/medianet.yaml
Sanitize medianet usersync iframe url
> Sanitize medianet usersync iframe url

- pom.xml
- src/test/groovy/org/prebid/server/functional/tests/TimeoutSpec.groovy
> Test: Bidder specific `tmax`

- src/test/groovy/org/prebid/server/functional/tests/AmpFpdSpec.groovy
> Update functional tests for fpd fields

- src/test/groovy/org/prebid/server/functional/model/bidder/BidderName.groovy
- src/test/groovy/org/prebid/server/functional/model/request/auction/Bidder.groovy
- src/test/groovy/org/prebid/server/functional/tests/AliasSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/ImpRequestSpec.groovy
> Test: `bidder aliases`

- src/main/resources/static/bidder-params/tradplus.json
> TradPlus: Update bidder

- src/main/java/org/prebid/server/execution/file/supplier/RemoteFileSupplier.java
- src/test/java/org/prebid/server/execution/file/supplier/RemoteFileSupplierTest.java
> Fix RemoteFileSupplier

- src/main/resources/static/bidder-params/criteo.json
- src/test/resources/org/prebid/server/it/openrtb2/criteo/test-auction-criteo-request.json
- src/test/resources/org/prebid/server/it/openrtb2/criteo/test-criteo-bid-request.json
> Criteo Bidder: Add pubid/uid fields

- src/main/resources/bidder-config/consumable.yaml
- [ x ] configuration
- [x ] tech debt (test coverage, refactorings, etc.)
Updating the Endpoint to a new version to remove the /api/v2
The /api/v2 endpoint is being retired
The new endpoint is our default and the one is being retired
> Consumable Adaptor: Updating Endpoint

- src/main/resources/bidder-config/trustedstack.yaml
Support iframe usersync for trustedstack bidder
> Add iframe usersync for trustedstack

- src/main/java/org/prebid/server/bidder/nextmillennium/NextMillenniumBidder.java
- src/main/java/org/prebid/server/spring/config/bidder/NextMillenniumConfiguration.java
- src/test/java/org/prebid/server/bidder/nextmillennium/NextMillenniumBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/nextmillennium/test-nextmillennium-bid-request.json
https://github.com/prebid/prebid-server-java/issues/3744
> NextMillennium: Adapter and server version

- src/main/resources/bidder-config/copper6ssp.yaml
https://github.com/prebid/prebid-server-java/issues/3747
> Copper6SSP: Fix endpoint

- src/main/resources/bidder-config/pubrise.yaml
https://github.com/prebid/prebid-server-java/issues/3748
> Pubrise: Fix endpoint

- src/main/resources/bidder-config/sspbc.yaml
https://github.com/prebid/prebid-server-java/issues/3749
> sspBC: Endpoint update

- src/main/resources/bidder-config/undertone.yaml
- src/test/resources/org/prebid/server/it/openrtb2/undertone/test-auction-undertone-request.json
- src/test/resources/org/prebid/server/it/openrtb2/undertone/test-undertone-bid-request.json
https://github.com/prebid/prebid-server-java/issues/3772
> Undertone: Declare OpenRTB 2.6 support

- src/main/resources/bidder-config/smarthub.yaml
- src/test/java/org/prebid/server/it/ArtechnologyTest.java
- src/test/resources/org/prebid/server/it/openrtb2/artechnology/test-artechnology-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/artechnology/test-artechnology-bid-response.json
- src/test/resources/org/prebid/server/it/openrtb2/artechnology/test-auction-artechnology-request.json
- src/test/resources/org/prebid/server/it/openrtb2/artechnology/test-auction-artechnology-response.json
- src/test/resources/org/prebid/server/it/test-application.properties
https://github.com/prebid/prebid-server-java/issues/3785
> Artechnology: port new alias of StartHub from Go

- src/main/resources/bidder-config/smarthub.yaml
- src/test/java/org/prebid/server/it/AdinifyTest.java
- src/test/resources/org/prebid/server/it/openrtb2/adinify/test-adinify-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/adinify/test-adinify-bid-response.json
- src/test/resources/org/prebid/server/it/openrtb2/adinify/test-auction-adinify-request.json
- src/test/resources/org/prebid/server/it/openrtb2/adinify/test-auction-adinify-response.json
- src/test/resources/org/prebid/server/it/test-application.properties
https://github.com/prebid/prebid-server-java/issues/3784
> Adinify: port new alias of StartHub from Go

- src/main/resources/bidder-config/smarthub.yaml
- src/test/java/org/prebid/server/it/JambojarTest.java
- src/test/resources/org/prebid/server/it/openrtb2/jambojar/test-auction-jambojar-request.json
- src/test/resources/org/prebid/server/it/openrtb2/jambojar/test-auction-jambojar-response.json
- src/test/resources/org/prebid/server/it/openrtb2/jambojar/test-jambojar-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/jambojar/test-jambojar-bid-response.json
- src/test/resources/org/prebid/server/it/test-application.properties
https://github.com/prebid/prebid-server-java/issues/3783
> Jambojar: port new alias of StartHub from Go

- .github/workflows/pr-java-ci.yml
- src/test/proto/test-opernrtb.proto
> Tests: Fix Maven build issue with IAB Tech Lab's Protobuf

- docs/developers/bid-adapter-porting-guide.md
As discussed in the PBS Java Engr sync
> Docs: Update bid-adapter-porting-guide.md

- src/main/resources/bidder-config/vidazoo.yaml
- src/test/resources/org/prebid/server/it/openrtb2/vidazoo/test-auction-vidazoo-request.json
- src/test/resources/org/prebid/server/it/openrtb2/vidazoo/test-vidazoo-bid-request.json
https://github.com/prebid/prebid-server-java/issues/3801
> Vidazoo: Declare OpenRTB 2.6 support

- src/main/java/org/prebid/server/bidder/smarthub/SmarthubBidder.java
- src/main/resources/static/bidder-params/smarthub.json
Porting change from PBS-Go
Unit and local testing
> Attekmi: remove partnerName param requirement

- src/main/java/org/prebid/server/bidder/kobler/KoblerBidder.java
- src/test/java/org/prebid/server/bidder/kobler/KoblerBidderTest.java
> Kobler: Fix NPE

- src/main/resources/bidder-config/smilewanted.yaml
https://github.com/prebid/prebid-server-java/issues/3858
> Port Smilewanted: change endpoint to HTTPS

- src/main/resources/bidder-config/nextmillennium.yaml
https://github.com/prebid/prebid-server-java/issues/3861
> Port Nextmillennium: Add gzip compression

- src/main/resources/bidder-config/improvedigital.yaml
> Port Improve Digital: Add iframe user sync

- src/test/groovy/org/prebid/server/functional/tests/AuctionSpec.groovy
> Test: Fix flaky 

- src/test/groovy/org/prebid/server/functional/tests/privacy/GppSyncUserActivitiesSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitEidsActivitiesSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitUfpdActivitiesSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/PrivacyBaseSpec.groovy
> Tests: GPP decode error shouldn't fails entire auction

- src/main/resources/static/bidder-params/appnexus.json
https://github.com/prebid/prebid-server-java/issues/3891
> AppNexus: Support member param as int

- src/main/resources/bidder-config/smaato.yaml
https://github.com/prebid/prebid-server-java/issues/3894
> Smaato: Add iframe user sync

- src/main/resources/bidder-config/algorix.yaml
https://github.com/prebid/prebid-server-java/issues/3897#event-17173740745
> Algorix: Add site support

- src/main/resources/bidder-config/improvedigital.yaml
Improve Digital adapter: add iframe sync
PBS Go PR: https://github.com/prebid/prebid-server/pull/4274
> ImproveDigital: add iframe sync

- src/main/resources/bidder-config/improvedigital.yaml
Reverts prebid/prebid-server-java#3913
> Revert "Port Improve Digital: Add iframe user sync"

- src/test/resources/org/prebid/server/it/openrtb2/addigi/test-auction-addigi-response.json
> Addigi: Fix test

- src/test/groovy/org/prebid/server/functional/model/privacy/Metric.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GppFetchBidActivitiesSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GppSyncUserActivitiesSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitEidsActivitiesSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitPreciseGeoActivitiesSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitUfpdActivitiesSpec.groovy
> Tests: fix alert.general metric conflict

- src/test/groovy/org/prebid/server/functional/model/privacy/Metric.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GppFetchBidActivitiesSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GppSyncUserActivitiesSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitEidsActivitiesSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitPreciseGeoActivitiesSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitUfpdActivitiesSpec.groovy
Reverts prebid/prebid-server-java#3943
> Revert "Tests: fix alert.general metric conflict"

- src/main/java/org/prebid/server/floors/BasicPriceFloorProcessor.java
- src/main/java/org/prebid/server/floors/PriceFloorFetcher.java
- src/main/java/org/prebid/server/floors/proto/FetchResult.java
- src/main/java/org/prebid/server/spring/config/PriceFloorsConfiguration.java
- src/test/groovy/org/prebid/server/functional/tests/BaseSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/BidValidationSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/MetricsSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/bidder/openx/OpenxSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsBaseSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsFetchingSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsRulesSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/pricefloors/PriceFloorsSignalingSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAmpSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GdprAuctionSpec.groovy
- src/test/java/org/prebid/server/floors/BasicPriceFloorProcessorTest.java
- src/test/java/org/prebid/server/floors/PriceFloorFetcherTest.java
Reverts prebid/prebid-server-java#3924
> Revert "Price Floor Logs Update"

- .github/workflows/scripts/codepath-notification
Enable TheTradeDesk bidder adapter change notifications
> GitHub: Add TheTradeDesk codepath notifications

- src/main/java/org/prebid/server/auction/gpp/model/GppModelWrapper.java
- src/test/groovy/org/prebid/server/functional/tests/privacy/GppSyncUserActivitiesSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitEidsActivitiesSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/GppTransmitUfpdActivitiesSpec.groovy
- src/test/groovy/org/prebid/server/functional/tests/privacy/PrivacyBaseSpec.groovy
- src/test/java/org/prebid/server/auction/gpp/model/GppContextCreatorTest.java
- src/test/java/org/prebid/server/auction/gpp/model/GppModelWrapperTest.java
Reverts prebid/prebid-server-java#3921
> Revert "Core: Pad GPP consent string sections"

- extra/pom.xml
For some reason, Spring Boot versions 3.4.3 and 3.4.4 significantly increased application startup time. There don’t appear to be any specific breaking changes, so this is likely caused by dependency updates:
[v3.4.3](https://github.com/spring-projects/spring-boot/releases/tag/v3.4.3)
[v3.4.4](https://github.com/spring-projects/spring-boot/releases/tag/v3.4.4)
However, more concerning part is that runtime for functional tests also increased noticeably.
> Dependencies: Change spring-boot version

- extra/pom.xml
This reverts commit 46cdf39cd7185e03543a7320c56c51d32922cf84.
> Revert "Dependencies: Change spring-boot version (#3954)"

- src/main/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidder.java
- src/main/java/org/prebid/server/bidder/adnuntius/model/request/AdnuntiusNativeRequest.java
- src/main/java/org/prebid/server/bidder/adnuntius/model/request/AdnuntiusRequest.java
- src/main/java/org/prebid/server/bidder/adnuntius/model/request/AdnuntiusRequestAdUnit.java
- src/main/java/org/prebid/server/bidder/adnuntius/model/response/AdnuntiusAdUnit.java
- src/main/java/org/prebid/server/bidder/adnuntius/model/response/AdnuntiusResponse.java
- src/main/java/org/prebid/server/spring/config/bidder/AdnuntiusBidderConfiguration.java
- src/main/resources/bidder-config/adnuntius.yaml
- src/test/java/org/prebid/server/bidder/adnuntius/AdnuntiusBidderTest.java
- src/test/java/org/prebid/server/it/AdnuntiusTest.java
- src/test/resources/org/prebid/server/it/openrtb2/adnuntius/test-adnuntius-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/adnuntius/test-adnuntius-bid-response.json
- src/test/resources/org/prebid/server/it/openrtb2/adnuntius/test-auction-adnuntius-response.json
- src/test/resources/org/prebid/server/it/test-application.properties
> Adnuntius Adapter: Add multi-format and native support

- README.md
Trying to build the server from scratch. 
it is not super clear which version of JAVA need to install. 
I found that this version is used in [pr-java-ci.yml](https://github.com/prebid/prebid-server-java/blob/master/.github/workflows/pr-java-ci.yml#L20)
> Update README.md - Add the required JAVA SDK version

- src/main/resources/bidder-config/admatic.yaml
- src/test/java/org/prebid/server/it/NetAddictionTest.java
- src/test/resources/org/prebid/server/it/openrtb2/netaddiction/test-auction-netaddiction-request.json
- src/test/resources/org/prebid/server/it/openrtb2/netaddiction/test-auction-netaddiction-response.json
- src/test/resources/org/prebid/server/it/openrtb2/netaddiction/test-netaddiction-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/netaddiction/test-netaddiction-bid-response.json
- src/test/resources/org/prebid/server/it/test-application.properties
> Admatic Alias: Netaddiction

- src/main/resources/bidder-config/pubmatic.yaml
> Pubmatic Adapter: Enable Gzip compression

- src/main/resources/bidder-config/mobilefuse.yaml
- src/main/resources/bidder-config/nextmillennium.yaml
> MobileFuse Adapter: Add usersync info

- src/main/java/org/prebid/server/bidder/smoot/SmootBidder.java
- src/main/java/org/prebid/server/bidder/smoot/SmootImpExt.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/smoot/ExtImpSmoot.java
- src/main/java/org/prebid/server/spring/config/bidder/SmootConfiguration.java
- src/main/resources/bidder-config/smoot.yaml
- src/main/resources/static/bidder-params/smoot.json
- src/test/java/org/prebid/server/bidder/smoot/SmootBidderTest.java
- src/test/java/org/prebid/server/it/SmootTest.java
- src/test/resources/org/prebid/server/it/openrtb2/smoot/test-auction-smoot-request.json
- src/test/resources/org/prebid/server/it/openrtb2/smoot/test-auction-smoot-response.json
- src/test/resources/org/prebid/server/it/openrtb2/smoot/test-smoot-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/smoot/test-smoot-bid-response.json
- src/test/resources/org/prebid/server/it/test-application.properties
> New Smoot Adapter

- src/main/java/org/prebid/server/bidder/missena/MissenaAdRequest.java
- src/main/java/org/prebid/server/bidder/missena/MissenaBidder.java
- src/test/java/org/prebid/server/bidder/missena/MissenaBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/missena/test-missena-bid-request.json
> Missena Adapter: Pass full openrtb request

- src/main/resources/bidder-config/aso.yaml
- src/test/java/org/prebid/server/it/KuantyxTest.java
- src/test/resources/org/prebid/server/it/openrtb2/kuantyx/test-auction-kuantyx-request.json
- src/test/resources/org/prebid/server/it/openrtb2/kuantyx/test-auction-kuantyx-response.json
- src/test/resources/org/prebid/server/it/openrtb2/kuantyx/test-kuantyx-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/kuantyx/test-kuantyx-bid-response.json
- src/test/resources/org/prebid/server/it/test-application.properties
> Aso Adapter: New Kuantyx Alias

- src/main/resources/bidder-config/ogury.yaml
> Ogury Adapter: Support gpp for cookie sync

- Dockerfile
- Dockerfile-modules
Minor base Java image version bump
None needed
> Housekeeping: Update Java base image version

- src/main/java/org/prebid/server/bidder/exco/ExcoBidder.java
- src/main/java/org/prebid/server/proto/openrtb/ext/request/exco/ExtImpExco.java
- src/main/java/org/prebid/server/spring/config/bidder/ExcoConfiguration.java
- src/main/resources/bidder-config/exco.yaml
- src/main/resources/static/bidder-params/exco.json
- src/test/java/org/prebid/server/bidder/exco/ExcoBidderTest.java
- src/test/java/org/prebid/server/it/ExcoTest.java
- src/test/resources/org/prebid/server/it/openrtb2/exco/test-auction-exco-request.json
- src/test/resources/org/prebid/server/it/openrtb2/exco/test-auction-exco-response.json
- src/test/resources/org/prebid/server/it/openrtb2/exco/test-exco-bid-request.json
- src/test/resources/org/prebid/server/it/openrtb2/exco/test-exco-bid-response.json
- src/test/resources/org/prebid/server/it/test-application.properties
> New Exco Adapter

- src/main/resources/bidder-config/kobler.yaml
https://github.com/prebid/prebid-server-java/issues/3898
> Kobler: Add app support

- src/main/java/org/prebid/server/bidder/onetag/OnetagBidder.java
- src/test/java/org/prebid/server/bidder/onetag/OnetagBidderTest.java
- src/test/resources/org/prebid/server/it/openrtb2/onetag/test-onetag-bid-request.json
> Onetag Adapter: imp.ext read generalization

- extra/pom.xml
> Dependencies: Bump GPP library version
